//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t decrypt_message(void);
int64_t deregister_tm_clones(void);
int64_t frame_dummy(void);
int32_t function_1030(char * format, ...);
void function_1040(int64_t * d);
int64_t multiplication_table(int64_t a1);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

char * g1 = "%2d \xc3\x97 %3d = %4d\n"; // 0x5004
int64_t g2 = 0; // 0x6fe0
int64_t g3; // 0x7187
int32_t g4;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1017
int64_t _init(void) {
    int64_t result = 0; // 0x100e
    if (*(int64_t *)0x6fd0 != 0) {
        // 0x1010
        __gmon_start__();
        result = &g4;
    }
    // 0x1012
    return result;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(char * format, ...) {
    // 0x1030
    return printf(format);
}

// Address range: 0x1040 - 0x1046
void function_1040(int64_t * d) {
    // 0x1040
    __cxa_finalize(d);
}

// Address range: 0x1050 - 0x1072
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1050
    int64_t v1; // 0x1050
    __libc_start_main(0x488a, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1080 - 0x10a9
int64_t deregister_tm_clones(void) {
    // 0x1080
    return 0x7188;
}

// Address range: 0x10b0 - 0x10e9
int64_t register_tm_clones(void) {
    // 0x10b0
    return 0;
}

// Address range: 0x10f0 - 0x1129
int64_t __do_global_dtors_aux(void) {
    // 0x10f0
    if (*(char *)0x7187 != 0) {
        // 0x1128
        int64_t result; // 0x10f0
        return result;
    }
    // 0x10fd
    if (g2 != 0) {
        // 0x110b
        __cxa_finalize((int64_t *)*(int64_t *)0x7028);
    }
    int64_t result2 = deregister_tm_clones(); // 0x1117
    *(char *)&g3 = 1;
    return result2;
}

// Address range: 0x1130 - 0x1139
int64_t frame_dummy(void) {
    // 0x1130
    return register_tm_clones();
}

// Address range: 0x1139 - 0x1383
int64_t multiplication_table(int64_t a1) {
    // 0x1139
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    return printf((char *)&g1);
}

// Address range: 0x1383 - 0x488a
int64_t decrypt_message(void) {
    // 0x1383
    int64_t v1; // bp-328, 0x1383
    int64_t v2 = &v1; // 0x1383
    *(char *)(v2 + 137) = 0;
    char * v3 = (char *)(v2 + 248); // 0x1af4
    unsigned char v4 = *v3; // 0x1af4
    *v3 = 1;
    char * v5 = (char *)(v2 + 282); // 0x1b12
    unsigned char v6 = *v5; // 0x1b12
    *v5 = 2;
    char * v7 = (char *)(v2 + 128); // 0x1b30
    unsigned char v8 = *v7; // 0x1b30
    *v7 = 3;
    char * v9 = (char *)(v2 + 246); // 0x1b4e
    unsigned char v10 = *v9; // 0x1b4e
    *v9 = 4;
    char * v11 = (char *)(v2 + 116); // 0x1b6c
    unsigned char v12 = *v11; // 0x1b6c
    *v11 = 5;
    char * v13 = (char *)(v2 + 234); // 0x1b8a
    unsigned char v14 = *v13; // 0x1b8a
    *v13 = 6;
    char * v15 = (char *)(v2 + 101); // 0x1ba8
    unsigned char v16 = *v15; // 0x1ba8
    *v15 = 7;
    char * v17 = (char *)(v2 + 220); // 0x1bc6
    unsigned char v18 = *v17; // 0x1bc6
    *v17 = 8;
    char * v19 = (char *)(v2 + 76); // 0x1be4
    unsigned char v20 = *v19; // 0x1be4
    *v19 = 9;
    char * v21 = (char *)(v2 + 200); // 0x1c02
    unsigned char v22 = *v21; // 0x1c02
    *v21 = 10;
    char * v23 = (char *)(v2 + 308); // 0x1c20
    unsigned char v24 = *v23; // 0x1c20
    *v23 = 11;
    char * v25 = (char *)(v2 + 176); // 0x1c3e
    unsigned char v26 = *v25; // 0x1c3e
    *v25 = 12;
    char * v27 = (char *)(v2 + 293); // 0x1c5c
    unsigned char v28 = *v27; // 0x1c5c
    *v27 = 13;
    char * v29 = (char *)(v2 + 172); // 0x1c7a
    unsigned char v30 = *v29; // 0x1c7a
    *v29 = 14;
    char * v31 = (char *)(v2 + 231); // 0x1c98
    unsigned char v32 = *v31; // 0x1c98
    *v31 = 15;
    char * v33 = (char *)(v2 + 279); // 0x1cb6
    unsigned char v34 = *v33; // 0x1cb6
    *v33 = 16;
    char * v35 = (char *)(v2 + 122); // 0x1cd4
    unsigned char v36 = *v35; // 0x1cd4
    *v35 = 17;
    char * v37 = (char *)(v2 + 207); // 0x1cf2
    unsigned char v38 = *v37; // 0x1cf2
    *v37 = 18;
    char * v39 = (char *)(v2 + 278); // 0x1d10
    unsigned char v40 = *v39; // 0x1d10
    *v39 = 19;
    char * v41 = (char *)(v2 + 74); // 0x1d2e
    unsigned char v42 = *v41; // 0x1d2e
    *v41 = 20;
    char * v43 = (char *)(v2 + 135); // 0x1d4c
    unsigned char v44 = *v43; // 0x1d4c
    *v43 = 21;
    char * v45 = (char *)(v2 + 239); // 0x1d6a
    unsigned char v46 = *v45; // 0x1d6a
    *v45 = 22;
    char * v47 = (char *)(v2 + 111); // 0x1d88
    unsigned char v48 = *v47; // 0x1d88
    *v47 = 23;
    char * v49 = (char *)(v2 + 253); // 0x1da6
    unsigned char v50 = *v49; // 0x1da6
    *v49 = 24;
    char * v51 = (char *)(v2 + 123); // 0x1dc4
    unsigned char v52 = *v51; // 0x1dc4
    *v51 = 25;
    char * v53 = (char *)(v2 + 264); // 0x1de2
    unsigned char v54 = *v53; // 0x1de2
    *v53 = 26;
    char * v55 = (char *)(v2 + 151); // 0x1e00
    unsigned char v56 = *v55; // 0x1e00
    *v55 = 27;
    char * v57 = (char *)(v2 + 211); // 0x1e1e
    unsigned char v58 = *v57; // 0x1e1e
    *v57 = 28;
    char * v59 = (char *)(v2 + 307); // 0x1e3c
    unsigned char v60 = *v59; // 0x1e3c
    *v59 = 29;
    char * v61 = (char *)(v2 + 186); // 0x1e5a
    unsigned char v62 = *v61; // 0x1e5a
    *v61 = 30;
    char * v63 = (char *)(v2 + 73); // 0x1e78
    unsigned char v64 = *v63; // 0x1e78
    *v63 = 31;
    char * v65 = (char *)(v2 + 209); // 0x1e96
    unsigned char v66 = *v65; // 0x1e96
    *v65 = 32;
    char * v67 = (char *)(v2 + 87); // 0x1eb4
    unsigned char v68 = *v67; // 0x1eb4
    *v67 = 33;
    char * v69 = (char *)(v2 + 235); // 0x1ed2
    unsigned char v70 = *v69; // 0x1ed2
    *v69 = 34;
    char * v71 = (char *)(v2 + 302); // 0x1ef0
    unsigned char v72 = *v71; // 0x1ef0
    *v71 = 35;
    char * v73 = (char *)(v2 + 134); // 0x1f0e
    unsigned char v74 = *v73; // 0x1f0e
    *v73 = 36;
    char * v75 = (char *)(v2 + 215); // 0x1f2c
    unsigned char v76 = *v75; // 0x1f2c
    *v75 = 37;
    char * v77 = (char *)(v2 + 285); // 0x1f4a
    unsigned char v78 = *v77; // 0x1f4a
    *v77 = 38;
    char * v79 = (char *)(v2 + 165); // 0x1f68
    unsigned char v80 = *v79; // 0x1f68
    *v79 = 39;
    char * v81 = (char *)(v2 + 313); // 0x1f86
    unsigned char v82 = *v81; // 0x1f86
    *v81 = 40;
    char * v83 = (char *)(v2 + 213); // 0x1fa4
    unsigned char v84 = *v83; // 0x1fa4
    *v83 = 41;
    char * v85 = (char *)(v2 + 110); // 0x1fc2
    unsigned char v86 = *v85; // 0x1fc2
    *v85 = 42;
    char * v87 = (char *)(v2 + 185); // 0x1fe0
    unsigned char v88 = *v87; // 0x1fe0
    *v87 = 43;
    char * v89 = (char *)(v2 + 80); // 0x1ffe
    unsigned char v90 = *v89; // 0x1ffe
    *v89 = 44;
    unsigned char v91 = *v69; // 0x201c
    *v69 = 45;
    char * v92 = (char *)(v2 + 136); // 0x203a
    unsigned char v93 = *v92; // 0x203a
    *v92 = 46;
    unsigned char v94 = *v71; // 0x2058
    *v71 = 47;
    char * v95 = (char *)(v2 + 204); // 0x2076
    unsigned char v96 = *v95; // 0x2076
    *v95 = 48;
    unsigned char v97 = *v77; // 0x2094
    *v77 = 49;
    unsigned char v98 = *v25; // 0x20b2
    *v25 = 50;
    char * v99 = (char *)(v2 + 86); // 0x20d0
    unsigned char v100 = *v99; // 0x20d0
    *v99 = 51;
    char * v101 = (char *)(v2 + 170); // 0x20ee
    unsigned char v102 = *v101; // 0x20ee
    *v101 = 52;
    char * v103 = (char *)(v2 + 288); // 0x210c
    unsigned char v104 = *v103; // 0x210c
    *v103 = 53;
    char * v105 = (char *)(v2 + 168); // 0x212a
    unsigned char v106 = *v105; // 0x212a
    *v105 = 54;
    char * v107 = (char *)(v2 + 290); // 0x2148
    unsigned char v108 = *v107; // 0x2148
    *v107 = 55;
    char * v109 = (char *)(v2 + 142); // 0x2166
    unsigned char v110 = *v109; // 0x2166
    *v109 = 56;
    unsigned char v111 = *v31; // 0x2184
    *v31 = 57;
    char * v112 = (char *)(v2 + 144); // 0x21a2
    unsigned char v113 = *v112; // 0x21a2
    *v112 = 58;
    char * v114 = (char *)(v2 + 317); // 0x21c0
    unsigned char v115 = *v114; // 0x21c0
    *v114 = 59;
    char * v116 = (char *)(v2 + 153); // 0x21de
    unsigned char v117 = *v116; // 0x21de
    *v116 = 60;
    unsigned char v118 = *v33; // 0x21fc
    *v33 = 61;
    char * v119 = (char *)(v2 + 167); // 0x221a
    char v120 = *v119; // 0x221a
    *v119 = 62;
    char * v121 = (char *)(v2 + 297); // 0x223d
    *v121 = 63;
    *(char *)(v2 + 175) = 64;
    char * v122 = (char *)(v2 + 319); // 0x2282
    *v122 = 65;
    char * v123 = (char *)(v2 + 214); // 0x22a6
    *v123 = 66;
    char * v124 = (char *)(v2 + 107); // 0x22ca
    *(char *)(v2 + 219) = 68;
    int64_t v125 = v2 + 64; // 0x2312
    char * v126 = (char *)v125; // 0x2312
    *v126 = 69;
    *(char *)(v2 + 243) = 70;
    *(char *)(v2 + 159) = 71;
    char * v127 = (char *)(v2 + 72); // 0x237e
    *v127 = 72;
    char * v128 = (char *)(v2 + 255); // 0x23a2
    *v128 = 73;
    *v124 = 75;
    char * v129 = (char *)(v2 + 286); // 0x240e
    *v129 = 76;
    *(char *)(v2 + 139) = 77;
    *v5 = 78;
    *v83 = 79;
    char * v130 = (char *)(v2 + 145); // 0x249e
    char * v131 = (char *)(v2 + 71); // 0x24c2
    *v131 = 81;
    *(char *)(v2 + 256) = 82;
    *(char *)(v2 + 184) = 83;
    *(char *)(v2 + 112) = 84;
    *(char *)(v2 + 229) = 85;
    char * v132 = (char *)(v2 + 141); // 0x2576
    *v132 = 86;
    *(char *)(v2 + 295) = 87;
    char * v133 = (char *)(v2 + 312); // 0x25e2
    *v133 = 89;
    *(char *)(v2 + 178) = 90;
    *v7 = 91;
    *(char *)(v2 + 65) = 92;
    *(char *)(v2 + 259) = 93;
    *(char *)(v2 + 129) = 94;
    char * v134 = (char *)(v2 + 66); // 0x26ba
    *v134 = 95;
    *(char *)(v2 + 263) = 96;
    char * v135 = (char *)(v2 + 212); // 0x2702
    *v79 = 98;
    char * v136 = (char *)(v2 + 127); // 0x274a
    *v136 = 99;
    *(char *)(v2 + 268) = 100;
    *v130 = 101;
    *(char *)(v2 + 96) = 102;
    *(char *)(v2 + 314) = 103;
    char * v137 = (char *)(v2 + 194); // 0x27fe
    *v137 = 104;
    char * v138 = (char *)(v2 + 140); // 0x2822
    *v138 = 105;
    *v39 = 106;
    char * v139 = (char *)(v2 + 244); // 0x286a
    *v139 = 107;
    *v135 = 108;
    *(char *)(v2 + 179) = 109;
    *v73 = 110;
    *v99 = 111;
    *v59 = 112;
    *v116 = 114;
    *(char *)(v2 + 117) = 115;
    char * v140 = (char *)(v2 + 89); // 0x29ae
    *v140 = 116;
    char * v141 = (char *)(v2 + 310); // 0x29d2
    *v141 = 117;
    *(char *)(v2 + 273) = 118;
    char * v142 = (char *)(v2 + 266); // 0x2a86
    *v142 = 122;
    *(char *)(v2 + 237) = 123;
    *(char *)(v2 + 210) = 124;
    *(char *)(v2 + 187) = 125;
    char * v143 = (char *)(v2 + 158); // 0x2b16
    *v143 = 126;
    *(char *)(v2 + 294) = -128;
    char * v144 = (char *)(v2 + 189); // 0x2ba6
    *v144 = -126;
    *(char *)(v2 + 169) = -125;
    *(char *)(v2 + 160) = -124;
    *(char *)(v2 + 69) = -123;
    *v121 = -121;
    *v129 = -120;
    *v53 = -119;
    *(char *)(v2 + 260) = -118;
    *(char *)(v2 + 250) = -117;
    *v123 = -115;
    *(char *)(v2 + 208) = -114;
    *(char *)(v2 + 196) = -113;
    *v11 = -112;
    char * v145 = (char *)(v2 + 108); // 0x2de6
    *(char *)(v2 + 113) = -109;
    *(char *)(v2 + 291) = -107;
    char * v146 = (char *)(v2 + 301); // 0x2e76
    *(char *)(v2 + 311) = -105;
    *(char *)(v2 + 251) = -103;
    *(char *)(v2 + 254) = -102;
    *(char *)(v2 + 274) = -100;
    *(char *)(v2 + 283) = -99;
    *v107 = -98;
    *v146 = -96;
    *(char *)(v2 + 93) = -94;
    *v103 = -93;
    *v27 = -92;
    *v133 = -91;
    *v134 = -90;
    *(char *)(v2 + 265) = -89;
    *(char *)(v2 + 92) = -85;
    *v145 = -84;
    *v81 = -83;
    *v89 = -82;
    *(char *)(v2 + 109) = -81;
    *v114 = -80;
    *(char *)(v2 + 97) = -79;
    *(char *)(v2 + 130) = -78;
    *(char *)(v2 + 155) = -77;
    *(char *)(v2 + 195) = -76;
    *v45 = -75;
    *(char *)(v2 + 262) = -74;
    *(char *)(v2 + 303) = -73;
    *v19 = -72;
    *(char *)(v2 + 305) = -71;
    *(char *)(v2 + 267) = -70;
    *v59 = -69;
    *(char *)(v2 + 100) = -68;
    *v132 = -67;
    *(char *)(v2 + 191) = -66;
    *v31 = -65;
    *v33 = -64;
    *(char *)(v2 + 68) = -63;
    *(char *)(v2 + 78) = -61;
    *v92 = -60;
    *v137 = -59;
    *v139 = -58;
    *v99 = -56;
    *v130 = -55;
    *(char *)(v2 + 188) = -54;
    *(char *)(v2 + 233) = -53;
    *v109 = -50;
    *v65 = -49;
    *v142 = -48;
    *v126 = -47;
    *(char *)(v2 + 133) = -46;
    *(char *)(v2 + 120) = -45;
    *(char *)(v2 + 180) = -44;
    *v13 = -43;
    *(char *)(v2 + 114) = -41;
    *(char *)(v2 + 106) = -40;
    *v79 = -39;
    *(char *)(v2 + 292) = -37;
    *v85 = -36;
    *v124 = -35;
    *(char *)(v2 + 173) = -34;
    *(char *)(v2 + 245) = -33;
    *v127 = -32;
    *v138 = -31;
    *(char *)(v2 + 221) = -30;
    *v141 = -29;
    *v136 = -28;
    *v123 = -27;
    *(char *)(v2 + 289) = -26;
    *v145 = -25;
    *v11 = -24;
    *(char *)(v2 + 198) = -23;
    *v121 = -21;
    *(char *)(v2 + 103) = -20;
    *v55 = -19;
    *v87 = -18;
    *v135 = -17;
    *(char *)(v2 + 228) = -16;
    *v131 = -15;
    *v143 = -14;
    *v128 = -13;
    *v67 = -12;
    *(char *)(v2 + 281) = -10;
    *(char *)(v2 + 121) = -9;
    *(char *)(v2 + 223) = -8;
    *v122 = -7;
    *v140 = -6;
    *v144 = -5;
    *v146 = -4;
    *v41 = -3;
    *(char *)(v2 + 177) = -2;
    *v129 = -1;
    int64_t v147 = v4; // 0x3d4a
    *(char *)(v125 + v147) = v4;
    uint64_t v148 = (int64_t)v6 + v147; // 0x3d75
    *(char *)(v148 % 256 + v125) = v6;
    uint64_t v149 = v148 + (int64_t)v8; // 0x3da3
    *(char *)(v149 % 256 + v125) = v8;
    uint64_t v150 = v149 + (int64_t)v10; // 0x3dd1
    *(char *)(v150 % 256 + v125) = v10;
    uint64_t v151 = v150 + (int64_t)v12; // 0x3dff
    *(char *)(v151 % 256 + v125) = v12;
    uint64_t v152 = v151 + (int64_t)v14; // 0x3e2d
    *(char *)(v152 % 256 + v125) = v14;
    uint64_t v153 = v152 + (int64_t)v16; // 0x3e5b
    *(char *)(v153 % 256 + v125) = v16;
    uint64_t v154 = v153 + (int64_t)v18; // 0x3e89
    *(char *)(v154 % 256 + v125) = v18;
    uint64_t v155 = v154 + (int64_t)v20; // 0x3eb7
    *(char *)(v155 % 256 + v125) = v20;
    uint64_t v156 = v155 + (int64_t)v22; // 0x3ee5
    *(char *)(v156 % 256 + v125) = v22;
    uint64_t v157 = v156 + (int64_t)v24; // 0x3f13
    *(char *)(v157 % 256 + v125) = v24;
    uint64_t v158 = v157 + (int64_t)v26; // 0x3f41
    *(char *)(v158 % 256 + v125) = v26;
    uint64_t v159 = v158 + (int64_t)v28; // 0x3f6f
    *(char *)(v159 % 256 + v125) = v28;
    uint64_t v160 = v159 + (int64_t)v30; // 0x3f9d
    *(char *)(v160 % 256 + v125) = v30;
    uint64_t v161 = v160 + (int64_t)v32; // 0x3fcb
    *(char *)(v161 % 256 + v125) = v32;
    uint64_t v162 = v161 + (int64_t)v34; // 0x3ff9
    *(char *)(v162 % 256 + v125) = v34;
    uint64_t v163 = v162 + (int64_t)v36; // 0x4027
    *(char *)(v163 % 256 + v125) = v36;
    uint64_t v164 = v163 + (int64_t)v38; // 0x4055
    *(char *)(v164 % 256 + v125) = v38;
    uint64_t v165 = v164 + (int64_t)v40; // 0x4083
    *(char *)(v165 % 256 + v125) = v40;
    uint64_t v166 = v165 + (int64_t)v42; // 0x40b1
    *(char *)(v166 % 256 + v125) = v42;
    uint64_t v167 = v166 + (int64_t)v44; // 0x40df
    *(char *)(v167 % 256 + v125) = v44;
    uint64_t v168 = v167 + (int64_t)v46; // 0x410d
    *(char *)(v168 % 256 + v125) = v46;
    uint64_t v169 = v168 + (int64_t)v48; // 0x413b
    *(char *)(v169 % 256 + v125) = v48;
    uint64_t v170 = v169 + (int64_t)v50; // 0x4169
    *(char *)(v170 % 256 + v125) = v50;
    uint64_t v171 = v170 + (int64_t)v52; // 0x4197
    *(char *)(v171 % 256 + v125) = v52;
    uint64_t v172 = v171 + (int64_t)v54; // 0x41c5
    *(char *)(v172 % 256 + v125) = v54;
    uint64_t v173 = v172 + (int64_t)v56; // 0x41f3
    *(char *)(v173 % 256 + v125) = v56;
    uint64_t v174 = v173 + (int64_t)v58; // 0x4221
    *(char *)(v174 % 256 + v125) = v58;
    uint64_t v175 = v174 + (int64_t)v60; // 0x424f
    *(char *)(v175 % 256 + v125) = v60;
    uint64_t v176 = v175 + (int64_t)v62; // 0x427d
    *(char *)(v176 % 256 + v125) = v62;
    uint64_t v177 = v176 + (int64_t)v64; // 0x42ab
    *(char *)(v177 % 256 + v125) = v64;
    uint64_t v178 = v177 + (int64_t)v66; // 0x42d9
    *(char *)(v178 % 256 + v125) = v66;
    uint64_t v179 = v178 + (int64_t)v68; // 0x4307
    *(char *)(v179 % 256 + v125) = v68;
    uint64_t v180 = v179 + (int64_t)v70; // 0x4335
    *(char *)(v180 % 256 + v125) = v70;
    uint64_t v181 = v180 + (int64_t)v72; // 0x4363
    *(char *)(v181 % 256 + v125) = v72;
    uint64_t v182 = v181 + (int64_t)v74; // 0x4391
    *(char *)(v182 % 256 + v125) = v74;
    uint64_t v183 = v182 + (int64_t)v76; // 0x43bf
    *(char *)(v183 % 256 + v125) = v76;
    uint64_t v184 = v183 + (int64_t)v78; // 0x43ed
    *(char *)(v184 % 256 + v125) = v78;
    uint64_t v185 = v184 + (int64_t)v80; // 0x441b
    *(char *)(v185 % 256 + v125) = v80;
    uint64_t v186 = v185 + (int64_t)v82; // 0x4449
    *(char *)(v186 % 256 + v125) = v82;
    uint64_t v187 = v186 + (int64_t)v84; // 0x4477
    *(char *)(v187 % 256 + v125) = v84;
    uint64_t v188 = v187 + (int64_t)v86; // 0x44a5
    *(char *)(v188 % 256 + v125) = v86;
    uint64_t v189 = v188 + (int64_t)v88; // 0x44d3
    *(char *)(v189 % 256 + v125) = v88;
    uint64_t v190 = v189 + (int64_t)v90; // 0x4501
    *(char *)(v190 % 256 + v125) = v90;
    uint64_t v191 = v190 + (int64_t)v91; // 0x452f
    *(char *)(v191 % 256 + v125) = v91;
    uint64_t v192 = v191 + (int64_t)v93; // 0x455d
    *(char *)(v192 % 256 + v125) = v93;
    uint64_t v193 = v192 + (int64_t)v94; // 0x458b
    *(char *)(v193 % 256 + v125) = v94;
    uint64_t v194 = v193 + (int64_t)v96; // 0x45b9
    *(char *)(v194 % 256 + v125) = v96;
    uint64_t v195 = v194 + (int64_t)v97; // 0x45e7
    *(char *)(v195 % 256 + v125) = v97;
    uint64_t v196 = v195 + (int64_t)v98; // 0x4615
    *(char *)(v196 % 256 + v125) = v98;
    uint64_t v197 = v196 + (int64_t)v100; // 0x4643
    *(char *)(v197 % 256 + v125) = v100;
    uint64_t v198 = v197 + (int64_t)v102; // 0x4671
    *(char *)(v198 % 256 + v125) = v102;
    uint64_t v199 = v198 + (int64_t)v104; // 0x469f
    *(char *)(v199 % 256 + v125) = v104;
    uint64_t v200 = v199 + (int64_t)v106; // 0x46cd
    *(char *)(v200 % 256 + v125) = v106;
    uint64_t v201 = v200 + (int64_t)v108; // 0x46fb
    *(char *)(v201 % 256 + v125) = v108;
    uint64_t v202 = v201 + (int64_t)v110; // 0x4729
    *(char *)(v202 % 256 + v125) = v110;
    uint64_t v203 = v202 + (int64_t)v111; // 0x4757
    *(char *)(v203 % 256 + v125) = v111;
    uint64_t v204 = v203 + (int64_t)v113; // 0x4785
    *(char *)(v204 % 256 + v125) = v113;
    uint64_t v205 = v204 + (int64_t)v115; // 0x47b3
    *(char *)(v205 % 256 + v125) = v115;
    uint64_t v206 = v205 + (int64_t)v117; // 0x47e1
    *(char *)(v206 % 256 + v125) = v117;
    uint64_t v207 = v206 + (int64_t)v118; // 0x480f
    *(char *)(v207 % 256 + v125) = v118;
    *(char *)(v125 + (int64_t)(v120 + (char)v207)) = v120;
    v1 = 32;
    return printf("Decrypted message: %s\n", &v1);
}

// Address range: 0x488a - 0x48ac
int main(int argc, char ** argv) {
    // 0x488a
    multiplication_table(17);
    decrypt_message();
    return 0;
}

// Address range: 0x48ac - 0x48b5
int64_t _fini(void) {
    // 0x48ac
    int64_t result; // 0x48ac
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (12.2.0)
// Detected functions: 12

