//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int32_t __do_global_dtors_aux(void);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
int32_t count_sheep(void);
int32_t deregister_tm_clones(void);
int32_t frame_dummy(void);
int32_t function_1030(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1040(char * format, ...);
int32_t function_1050(char * s);
int32_t function_1060(void);
int32_t function_10c8(int32_t a1);
int32_t register_tm_clones(void);
int32_t short_multiplication_table(int32_t a1);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1020
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x2fdf);
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1030
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * format, ...) {
    // 0x1040
    return printf(format);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(char * s) {
    // 0x1050
    return puts(s);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(void) {
    // 0x1060
    int32_t result; // 0x1060
    return result;
}

// Address range: 0x1070 - 0x109a
int main(int argc, char ** argv) {
    // 0x1070
    short_multiplication_table(19);
    count_sheep();
    return 0;
}

// Address range: 0x10a0 - 0x10c8
int32_t _start(int32_t a1) {
    // 0x10a0
    int32_t v1; // 0x10a0
    function_10c8(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x2f3c); // 0x10bc
    int32_t v3; // 0x10a0
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g1);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x10c8 - 0x10cc
int32_t function_10c8(int32_t a1) {
    // 0x10c8
    int32_t result; // 0x10c8
    return result;
}

// Address range: 0x10d0 - 0x10d4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10d0
    int32_t result; // 0x10d0
    return result;
}

// Address range: 0x10e0 - 0x1119
int32_t deregister_tm_clones(void) {
    // 0x10e0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x10e0
    return v1 + 0x2f2f;
}

// Address range: 0x1120 - 0x1167
int32_t register_tm_clones(void) {
    // 0x1120
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x1170 - 0x11bb
int32_t __do_global_dtors_aux(void) {
    // 0x1170
    int32_t v1; // 0x1170
    int32_t result = __x86_get_pc_thunk_bx(v1); // 0x1178
    char * v2 = (char *)(v1 + 0x2e97); // 0x1186
    if (*v2 != 0) {
        // 0x11b6
        return result;
    }
    // 0x118f
    if (*(int32_t *)(v1 + 0x2e67) != 0) {
        // 0x1199
        function_1060();
    }
    int32_t result2 = deregister_tm_clones(); // 0x11aa
    *v2 = 1;
    // 0x11b6
    return result2;
}

// Address range: 0x11c0 - 0x11c9
int32_t frame_dummy(void) {
    // 0x11c0
    return register_tm_clones();
}

// Address range: 0x11c9 - 0x11cd
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x11c9
    int32_t result; // 0x11c9
    return result;
}

// Address range: 0x11d0 - 0x15ee
int32_t count_sheep(void) {
    // 0x11d0
    int32_t v1; // 0x11d0
    __x86_get_pc_thunk_bx(v1);
    char * format = (char *)(v1 + 3633); // 0x11e8
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf((char *)(v1 + 3637));
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    return puts((char *)(v1 + 3645));
}

// Address range: 0x15f0 - 0x176f
int32_t short_multiplication_table(int32_t a1) {
    // 0x15f0
    int32_t v1; // 0x15f0
    __x86_get_pc_thunk_bx(v1);
    char * format = (char *)(v1 + 2597); // 0x1614
    printf(format);
    printf(format);
    printf(format);
    char * format2 = (char *)(v1 + 2615); // 0x164e
    printf(format2);
    printf(format);
    printf(format);
    printf(format);
    printf(format2);
    printf(format);
    printf(format);
    printf(format);
    printf(format2);
    printf(format);
    printf(format);
    printf(format);
    printf(format2);
    printf(format);
    printf(format);
    printf(format);
    return printf(format2);
}

// Address range: 0x1770 - 0x1784
int32_t _fini(void) {
    // 0x1770
    int32_t v1; // 0x1770
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (12.2.0)
// Detected functions: 17

