// Generated by Rec Studio 4 - build Sep 23 2015

_init()
{// addr = 0x00001000
    __rax = __imp____gmon_start__;
    if(__rax != 0) {
         *__rax();
        return;
    }
}

puts()
{// addr = 0x00001030
    goto __imp__puts;
}

printf()
{// addr = 0x00001040
    goto __imp__printf;
}

__cxa_finalize()
{// addr = 0x00001050
    goto __imp____cxa_finalize;
}

_start(
    _unknown_ __rax,                       // r53
    _unknown_ __rcx,                       // r55
    _unknown_ __rdx                        // r56
)
{// addr = 0x00001060
    _pop(__rsi);
    __r9 = __r9 & -16;
    _push(__rax);
    _push(__r9);
    __imp____libc_start_main();
    asm("hlt");
    asm("o16 nop [cs:rax+rax]");
    if( &completed.0 !=  &completed.0 && __imp___ITM_deregisterTMCloneTable != 0) {
        goto __rax;
    }
}

deregister_tm_clones()
{// addr = 0x00001090
    if( &completed.0 ==  &completed.0 || __imp___ITM_deregisterTMCloneTable == 0) {
        return;
    } else {
        goto __rax;
    }
}

register_tm_clones()
{// addr = 0x000010C0
    if( &completed.0 == 0 || __imp___ITM_registerTMCloneTable == 0) {
        return;
    } else {
        goto __rax;
    }
}

__do_global_dtors_aux(
    _unknown_ __rax                        // r53
)
{// addr = 0x00001100
    _unknown_ _t3;                         // _t3

    __rax = __rax;
    asm("invalid");
    if(completed.0 != 0) {
        return;
    } else {
        _push(_t3);
        if(__imp____cxa_finalize != 0) {
            __cxa_finalize();
        }
        deregister_tm_clones();
        completed.0 = 1;
        _pop(__r8);
        return;
    }
}

frame_dummy()
{// addr = 0x00001140
    asm("invalid");
    if( &completed.0 != 0 && __imp___ITM_registerTMCloneTable != 0) {
        goto __rax;
    }
}

count_sheep(
    _unknown_ __rax,                       // r53
    _unknown_ __rsi                        // r58
)
{// addr = 0x00001149
    __rsi = __rsi;
    __rax = __rax;
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    puts();
}

short_multiplication_table(
    _unknown_ __rax,                       // r53
    _unknown_ __rcx,                       // r55
    _unknown_ __rdx,                       // r56
    _unknown_ __rdi,                       // r57
    _unknown_ __rsi,                       // r58
    _unknown_ __r12,                       // r63
    _unknown_ __r13                        // r64
)
{// addr = 0x00001878
    _unknown_ __rbx;                       // r54
    _unknown_ __r14;                       // r65
    _unknown_ __r15;                       // r66
    _unknown_ __rsp;                       // r68

    __rsi = __rsi;
    __rdx = __rdx;
    __rcx = __rcx;
    __rax = __rax;
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
}

main(
    _unknown_ __rax,                       // r53
    _unknown_ __rdi                        // r57
)
{// addr = 0x00001AAC
    __rax = __rax;
    short_multiplication_table(__rax, __rcx, __rdx, 19, __rsi, __r12, __r13);
    count_sheep(__rax, __rsi);
}

_fini(
    _unknown_ __rax                        // r53
)
{// addr = 0x00001AD0
    __rax = __rax;
}

_fini(
    _unknown_ __rax                        // r53
)
{// addr = 0x00001AD0
    __rax = __rax;
}

// Statistics:
//      39 Register nodes
//       1 Temporaries nodes
//       0 Casts
//     152 Statements
//       0 Labels
//       0 Gotos
//      13 Blocks
//     396 Nodes
//       4 Assembly nodes
//      21 Unknown Types


Total time: 0 seconds.
