// tmpg5ppo5nz_text.c
// Generated by decompiling tmpg5ppo5nz
// using Reko decompiler version 0.11.6.0.

#include "tmpg5ppo5nz.h"

// 00001070: void _start()
void _start()
{
	ptr32 fp;
	__align_stack<word32>(fp + 4);
	__libc_start_main(&g_t3FF4);
	__halt();
}

// 000010A0: void __x86.get_pc_thunk.bx()
void __x86.get_pc_thunk.bx()
{
}

// 000010B0: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
	if (&g_b4014 == &g_b4014)
		return;
	<anonymous> * eax_11 = g_ptr3FE0;
	if (eax_11 == null)
		return;
	eax_11();
}

// 000010F0: void register_tm_clones()
// Called from:
//      frame_dummy
void register_tm_clones()
{
	Eq_44 eax_16 = &g_b4014 - &g_b4014;
	Eq_50 eax_20 = (eax_16 >> 0x1F) + (eax_16 >> 0x02);
	if (eax_20 >> 0x01 != 0x00)
	{
		<anonymous> * edx_25 = g_ptr3FF0;
		if (edx_25 != null)
			edx_25();
	}
}

// 00001140: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	if (g_b4014 == 0x00)
	{
		if (__cxa_finalize_GOT != 0x00)
			fn00001060(&g_t3FF4);
		deregister_tm_clones();
		g_b4014 = 0x01;
	}
}

// 00001190: void frame_dummy()
void frame_dummy()
{
	register_tm_clones();
}

// 00001199: void __x86.get_pc_thunk.dx()
void __x86.get_pc_thunk.dx()
{
}

// 0000119D: void it_crowd()
// Called from:
//      main
void it_crowd()
{
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
	puts(&g_t3FF4);
}

// 000012B9: void some_calculation()
void some_calculation()
{
}

// 000012FC: void main()
void main()
{
	ptr32 fp;
	__align_stack<word32>(fp);
	it_crowd();
	printf(&g_t3FF4);
}

// tmpg5ppo5nz_rodata.c
// Generated by decompiling tmpg5ppo5nz
// using Reko decompiler version 0.11.6.0.

#include "tmpg5ppo5nz.h"

word32 _fp_hw = 0x03; // 00002000
word32 _IO_stdin_used = 0x00020001; // 00002004
// tmpg5ppo5nz_comment.c
// Generated by decompiling tmpg5ppo5nz
// using Reko decompiler version 0.11.6.0.

#include "tmpg5ppo5nz.h"

<anonymous> g_t0000 = <code>; // 00000000
// tmpg5ppo5nz_bss.c
// Generated by decompiling tmpg5ppo5nz
// using Reko decompiler version 0.11.6.0.

#include "tmpg5ppo5nz.h"

byte g_b4014 = 0x00; // 00004014
// tmpg5ppo5nz_init.c
// Generated by decompiling tmpg5ppo5nz
// using Reko decompiler version 0.11.6.0.

#include "tmpg5ppo5nz.h"

// 00001000: void _init()
void _init()
{
	<anonymous> * eax_10 = g_ptr3FE8;
	if (eax_10 != null)
		eax_10();
}

// tmpg5ppo5nz_got.c
// Generated by decompiling tmpg5ppo5nz
// using Reko decompiler version 0.11.6.0.

#include "tmpg5ppo5nz.h"

<anonymous> * g_ptr3FE0 = null; // 00003FE0
<anonymous> * __cxa_finalize_GOT = null; // 00003FE4
<anonymous> * g_ptr3FE8 = null; // 00003FE8
<anonymous> * g_ptr3FF0 = null; // 00003FF0
// tmpg5ppo5nz_fini.c
// Generated by decompiling tmpg5ppo5nz
// using Reko decompiler version 0.11.6.0.

#include "tmpg5ppo5nz.h"

// 00001344: void _fini()
void _fini()
{
}

// tmpg5ppo5nz_got_plt.c
// Generated by decompiling tmpg5ppo5nz
// using Reko decompiler version 0.11.6.0.

#include "tmpg5ppo5nz.h"

struct Eq_7 g_t3FF4 = // 00003FF4
	{
		null,
		&g_t1036,
		&g_t1046,
		&g_t1056,
	};
<anonymous> * __libc_start_main_GOT = &g_t1036; // 00004000
<anonymous> * printf_GOT = &g_t1046; // 00004004
<anonymous> * puts_GOT = &g_t1056; // 00004008
// tmpg5ppo5nz_plt.c
// Generated by decompiling tmpg5ppo5nz
// using Reko decompiler version 0.11.6.0.

#include "tmpg5ppo5nz.h"

// 00001030: void __libc_start_main(Register (ptr32 Eq_7) ebx)
// Called from:
//      _start
void __libc_start_main(struct Eq_7 * ebx)
{
	ebx->ptr000C();
}

<anonymous> g_t1036 = <code>; // 00001036
// 00001040: void printf(Register (ptr32 Eq_7) ebx)
// Called from:
//      main
void printf(struct Eq_7 * ebx)
{
	ebx->ptr0010();
}

<anonymous> g_t1046 = <code>; // 00001046
// 00001050: void puts(Register (ptr32 Eq_7) ebx)
// Called from:
//      it_crowd
void puts(struct Eq_7 * ebx)
{
	ebx->ptr0014();
}

<anonymous> g_t1056 = <code>; // 00001056
// tmpg5ppo5nz_plt_got.c
// Generated by decompiling tmpg5ppo5nz
// using Reko decompiler version 0.11.6.0.

#include "tmpg5ppo5nz.h"

// 00001060: void fn00001060(Register (ptr32 Eq_7) ebx)
// Called from:
//      __do_global_dtors_aux
void fn00001060(struct Eq_7 * ebx)
{
	ebx->ptrFFFFFFF0();
}

