// tmpbkuv8w99_TEXT_text_startup.c
// Generated by decompiling tmpbkuv8w99
// using Reko decompiler version 0.11.6.0.

#include "tmpbkuv8w99.h"

// 0000000100003E40: void main()
void main()
{
	it_crowd();
	printf();
}

// tmpbkuv8w99_TEXT_text.c
// Generated by decompiling tmpbkuv8w99
// using Reko decompiler version 0.11.6.0.

#include "tmpbkuv8w99.h"

// 0000000100003CE8: void it_crowd()
// Called from:
//      main
void it_crowd()
{
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
	puts();
}

// 0000000100003E04: void some_calculation()
void some_calculation()
{
}

// tmpbkuv8w99_TEXT_stubs.c
// Generated by decompiling tmpbkuv8w99
// using Reko decompiler version 0.11.6.0.

#include "tmpbkuv8w99.h"

// 0000000100003E78: void printf()
// Called from:
//      main
void printf()
{
	__imp__printf();
}

// 0000000100003E84: void puts()
// Called from:
//      it_crowd
void puts()
{
	__imp__puts();
}

// tmpbkuv8w99.globals.c
// Generated by decompiling tmpbkuv8w99
// using Reko decompiler version 0.11.6.0.

#include "tmpbkuv8w99.h"

<anonymous> * __imp__dyld_stub_binder; // 0000000000004000
<anonymous> * __imp__printf; // 0000000000008000
<anonymous> * __imp__puts; // 0000000000008008
