//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t count_sheep(void);
int64_t deregister_tm_clones(void);
int64_t frame_dummy(void);
int32_t function_1030(char * s);
int32_t function_1040(char * format, ...);
void function_1050(int64_t * d);
int64_t register_tm_clones(void);
int64_t short_multiplication_table(int64_t a1);

// --------------------- Global Variables ---------------------

char * g1 = "%2d \xc3\x97 %3d = %4d\t"; // 0x201a
char * g2 = "%2d \xc3\x97 %3d = %4d\n"; // 0x202c
int64_t g3 = 0; // 0x3fe0
int64_t g4 = 0; // 0x4020
int32_t g5;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1017
int64_t _init(void) {
    int64_t result = 0; // 0x100e
    if (*(int64_t *)0x3fd0 != 0) {
        // 0x1010
        __gmon_start__();
        result = &g5;
    }
    // 0x1012
    return result;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(char * s) {
    // 0x1030
    return puts(s);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * format, ...) {
    // 0x1040
    return printf(format);
}

// Address range: 0x1050 - 0x1056
void function_1050(int64_t * d) {
    // 0x1050
    __cxa_finalize(d);
}

// Address range: 0x1060 - 0x1082
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1060
    int64_t v1; // 0x1060
    __libc_start_main(0x1aac, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1090 - 0x10b9
int64_t deregister_tm_clones(void) {
    // 0x1090
    return &g4;
}

// Address range: 0x10c0 - 0x10f9
int64_t register_tm_clones(void) {
    // 0x10c0
    return 0;
}

// Address range: 0x1100 - 0x1139
int64_t __do_global_dtors_aux(void) {
    // 0x1100
    if (*(char *)&g4 != 0) {
        // 0x1138
        int64_t result; // 0x1100
        return result;
    }
    // 0x110d
    if (g3 != 0) {
        // 0x111b
        __cxa_finalize((int64_t *)*(int64_t *)0x4018);
    }
    int64_t result2 = deregister_tm_clones(); // 0x1127
    *(char *)&g4 = 1;
    return result2;
}

// Address range: 0x1140 - 0x1149
int64_t frame_dummy(void) {
    // 0x1140
    return register_tm_clones();
}

// Address range: 0x1149 - 0x1878
int64_t count_sheep(void) {
    // 0x1149
    printf("%d ", 0);
    printf("%d ", 1);
    printf("%d ", 2);
    printf("%d ", 3);
    printf("%d ", 4);
    printf("%d ", 5);
    printf("%d ", 6);
    printf("%d ", 7);
    printf("%d ", 8);
    printf("%d ", 9);
    printf("%d ", 10);
    printf("%d ", 11);
    printf("%d ", 12);
    printf("%d ", 13);
    printf("%d ", 14);
    printf("%d ", 15);
    printf("%d ", 16);
    printf("%d ", 17);
    printf("%d ", 18);
    printf("%d ", 19);
    printf("%d ", 20);
    printf("%d ", 21);
    printf("%d ", 22);
    printf("%d ", 23);
    printf("%d ", 24);
    printf("%d ", 25);
    printf("%d ", 26);
    printf("%d ", 27);
    printf("%d ", 28);
    printf("%d ", 29);
    printf("%d ", 30);
    printf("%d ", 31);
    printf("%d ", 32);
    printf("%d ", 33);
    printf("%d ", 34);
    printf("%d ", 35);
    printf("%d ", 36);
    printf("%d ", 37);
    printf("%d ", 38);
    printf("%d ", 39);
    printf("%d ", 40);
    printf("%d ", 41);
    printf("%d ", 42);
    printf("%d ", 43);
    printf("%d ", 44);
    printf("%d ", 45);
    printf("%d ", 46);
    printf("%d ", 47);
    printf("%d ", 48);
    printf("%d ", 49);
    printf("%d ", 50);
    printf("%d ", 51);
    printf("%d ", 52);
    printf("%d ", 53);
    printf("%d ", 54);
    printf("%d ", 55);
    printf("%d ", 56);
    printf("%d ", 57);
    printf("%d ", 58);
    printf("%d ", 59);
    printf("%d ", 60);
    printf("%d ", 61);
    printf("%d ", 62);
    printf("%d ", 63);
    printf("%d ", 64);
    printf("%d ", 65);
    printf("%d ", 66);
    printf("%d ", 67);
    printf("%d ", 68);
    printf("%d ", 69);
    printf("(nice) ");
    printf("%d ", 70);
    printf("%d ", 71);
    printf("%d ", 72);
    printf("%d ", 73);
    printf("%d ", 74);
    printf("%d ", 75);
    printf("%d ", 76);
    printf("%d ", 77);
    printf("%d ", 78);
    printf("%d ", 79);
    printf("%d ", 80);
    printf("%d ", 81);
    printf("%d ", 82);
    printf("%d ", 83);
    printf("%d ", 84);
    printf("%d ", 85);
    printf("%d ", 86);
    printf("%d ", 87);
    printf("%d ", 88);
    printf("%d ", 89);
    printf("%d ", 90);
    printf("%d ", 91);
    printf("%d ", 92);
    printf("%d ", 93);
    printf("%d ", 94);
    printf("%d ", 95);
    printf("%d ", 96);
    printf("%d ", 97);
    printf("%d ", 98);
    printf("%d ", 99);
    return puts("ZzZzZz...");
}

// Address range: 0x1878 - 0x1aac
int64_t short_multiplication_table(int64_t a1) {
    // 0x1878
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g2);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g2);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g2);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g2);
    printf((char *)&g1);
    printf((char *)&g1);
    printf((char *)&g1);
    return printf((char *)&g2);
}

// Address range: 0x1aac - 0x1ace
int main(int argc, char ** argv) {
    // 0x1aac
    short_multiplication_table(19);
    count_sheep();
    return 0;
}

// Address range: 0x1ad0 - 0x1ad9
int64_t _fini(void) {
    // 0x1ad0
    int64_t result; // 0x1ad0
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (12.2.0)
// Detected functions: 13

