//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t all_badges(void);
int32_t function_1035c(void);
int32_t function_10368(void);
int32_t polynome_table(void);
int32_t red_herring(void);

// ------------------------ Functions -------------------------

// Address range: 0x1035c - 0x10368
int32_t function_1035c(void) {
    // 0x1035c
    int32_t result; // 0x1035c
    return result;
}

// Address range: 0x10368 - 0x10374
int32_t function_10368(void) {
    // 0x10368
    int32_t result; // 0x10368
    return result;
}

// Address range: 0x10470 - 0x104e8
int32_t all_badges(void) {
    // 0x10470
    return function_1035c();
}

// Address range: 0x104e8 - 0x105a8
int32_t polynome_table(void) {
    // 0x104e8
    function_1035c();
    function_1035c();
    function_1035c();
    function_1035c();
    function_1035c();
    function_1035c();
    function_1035c();
    function_1035c();
    function_1035c();
    function_1035c();
    return function_1035c();
}

// Address range: 0x105a8 - 0x10600
int32_t red_herring(void) {
    // 0x105a8
    function_10368();
    function_1035c();
    function_1035c();
    function_1035c();
    function_1035c();
    return function_1035c();
}

// Address range: 0x10600 - 0x10618
int main(int argc, char ** argv) {
    // 0x10600
    all_badges();
    polynome_table();
    red_herring();
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.3.0)
// Detected functions: 6

