// Generated by Rec Studio 4 - build Sep 23 2015

_init()
{// addr = 0x00001000
    __rax = __imp____gmon_start__;
    if(__rax != 0) {
         *__rax();
        return;
    }
}

puts()
{// addr = 0x00001030
    goto __imp__puts;
}

printf()
{// addr = 0x00001040
    goto __imp__printf;
}

__cxa_finalize()
{// addr = 0x00001050
    goto __imp____cxa_finalize;
}

_start(
    _unknown_ __rax,                       // r53
    _unknown_ __rcx,                       // r55
    _unknown_ __rdx                        // r56
)
{// addr = 0x00001060
    _pop(__rsi);
    __r9 = __r9 & -16;
    _push(__rax);
    _push(__r9);
    __imp____libc_start_main();
    asm("hlt");
    asm("o16 nop [cs:rax+rax]");
    if(16592 != 16592 && __imp___ITM_deregisterTMCloneTable != 0) {
        goto __rax;
    }
}

deregister_tm_clones()
{// addr = 0x00001090
    if(16592 == 16592 || __imp___ITM_deregisterTMCloneTable == 0) {
        return;
    } else {
        goto __rax;
    }
}

register_tm_clones()
{// addr = 0x000010C0
    if(16592 == 0 || __imp___ITM_registerTMCloneTable == 0) {
        return;
    } else {
        goto __rax;
    }
}

__do_global_dtors_aux(
    _unknown_ __rax                        // r53
)
{// addr = 0x00001100
    _unknown_ _t3;                         // _t3

    __rax = __rax;
    asm("invalid");
    if(completed.0 != 0) {
        return;
    } else {
        _push(_t3);
        if(__imp____cxa_finalize != 0) {
            __cxa_finalize();
        }
        deregister_tm_clones();
        completed.0 = 1;
        _pop(__r8);
        return;
    }
}

frame_dummy()
{// addr = 0x00001140
    asm("invalid");
    if(16592 != 0 && __imp___ITM_registerTMCloneTable != 0) {
        goto __rax;
    }
}

all_badges(
    _unknown_ __rax,                       // r53
    _unknown_ __rcx,                       // r55
    _unknown_ __rdx,                       // r56
    _unknown_ __rsi                        // r58
)
{// addr = 0x00001149
    __rsi = __rsi;
    __rdx = __rdx;
    __rcx = __rcx;
    __rax = __rax;
    printf();
}

polynome_table(
    _unknown_ __rax,                       // r53
    _unknown_ __rdx,                       // r56
    _unknown_ __rsi                        // r58
)
{// addr = 0x000011CD
    __rsi = __rsi;
    __rdx = __rdx;
    __rax = __rax;
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
    printf();
}

red_herring(
    _unknown_ __rax,                       // r53
    _unknown_ __rsi                        // r58
)
{// addr = 0x000012D4
    __rsi = __rsi;
    __rax = __rax;
    puts();
    printf();
    printf();
    printf();
    printf();
    printf();
}

main(
    _unknown_ __rax                        // r53
)
{// addr = 0x00001344
    __rax = __rax;
    all_badges(__rax, __rcx, __rdx, __rsi);
    polynome_table(__rax, __rdx, __rsi);
    red_herring(__rax, __rsi);
}

_fini(
    _unknown_ __rax                        // r53
)
{// addr = 0x00001370
    __rax = __rax;
}

_fini(
    _unknown_ __rax                        // r53
)
{// addr = 0x00001370
    __rax = __rax;
}

// Statistics:
//      46 Register nodes
//       1 Temporaries nodes
//       0 Casts
//      52 Statements
//       0 Labels
//       0 Gotos
//      14 Blocks
//     194 Nodes
//       4 Assembly nodes
//      16 Unknown Types


Total time: 0 seconds.
