// tmpibt98ua1_text.c
// Generated by decompiling tmpibt98ua1
// using Reko decompiler version 0.11.6.0.

#include "tmpibt98ua1.h"

// 0000000000001050: void _start(Register (ptr64 Eq_8) rdx, Stack word32 dwArg00, Stack (ptr64 char) ptrArg08)
void _start(void (* rdx)(), word32 dwArg00, char * ptrArg08)
{
	__align_stack<word64>(&ptrArg08);
	word64 qwArg00;
	void * fp;
	__libc_start_main(&g_t488A, (int32) qwArg00, &ptrArg08, null, null, rdx, fp);
	__halt();
}

// 0000000000001080: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
	if (0x7188 == 0x7188 || _ITM_deregisterTMCloneTable == null)
		return;
	_ITM_deregisterTMCloneTable();
}

// 00000000000010B0: void register_tm_clones()
// Called from:
//      frame_dummy
void register_tm_clones()
{
	Eq_43 rsi_6 = 0x7188 - 0x7188;
	if ((rsi_6 >> 0x3F) + (rsi_6 >> 0x03) >> 0x01 == 0x00 || _ITM_registerTMCloneTable == null)
		return;
	_ITM_registerTMCloneTable();
}

// 00000000000010F0: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	if (g_b7187 != 0x00)
		return;
	if (__cxa_finalize != 0x00)
		__cxa_finalize(g_qw7028);
	deregister_tm_clones();
	g_b7187 = 0x01;
}

// 0000000000001130: void frame_dummy()
void frame_dummy()
{
	register_tm_clones();
}

// 0000000000001139: void multiplication_table(Register int32 edi)
// Called from:
//      main
void multiplication_table(int32 edi)
{
	printf("%2d \xC3\x97 %3d = %4d\n", 0, edi, 0);
	printf("%2d \xC3\x97 %3d = %4d\n", 1, edi, edi);
	printf("%2d \xC3\x97 %3d = %4d\n", 2, edi, edi * 0x02);
	printf("%2d \xC3\x97 %3d = %4d\n", 3, edi, edi * 0x03);
	printf("%2d \xC3\x97 %3d = %4d\n", 4, edi, edi * 0x04);
	printf("%2d \xC3\x97 %3d = %4d\n", 5, edi, edi * 0x05);
	printf("%2d \xC3\x97 %3d = %4d\n", 6, edi, edi * 0x06);
	printf("%2d \xC3\x97 %3d = %4d\n", 7, edi, edi * 0x07);
	printf("%2d \xC3\x97 %3d = %4d\n", 8, edi, edi * 0x08);
	printf("%2d \xC3\x97 %3d = %4d\n", 9, edi, edi * 0x09);
	printf("%2d \xC3\x97 %3d = %4d\n", 0x0A, edi, edi * 0x0A);
	printf("%2d \xC3\x97 %3d = %4d\n", 11, edi, edi * 11);
	uint64 r13_161 = (uint64) (edi * 0x0C);
	printf("%2d \xC3\x97 %3d = %4d\n", 0x0C, edi, (word32) r13_161);
	printf("%2d \xC3\x97 %3d = %4d\n", 0x0D, edi, (word32) r13_161 + edi);
	printf("%2d \xC3\x97 %3d = %4d\n", 0x0E, edi, edi *s 0x0E);
	uint64 r13_194 = (uint64) (edi << 0x04);
	int32 r13d_195 = (word32) r13_194;
	printf("%2d \xC3\x97 %3d = %4d\n", 0x0F, edi, r13d_195 - edi);
	printf("%2d \xC3\x97 %3d = %4d\n", 16, edi, r13d_195);
	printf("%2d \xC3\x97 %3d = %4d\n", 0x0011, edi, (word32) r13_194 + edi);
	uint64 r12_227 = (uint64) (edi * 0x12);
	printf("%2d \xC3\x97 %3d = %4d\n", 18, edi, (word32) r12_227);
	printf("%2d \xC3\x97 %3d = %4d\n", 19, edi, (word32) r12_227 + edi);
	printf("%2d \xC3\x97 %3d = %4d\n", 20, edi, edi * 0x14);
}

// 0000000000001383: void decrypt_message()
// Called from:
//      main
void decrypt_message()
{
	word32 edx_261 = (word32) g_b7080;
	Eq_303 fp;
	(fp - 0x0108)[(int64) edx_261] = 0x00;
	byte al_281 = g_b7081 + 0x01 + (byte) edx_261;
	Eq_316 rdx_283;
	rdx_283.u1 = (uint64) al_281;
	byte sil_288 = (byte) *(fp - 0x0108 + rdx_283);
	*(fp - 0x0108 + rdx_283) = (word64) 0x01;
	byte al_292 = al_281 + g_b7082;
	Eq_334 rdx_300;
	rdx_300.u0 = (uint64) (al_292 + 0x02);
	byte sil_305 = (byte) *(fp - 0x0108 + rdx_300);
	*(fp - 0x0108 + rdx_300) = (word64) 0x02;
	byte al_309 = al_292 + 0x02 + g_b7083;
	Eq_353 rdx_317;
	rdx_317.u0 = (uint64) (al_309 + 0x03);
	byte sil_322 = (byte) *(fp - 0x0108 + rdx_317);
	*(fp - 0x0108 + rdx_317) = (word64) 0x03;
	byte al_326 = al_309 + 0x03 + g_b7084;
	Eq_372 rdx_334;
	rdx_334.u0 = (uint64) (al_326 + 0x04);
	byte sil_339 = (byte) *(fp - 0x0108 + rdx_334);
	*(fp - 0x0108 + rdx_334) = (word64) 0x04;
	byte al_343 = al_326 + 0x04 + g_b7085;
	Eq_391 rdx_351;
	rdx_351.u0 = (uint64) (al_343 + 0x05);
	byte sil_356 = (byte) *(fp - 0x0108 + rdx_351);
	*(fp - 0x0108 + rdx_351) = (word64) 0x05;
	byte al_360 = al_343 + 0x05 + g_b7086;
	Eq_410 rdx_368;
	rdx_368.u0 = (uint64) (al_360 + 0x06);
	byte sil_373 = (byte) *(fp - 0x0108 + rdx_368);
	*(fp - 0x0108 + rdx_368) = (word64) 0x06;
	byte al_377 = al_360 + 0x06 + g_b7087;
	Eq_429 rdx_385;
	rdx_385.u0 = (uint64) (al_377 + 0x07);
	byte sil_390 = (byte) *(fp - 0x0108 + rdx_385);
	*(fp - 0x0108 + rdx_385) = (word64) 0x07;
	byte al_394 = al_377 + 0x07 + g_b7088;
	Eq_448 rdx_402;
	rdx_402.u0 = (uint64) (al_394 + 0x08);
	byte sil_407 = (byte) *(fp - 0x0108 + rdx_402);
	*(fp - 0x0108 + rdx_402) = (word64) 0x08;
	byte al_411 = al_394 + 0x08 + g_b7089;
	Eq_467 rdx_419;
	rdx_419.u0 = (uint64) (al_411 + 0x09);
	byte sil_424 = (byte) *(fp - 0x0108 + rdx_419);
	*(fp - 0x0108 + rdx_419) = (word64) 0x09;
	byte al_428 = al_411 + 0x09 + g_b708A;
	Eq_486 rdx_436;
	rdx_436.u0 = (uint64) (al_428 + 0x0A);
	byte sil_441 = (byte) *(fp - 0x0108 + rdx_436);
	*(fp - 0x0108 + rdx_436) = (word64) 0x0A;
	byte al_445 = al_428 + 0x0A + g_b708B;
	Eq_505 rdx_453;
	rdx_453.u0 = (uint64) (al_445 + 11);
	byte sil_458 = (byte) *(fp - 0x0108 + rdx_453);
	*(fp - 0x0108 + rdx_453) = (word64) 11;
	byte al_462 = al_445 + 11 + g_b708C;
	Eq_524 rdx_470;
	rdx_470.u0 = (uint64) (al_462 + 0x0C);
	byte sil_475 = (byte) *(fp - 0x0108 + rdx_470);
	*(fp - 0x0108 + rdx_470) = (word64) 0x0C;
	byte al_479 = al_462 + 0x0C + g_b708D;
	Eq_543 rdx_487;
	rdx_487.u0 = (uint64) (al_479 + 0x0D);
	byte sil_492 = (byte) *(fp - 0x0108 + rdx_487);
	*(fp - 0x0108 + rdx_487) = (word64) 0x0D;
	byte al_496 = al_479 + 0x0D + g_b708E;
	Eq_562 rdx_504;
	rdx_504.u0 = (uint64) (al_496 + 0x0E);
	byte sil_509 = (byte) *(fp - 0x0108 + rdx_504);
	*(fp - 0x0108 + rdx_504) = (word64) 0x0E;
	byte al_513 = al_496 + 0x0E + g_b708F;
	Eq_581 rdx_521;
	rdx_521.u0 = (uint64) (al_513 + 0x0F);
	byte sil_526 = (byte) *(fp - 0x0108 + rdx_521);
	*(fp - 0x0108 + rdx_521) = (word64) 0x0F;
	byte al_530 = al_513 + 0x0F + g_b7090;
	Eq_600 rdx_538;
	rdx_538.u0 = (uint64) (al_530 + 0x10);
	byte sil_543 = (byte) *(fp - 0x0108 + rdx_538);
	*(fp - 0x0108 + rdx_538) = (word64) 0x10;
	byte al_547 = al_530 + 0x10 + g_b7091;
	Eq_619 rdx_555;
	rdx_555.u0 = (uint64) (al_547 + 0x11);
	byte sil_560 = (byte) *(fp - 0x0108 + rdx_555);
	*(fp - 0x0108 + rdx_555) = (word64) 0x11;
	byte al_564 = al_547 + 0x11 + g_b7092;
	Eq_638 rdx_572;
	rdx_572.u0 = (uint64) (al_564 + 0x12);
	byte sil_577 = (byte) *(fp - 0x0108 + rdx_572);
	*(fp - 0x0108 + rdx_572) = (word64) 0x12;
	byte al_581 = al_564 + 0x12 + g_b7093;
	Eq_657 rdx_589;
	rdx_589.u0 = (uint64) (al_581 + 0x13);
	byte sil_594 = (byte) *(fp - 0x0108 + rdx_589);
	*(fp - 0x0108 + rdx_589) = (word64) 0x13;
	byte al_598 = al_581 + 0x13 + g_b7094;
	Eq_676 rdx_606;
	rdx_606.u0 = (uint64) (al_598 + 0x14);
	byte sil_611 = (byte) *(fp - 0x0108 + rdx_606);
	*(fp - 0x0108 + rdx_606) = (word64) 0x14;
	byte al_615 = al_598 + 0x14 + g_b7095;
	Eq_695 rdx_623;
	rdx_623.u0 = (uint64) (al_615 + 0x15);
	byte sil_628 = (byte) *(fp - 0x0108 + rdx_623);
	*(fp - 0x0108 + rdx_623) = (word64) 0x15;
	byte al_632 = al_615 + 0x15 + g_b7096;
	Eq_714 rdx_640;
	rdx_640.u0 = (uint64) (al_632 + 22);
	byte sil_645 = (byte) *(fp - 0x0108 + rdx_640);
	*(fp - 0x0108 + rdx_640) = (word64) 22;
	byte al_649 = al_632 + 22 + g_b7097;
	Eq_733 rdx_657;
	rdx_657.u0 = (uint64) (al_649 + 0x17);
	byte sil_662 = (byte) *(fp - 0x0108 + rdx_657);
	*(fp - 0x0108 + rdx_657) = (word64) 0x17;
	byte al_666 = al_649 + 0x17 + g_b7098;
	Eq_752 rdx_674;
	rdx_674.u0 = (uint64) (al_666 + 0x18);
	byte sil_679 = (byte) *(fp - 0x0108 + rdx_674);
	*(fp - 0x0108 + rdx_674) = (word64) 0x18;
	byte al_683 = al_666 + 0x18 + g_b7099;
	Eq_771 rdx_691;
	rdx_691.u0 = (uint64) (al_683 + 0x19);
	byte sil_696 = (byte) *(fp - 0x0108 + rdx_691);
	*(fp - 0x0108 + rdx_691) = (word64) 0x19;
	byte al_700 = al_683 + 0x19 + g_b709A;
	Eq_790 rdx_708;
	rdx_708.u0 = (uint64) (al_700 + 0x1A);
	byte sil_713 = (byte) *(fp - 0x0108 + rdx_708);
	*(fp - 0x0108 + rdx_708) = (word64) 0x1A;
	byte al_717 = al_700 + 0x1A + g_b709B;
	Eq_809 rdx_725;
	rdx_725.u0 = (uint64) (al_717 + 0x1B);
	byte sil_730 = (byte) *(fp - 0x0108 + rdx_725);
	*(fp - 0x0108 + rdx_725) = (word64) 0x1B;
	byte al_734 = al_717 + 0x1B + g_b709C;
	Eq_828 rdx_742;
	rdx_742.u0 = (uint64) (al_734 + 0x1C);
	byte sil_747 = (byte) *(fp - 0x0108 + rdx_742);
	*(fp - 0x0108 + rdx_742) = (word64) 0x1C;
	byte al_751 = al_734 + 0x1C + g_b709D;
	Eq_847 rdx_759;
	rdx_759.u0 = (uint64) (al_751 + 0x1D);
	byte sil_764 = (byte) *(fp - 0x0108 + rdx_759);
	*(fp - 0x0108 + rdx_759) = (word64) 0x1D;
	byte al_768 = al_751 + 0x1D + g_b709E;
	Eq_866 rdx_776;
	rdx_776.u0 = (uint64) (al_768 + 0x1E);
	byte sil_781 = (byte) *(fp - 0x0108 + rdx_776);
	*(fp - 0x0108 + rdx_776) = (word64) 0x1E;
	byte al_785 = al_768 + 0x1E + g_b709F;
	Eq_885 rdx_793;
	rdx_793.u0 = (uint64) (al_785 + 0x1F);
	byte sil_798 = (byte) *(fp - 0x0108 + rdx_793);
	*(fp - 0x0108 + rdx_793) = (word64) 0x1F;
	byte al_802 = al_785 + 0x1F + g_b70A0;
	Eq_904 rdx_810;
	rdx_810.u0 = (uint64) (al_802 + 0x20);
	byte sil_815 = (byte) *(fp - 0x0108 + rdx_810);
	*(fp - 0x0108 + rdx_810) = (word64) 0x20;
	byte al_819 = al_802 + 0x20 + g_b70A1;
	Eq_923 rdx_827;
	rdx_827.u0 = (uint64) (al_819 + 33);
	byte sil_832 = (byte) *(fp - 0x0108 + rdx_827);
	*(fp - 0x0108 + rdx_827) = (word64) 33;
	byte al_836 = al_819 + 33 + g_b70A2;
	Eq_942 rdx_844;
	rdx_844.u0 = (uint64) (al_836 + 0x22);
	byte sil_849 = (byte) *(fp - 0x0108 + rdx_844);
	*(fp - 0x0108 + rdx_844) = (word64) 0x22;
	byte al_853 = al_836 + 0x22 + g_b70A3;
	Eq_961 rdx_861;
	rdx_861.u0 = (uint64) (al_853 + 0x23);
	byte sil_866 = (byte) *(fp - 0x0108 + rdx_861);
	*(fp - 0x0108 + rdx_861) = (word64) 0x23;
	byte al_870 = al_853 + 0x23 + g_b70A4;
	Eq_980 rdx_878;
	rdx_878.u0 = (uint64) (al_870 + 0x24);
	byte sil_883 = (byte) *(fp - 0x0108 + rdx_878);
	*(fp - 0x0108 + rdx_878) = (word64) 0x24;
	byte al_887 = al_870 + 0x24 + g_b70A5;
	Eq_999 rdx_895;
	rdx_895.u0 = (uint64) (al_887 + 0x25);
	byte sil_900 = (byte) *(fp - 0x0108 + rdx_895);
	*(fp - 0x0108 + rdx_895) = (word64) 0x25;
	byte al_904 = al_887 + 0x25 + g_b70A6;
	Eq_1018 rdx_912;
	rdx_912.u0 = (uint64) (al_904 + 0x26);
	byte sil_917 = (byte) *(fp - 0x0108 + rdx_912);
	*(fp - 0x0108 + rdx_912) = (word64) 0x26;
	byte al_921 = al_904 + 0x26 + g_b70A7;
	Eq_1037 rdx_929;
	rdx_929.u0 = (uint64) (al_921 + 0x27);
	byte sil_934 = (byte) *(fp - 0x0108 + rdx_929);
	*(fp - 0x0108 + rdx_929) = (word64) 0x27;
	byte al_938 = al_921 + 0x27 + g_b70A8;
	Eq_1056 rdx_946;
	rdx_946.u0 = (uint64) (al_938 + 0x28);
	byte sil_951 = (byte) *(fp - 0x0108 + rdx_946);
	*(fp - 0x0108 + rdx_946) = (word64) 0x28;
	byte al_955 = al_938 + 0x28 + g_b70A9;
	Eq_1075 rdx_963;
	rdx_963.u0 = (uint64) (al_955 + 0x29);
	byte sil_968 = (byte) *(fp - 0x0108 + rdx_963);
	*(fp - 0x0108 + rdx_963) = (word64) 0x29;
	byte al_972 = al_955 + 0x29 + g_b70AA;
	Eq_1094 rdx_980;
	rdx_980.u0 = (uint64) (al_972 + 0x2A);
	byte sil_985 = (byte) *(fp - 0x0108 + rdx_980);
	*(fp - 0x0108 + rdx_980) = (word64) 0x2A;
	byte al_989 = al_972 + 0x2A + g_b70AB;
	Eq_1113 rdx_997;
	rdx_997.u0 = (uint64) (al_989 + 0x2B);
	byte sil_1002 = (byte) *(fp - 0x0108 + rdx_997);
	*(fp - 0x0108 + rdx_997) = (word64) 0x2B;
	byte al_1006 = al_989 + 0x2B + g_b70AC;
	Eq_1132 rdx_1014;
	rdx_1014.u0 = (uint64) (al_1006 + 44);
	byte sil_1019 = (byte) *(fp - 0x0108 + rdx_1014);
	*(fp - 0x0108 + rdx_1014) = (word64) 44;
	byte al_1023 = al_1006 + 44 + g_b70AD;
	Eq_1151 rdx_1031;
	rdx_1031.u0 = (uint64) (al_1023 + 0x2D);
	byte sil_1036 = (byte) *(fp - 0x0108 + rdx_1031);
	*(fp - 0x0108 + rdx_1031) = (word64) 0x2D;
	byte al_1040 = al_1023 + 0x2D + g_b70AE;
	Eq_1170 rdx_1048;
	rdx_1048.u0 = (uint64) (al_1040 + 0x2E);
	byte sil_1053 = (byte) *(fp - 0x0108 + rdx_1048);
	*(fp - 0x0108 + rdx_1048) = (word64) 0x2E;
	byte al_1057 = al_1040 + 0x2E + g_b70AF;
	Eq_1189 rdx_1065;
	rdx_1065.u0 = (uint64) (al_1057 + 0x2F);
	byte sil_1070 = (byte) *(fp - 0x0108 + rdx_1065);
	*(fp - 0x0108 + rdx_1065) = (word64) 0x2F;
	byte al_1074 = al_1057 + 0x2F + g_b70B0;
	Eq_1208 rdx_1082;
	rdx_1082.u0 = (uint64) (al_1074 + 0x30);
	byte sil_1087 = (byte) *(fp - 0x0108 + rdx_1082);
	*(fp - 0x0108 + rdx_1082) = (word64) 0x30;
	byte al_1091 = al_1074 + 0x30 + g_b70B1;
	Eq_1227 rdx_1099;
	rdx_1099.u0 = (uint64) (al_1091 + 0x31);
	byte sil_1104 = (byte) *(fp - 0x0108 + rdx_1099);
	*(fp - 0x0108 + rdx_1099) = (word64) 0x31;
	byte al_1108 = al_1091 + 0x31 + g_b70B2;
	Eq_1246 rdx_1116;
	rdx_1116.u0 = (uint64) (al_1108 + 0x32);
	byte sil_1121 = (byte) *(fp - 0x0108 + rdx_1116);
	*(fp - 0x0108 + rdx_1116) = (word64) 0x32;
	byte al_1125 = al_1108 + 0x32 + g_b70B3;
	Eq_1265 rdx_1133;
	rdx_1133.u0 = (uint64) (al_1125 + 0x33);
	byte sil_1138 = (byte) *(fp - 0x0108 + rdx_1133);
	*(fp - 0x0108 + rdx_1133) = (word64) 0x33;
	byte al_1142 = al_1125 + 0x33 + g_b70B4;
	Eq_1284 rdx_1150;
	rdx_1150.u0 = (uint64) (al_1142 + 0x34);
	byte sil_1155 = (byte) *(fp - 0x0108 + rdx_1150);
	*(fp - 0x0108 + rdx_1150) = (word64) 0x34;
	byte al_1159 = al_1142 + 0x34 + g_b70B5;
	Eq_1303 rdx_1167;
	rdx_1167.u0 = (uint64) (al_1159 + 0x35);
	byte sil_1172 = (byte) *(fp - 0x0108 + rdx_1167);
	*(fp - 0x0108 + rdx_1167) = (word64) 0x35;
	byte al_1176 = al_1159 + 0x35 + g_b70B6;
	Eq_1322 rdx_1184;
	rdx_1184.u0 = (uint64) (al_1176 + 0x36);
	byte sil_1189 = (byte) *(fp - 0x0108 + rdx_1184);
	*(fp - 0x0108 + rdx_1184) = (word64) 0x36;
	byte al_1193 = al_1176 + 0x36 + g_b70B7;
	Eq_1341 rdx_1201;
	rdx_1201.u0 = (uint64) (al_1193 + 55);
	byte sil_1206 = (byte) *(fp - 0x0108 + rdx_1201);
	*(fp - 0x0108 + rdx_1201) = (word64) 55;
	byte al_1210 = al_1193 + 55 + g_b70B8;
	Eq_1360 rdx_1218;
	rdx_1218.u0 = (uint64) (al_1210 + 0x38);
	byte sil_1223 = (byte) *(fp - 0x0108 + rdx_1218);
	*(fp - 0x0108 + rdx_1218) = (word64) 0x38;
	byte al_1227 = al_1210 + 0x38 + g_b70B9;
	Eq_1379 rdx_1235;
	rdx_1235.u0 = (uint64) (al_1227 + 0x39);
	byte sil_1240 = (byte) *(fp - 0x0108 + rdx_1235);
	*(fp - 0x0108 + rdx_1235) = (word64) 0x39;
	byte al_1244 = al_1227 + 0x39 + g_b70BA;
	Eq_1398 rdx_1252;
	rdx_1252.u0 = (uint64) (al_1244 + 0x3A);
	byte sil_1257 = (byte) *(fp - 0x0108 + rdx_1252);
	*(fp - 0x0108 + rdx_1252) = (word64) 0x3A;
	byte al_1261 = al_1244 + 0x3A + g_b70BB;
	Eq_1417 rdx_1269;
	rdx_1269.u0 = (uint64) (al_1261 + 0x3B);
	byte sil_1274 = (byte) *(fp - 0x0108 + rdx_1269);
	*(fp - 0x0108 + rdx_1269) = (word64) 0x3B;
	byte al_1278 = al_1261 + 0x3B + g_b70BC;
	Eq_1436 rdx_1286;
	rdx_1286.u0 = (uint64) (al_1278 + 0x3C);
	byte sil_1291 = (byte) *(fp - 0x0108 + rdx_1286);
	*(fp - 0x0108 + rdx_1286) = (word64) 0x3C;
	byte al_1295 = al_1278 + 0x3C + g_b70BD;
	Eq_1455 rdx_1303;
	rdx_1303.u0 = (uint64) (al_1295 + 0x3D);
	byte sil_1308 = (byte) *(fp - 0x0108 + rdx_1303);
	*(fp - 0x0108 + rdx_1303) = (word64) 0x3D;
	byte al_1312 = al_1295 + 0x3D + g_b70BE;
	Eq_1474 rdx_1320;
	rdx_1320.u0 = (uint64) (al_1312 + 0x3E);
	byte sil_1325 = (byte) *(fp - 0x0108 + rdx_1320);
	*(fp - 0x0108 + rdx_1320) = (word64) 0x3E;
	byte al_1329 = al_1312 + 0x3E + g_b70BF;
	(fp - 0x0108).u0[(uint64) (al_1329 + 0x3F)] = 0x3F;
	byte al_1346 = al_1329 + 0x3F + g_b70C0;
	(fp - 0x0108).u0[(uint64) (al_1346 + 0x40)] = 0x40;
	byte al_1363 = al_1346 + 0x40 + g_b70C1;
	(fp - 0x0108).u0[(uint64) (al_1363 + 0x41)] = 0x41;
	byte al_1380 = al_1363 + 0x41 + g_b70C2;
	(fp - 0x0108).u0[(uint64) (al_1380 + 66)] = 66;
	byte al_1397 = al_1380 + 66 + g_b70C3;
	(fp - 0x0108).u0[(uint64) (al_1397 + 0x43)] = 0x43;
	byte al_1414 = al_1397 + 0x43 + g_b70C4;
	(fp - 0x0108).u0[(uint64) (al_1414 + 0x44)] = 0x44;
	byte al_1431 = al_1414 + 0x44 + g_b70C5;
	(fp - 0x0108).u0[(uint64) (al_1431 + 0x45)] = 0x45;
	byte al_1448 = al_1431 + 0x45 + g_b70C6;
	(fp - 0x0108).u0[(uint64) (al_1448 + 0x46)] = 0x46;
	byte al_1465 = al_1448 + 0x46 + g_b70C7;
	(fp - 0x0108).u0[(uint64) (al_1465 + 0x47)] = 0x47;
	byte al_1482 = al_1465 + 0x47 + g_b70C8;
	(fp - 0x0108).u0[(uint64) (al_1482 + 0x48)] = 0x48;
	byte al_1499 = al_1482 + 0x48 + g_b70C9;
	(fp - 0x0108).u0[(uint64) (al_1499 + 0x49)] = 0x49;
	byte al_1516 = al_1499 + 0x49 + g_b70CA;
	(fp - 0x0108).u0[(uint64) (al_1516 + 0x4A)] = 0x4A;
	byte al_1533 = al_1516 + 0x4A + g_b70CB;
	(fp - 0x0108).u0[(uint64) (al_1533 + 0x4B)] = 0x4B;
	byte al_1550 = al_1533 + 0x4B + g_b70CC;
	(fp - 0x0108).u0[(uint64) (al_1550 + 0x4C)] = 0x4C;
	byte al_1567 = al_1550 + 0x4C + g_b70CD;
	(fp - 0x0108).u0[(uint64) (al_1567 + 77)] = 77;
	byte al_1584 = al_1567 + 77 + g_b70CE;
	(fp - 0x0108).u0[(uint64) (al_1584 + 0x4E)] = 0x4E;
	byte al_1601 = al_1584 + 0x4E + g_b70CF;
	(fp - 0x0108).u0[(uint64) (al_1601 + 0x4F)] = 0x4F;
	byte al_1618 = al_1601 + 0x4F + g_b70D0;
	(fp - 0x0108).u0[(uint64) (al_1618 + 0x50)] = 0x50;
	byte al_1635 = al_1618 + 0x50 + g_b70D1;
	(fp - 0x0108).u0[(uint64) (al_1635 + 0x51)] = 0x51;
	byte al_1652 = al_1635 + 0x51 + g_b70D2;
	(fp - 0x0108).u0[(uint64) (al_1652 + 0x52)] = 0x52;
	byte al_1669 = al_1652 + 0x52 + g_b70D3;
	(fp - 0x0108).u0[(uint64) (al_1669 + 0x53)] = 0x53;
	byte al_1686 = al_1669 + 0x53 + g_b70D4;
	(fp - 0x0108).u0[(uint64) (al_1686 + 0x54)] = 0x54;
	byte al_1703 = al_1686 + 0x54 + g_b70D5;
	(fp - 0x0108).u0[(uint64) (al_1703 + 0x55)] = 0x55;
	byte al_1720 = al_1703 + 0x55 + g_b70D6;
	(fp - 0x0108).u0[(uint64) (al_1720 + 0x56)] = 0x56;
	byte al_1737 = al_1720 + 0x56 + g_b70D7;
	(fp - 0x0108).u0[(uint64) (al_1737 + 0x57)] = 0x57;
	byte al_1754 = al_1737 + 0x57 + g_b70D8;
	(fp - 0x0108).u0[(uint64) (al_1754 + 88)] = 88;
	byte al_1771 = al_1754 + 88 + g_b70D9;
	(fp - 0x0108).u0[(uint64) (al_1771 + 0x59)] = 0x59;
	byte al_1788 = al_1771 + 0x59 + g_b70DA;
	(fp - 0x0108).u0[(uint64) (al_1788 + 0x5A)] = 0x5A;
	byte al_1805 = al_1788 + 0x5A + g_b70DB;
	(fp - 0x0108).u0[(uint64) (al_1805 + 0x5B)] = 0x5B;
	byte al_1822 = al_1805 + 0x5B + g_b70DC;
	(fp - 0x0108).u0[(uint64) (al_1822 + 0x5C)] = 0x5C;
	byte al_1839 = al_1822 + 0x5C + g_b70DD;
	(fp - 0x0108).u0[(uint64) (al_1839 + 0x5D)] = 0x5D;
	byte al_1856 = al_1839 + 0x5D + g_b70DE;
	(fp - 0x0108).u0[(uint64) (al_1856 + 0x5E)] = 0x5E;
	byte al_1873 = al_1856 + 0x5E + g_b70DF;
	(fp - 0x0108).u0[(uint64) (al_1873 + 0x5F)] = 0x5F;
	byte al_1890 = al_1873 + 0x5F + g_b70E0;
	(fp - 0x0108).u0[(uint64) (al_1890 + 0x60)] = 0x60;
	byte al_1907 = al_1890 + 0x60 + g_b70E1;
	(fp - 0x0108).u0[(uint64) (al_1907 + 0x61)] = 0x61;
	byte al_1924 = al_1907 + 0x61 + g_b70E2;
	(fp - 0x0108).u0[(uint64) (al_1924 + 0x62)] = 0x62;
	byte al_1941 = al_1924 + 0x62 + g_b70E3;
	(fp - 0x0108).u0[(uint64) (al_1941 + 99)] = 99;
	byte al_1958 = al_1941 + 99 + g_b70E4;
	(fp - 0x0108).u0[(uint64) (al_1958 + 100)] = 100;
	byte al_1975 = al_1958 + 100 + g_b70E5;
	(fp - 0x0108).u0[(uint64) (al_1975 + 101)] = 101;
	byte al_1992 = al_1975 + 101 + g_b70E6;
	(fp - 0x0108).u0[(uint64) (al_1992 + 0x66)] = 0x66;
	byte al_2009 = al_1992 + 0x66 + g_b70E7;
	(fp - 0x0108).u0[(uint64) (al_2009 + 0x67)] = 0x67;
	byte al_2026 = al_2009 + 0x67 + g_b70E8;
	(fp - 0x0108).u0[(uint64) (al_2026 + 0x68)] = 0x68;
	byte al_2043 = al_2026 + 0x68 + g_b70E9;
	(fp - 0x0108).u0[(uint64) (al_2043 + 0x69)] = 0x69;
	byte al_2060 = al_2043 + 0x69 + g_b70EA;
	(fp - 0x0108).u0[(uint64) (al_2060 + 0x6A)] = 0x6A;
	byte al_2077 = al_2060 + 0x6A + g_b70EB;
	(fp - 0x0108).u0[(uint64) (al_2077 + 0x6B)] = 0x6B;
	byte al_2094 = al_2077 + 0x6B + g_b70EC;
	(fp - 0x0108).u0[(uint64) (al_2094 + 0x6C)] = 0x6C;
	byte al_2111 = al_2094 + 0x6C + g_b70ED;
	(fp - 0x0108).u0[(uint64) (al_2111 + 0x6D)] = 0x6D;
	byte al_2128 = al_2111 + 0x6D + g_b70EE;
	(fp - 0x0108).u0[(uint64) (al_2128 + 110)] = 110;
	byte al_2145 = al_2128 + 110 + g_b70EF;
	(fp - 0x0108).u0[(uint64) (al_2145 + 111)] = 111;
	byte al_2162 = al_2145 + 111 + g_b70F0;
	(fp - 0x0108).u0[(uint64) (al_2162 + 0x70)] = 0x70;
	byte al_2179 = al_2162 + 0x70 + g_b70F1;
	(fp - 0x0108).u0[(uint64) (al_2179 + 113)] = 113;
	byte al_2196 = al_2179 + 113 + g_b70F2;
	(fp - 0x0108).u0[(uint64) (al_2196 + 114)] = 114;
	byte al_2213 = al_2196 + 114 + g_b70F3;
	(fp - 0x0108).u0[(uint64) (al_2213 + 115)] = 115;
	byte al_2230 = al_2213 + 115 + g_b70F4;
	(fp - 0x0108).u0[(uint64) (al_2230 + 116)] = 116;
	byte al_2247 = al_2230 + 116 + g_b70F5;
	(fp - 0x0108).u0[(uint64) (al_2247 + 117)] = 117;
	byte al_2264 = al_2247 + 117 + g_b70F6;
	(fp - 0x0108).u0[(uint64) (al_2264 + 118)] = 118;
	byte al_2281 = al_2264 + 118 + g_b70F7;
	(fp - 0x0108).u0[(uint64) (al_2281 + 0x77)] = 0x77;
	byte al_2298 = al_2281 + 0x77 + g_b70F8;
	(fp - 0x0108).u0[(uint64) (al_2298 + 0x78)] = 0x78;
	byte al_2315 = al_2298 + 0x78 + g_b70F9;
	(fp - 0x0108).u0[(uint64) (al_2315 + 121)] = 121;
	byte al_2332 = al_2315 + 121 + g_b70FA;
	(fp - 0x0108).u0[(uint64) (al_2332 + 122)] = 122;
	byte al_2349 = al_2332 + 122 + g_b70FB;
	(fp - 0x0108).u0[(uint64) (al_2349 + 0x7B)] = 0x7B;
	byte al_2366 = al_2349 + 0x7B + g_b70FC;
	(fp - 0x0108).u0[(uint64) (al_2366 + 0x7C)] = 0x7C;
	byte al_2383 = al_2366 + 0x7C + g_b70FD;
	(fp - 0x0108).u0[(uint64) (al_2383 + 0x7D)] = 0x7D;
	byte al_2400 = al_2383 + 0x7D + g_b70FE;
	(fp - 0x0108).u0[(uint64) (al_2400 + 0x7E)] = 0x7E;
	byte al_2417 = al_2400 + 0x7E + g_b70FF;
	(fp - 0x0108).u0[(uint64) (al_2417 + 0x7F)] = 0x7F;
	byte al_2434 = al_2417 + 0x7F + g_b7100;
	(fp - 0x0108).u0[(uint64) (al_2434 + 0x80)] = 0x80;
	byte al_2451 = al_2434 + 0x80 + g_b7101;
	(fp - 0x0108).u0[(uint64) (al_2451 + 0x81)] = 0x81;
	byte al_2468 = al_2451 + 0x81 + g_b7102;
	(fp - 0x0108).u0[(uint64) (al_2468 + 0x82)] = 0x82;
	byte al_2485 = al_2468 + 0x82 + g_b7103;
	(fp - 0x0108).u0[(uint64) (al_2485 + 131)] = 131;
	byte al_2502 = al_2485 + 131 + g_b7104;
	(fp - 0x0108).u0[(uint64) (al_2502 + 0x84)] = 0x84;
	byte al_2519 = al_2502 + 0x84 + g_b7105;
	(fp - 0x0108).u0[(uint64) (al_2519 + 133)] = 133;
	byte al_2536 = al_2519 + 133 + g_b7106;
	(fp - 0x0108).u0[(uint64) (al_2536 + 0x86)] = 0x86;
	byte al_2553 = al_2536 + 0x86 + g_b7107;
	(fp - 0x0108).u0[(uint64) (al_2553 + 0x87)] = 0x87;
	byte al_2570 = al_2553 + 0x87 + g_b7108;
	(fp - 0x0108).u0[(uint64) (al_2570 + 0x88)] = 0x88;
	byte al_2587 = al_2570 + 0x88 + g_b7109;
	(fp - 0x0108).u0[(uint64) (al_2587 + 0x89)] = 0x89;
	byte al_2604 = al_2587 + 0x89 + g_b710A;
	(fp - 0x0108).u0[(uint64) (al_2604 + 0x8A)] = 0x8A;
	byte al_2621 = al_2604 + 0x8A + g_b710B;
	(fp - 0x0108).u0[(uint64) (al_2621 + 0x8B)] = 0x8B;
	byte al_2638 = al_2621 + 0x8B + g_b710C;
	(fp - 0x0108).u0[(uint64) (al_2638 + 0x8C)] = 0x8C;
	byte al_2655 = al_2638 + 0x8C + g_b710D;
	(fp - 0x0108).u0[(uint64) (al_2655 + 141)] = 141;
	byte al_2672 = al_2655 + 141 + g_b710E;
	(fp - 0x0108).u0[(uint64) (al_2672 + 0x8E)] = 0x8E;
	byte al_2689 = al_2672 + 0x8E + g_b710F;
	(fp - 0x0108).u0[(uint64) (al_2689 + ~0x70)] = ~0x70;
	byte al_2706 = al_2689 + ~0x70 + g_b7110;
	(fp - 0x0108).u0[(uint64) (al_2706 + 0x90)] = 0x90;
	byte al_2723 = al_2706 + 0x90 + g_b7111;
	(fp - 0x0108).u0[(uint64) (al_2723 + 0x91)] = 0x91;
	byte al_2740 = al_2723 + 0x91 + g_b7112;
	(fp - 0x0108).u0[(uint64) (al_2740 + 0x92)] = 0x92;
	byte al_2757 = al_2740 + 0x92 + g_b7113;
	(fp - 0x0108).u0[(uint64) (al_2757 + 0x93)] = 0x93;
	byte al_2774 = al_2757 + 0x93 + g_b7114;
	(fp - 0x0108).u0[(uint64) (al_2774 + 0x94)] = 0x94;
	byte al_2791 = al_2774 + 0x94 + g_b7115;
	(fp - 0x0108).u0[(uint64) (al_2791 + 0x95)] = 0x95;
	byte al_2808 = al_2791 + 0x95 + g_b7116;
	(fp - 0x0108).u0[(uint64) (al_2808 + 0x96)] = 0x96;
	byte al_2825 = al_2808 + 0x96 + g_b7117;
	(fp - 0x0108).u0[(uint64) (al_2825 + 151)] = 151;
	byte al_2842 = al_2825 + 151 + g_b7118;
	(fp - 0x0108).u0[(uint64) (al_2842 + 0x98)] = 0x98;
	byte al_2859 = al_2842 + 0x98 + g_b7119;
	(fp - 0x0108).u0[(uint64) (al_2859 + 0x99)] = 0x99;
	byte al_2876 = al_2859 + 0x99 + g_b711A;
	(fp - 0x0108).u0[(uint64) (al_2876 + 0x9A)] = 0x9A;
	byte al_2893 = al_2876 + 0x9A + g_b711B;
	(fp - 0x0108).u0[(uint64) (al_2893 + 155)] = 155;
	byte al_2910 = al_2893 + 155 + g_b711C;
	(fp - 0x0108).u0[(uint64) (al_2910 + 0x9C)] = 0x9C;
	byte al_2927 = al_2910 + 0x9C + g_b711D;
	(fp - 0x0108).u0[(uint64) (al_2927 + ~0x62)] = ~0x62;
	byte al_2944 = al_2927 + ~0x62 + g_b711E;
	(fp - 0x0108).u0[(uint64) (al_2944 + ~0x61)] = ~0x61;
	byte al_2961 = al_2944 + ~0x61 + g_b711F;
	(fp - 0x0108).u0[(uint64) (al_2961 + ~0x60)] = ~0x60;
	byte al_2978 = al_2961 + ~0x60 + g_b7120;
	(fp - 0x0108).u0[(uint64) (al_2978 + 0xA0)] = 0xA0;
	byte al_2995 = al_2978 + 0xA0 + g_b7121;
	(fp - 0x0108).u0[(uint64) (al_2995 + 161)] = 161;
	byte al_3012 = al_2995 + 161 + g_b7122;
	(fp - 0x0108).u0[(uint64) (al_3012 + 0xA2)] = 0xA2;
	byte al_3029 = al_3012 + 0xA2 + g_b7123;
	(fp - 0x0108).u0[(uint64) (al_3029 + 0xA3)] = 0xA3;
	byte al_3046 = al_3029 + 0xA3 + g_b7124;
	(fp - 0x0108).u0[(uint64) (al_3046 + 0xA4)] = 0xA4;
	byte al_3063 = al_3046 + 0xA4 + g_b7125;
	(fp - 0x0108).u0[(uint64) (al_3063 + 0xA5)] = 0xA5;
	byte al_3080 = al_3063 + 0xA5 + g_b7126;
	(fp - 0x0108).u0[(uint64) (al_3080 + 166)] = 166;
	byte al_3097 = al_3080 + 166 + g_b7127;
	(fp - 0x0108).u0[(uint64) (al_3097 + ~0x58)] = ~0x58;
	byte al_3114 = al_3097 + ~0x58 + g_b7128;
	(fp - 0x0108).u0[(uint64) (al_3114 + 0xA8)] = 0xA8;
	byte al_3131 = al_3114 + 0xA8 + g_b7129;
	(fp - 0x0108).u0[(uint64) (al_3131 + 0xA9)] = 0xA9;
	byte al_3148 = al_3131 + 0xA9 + g_b712A;
	(fp - 0x0108).u0[(uint64) (al_3148 + 0xAA)] = 0xAA;
	byte al_3165 = al_3148 + 0xAA + g_b712B;
	(fp - 0x0108).u0[(uint64) (al_3165 + 171)] = 171;
	byte al_3182 = al_3165 + 171 + g_b712C;
	(fp - 0x0108).u0[(uint64) (al_3182 + 0xAC)] = 0xAC;
	byte al_3199 = al_3182 + 0xAC + g_b712D;
	(fp - 0x0108).u0[(uint64) (al_3199 + ~0x52)] = ~0x52;
	byte al_3216 = al_3199 + ~0x52 + g_b712E;
	(fp - 0x0108).u0[(uint64) (al_3216 + ~0x51)] = ~0x51;
	byte al_3233 = al_3216 + ~0x51 + g_b712F;
	(fp - 0x0108).u0[(uint64) (al_3233 + ~0x50)] = ~0x50;
	byte al_3250 = al_3233 + ~0x50 + g_b7130;
	(fp - 0x0108).u0[(uint64) (al_3250 + 0xB0)] = 0xB0;
	byte al_3267 = al_3250 + 0xB0 + g_b7131;
	(fp - 0x0108).u0[(uint64) (al_3267 + 177)] = 177;
	byte al_3284 = al_3267 + 177 + g_b7132;
	(fp - 0x0108).u0[(uint64) (al_3284 + 0xB2)] = 0xB2;
	byte al_3301 = al_3284 + 0xB2 + g_b7133;
	(fp - 0x0108).u0[(uint64) (al_3301 + ~0x4C)] = ~0x4C;
	byte al_3318 = al_3301 + ~0x4C + g_b7134;
	(fp - 0x0108).u0[(uint64) (al_3318 + 0xB4)] = 0xB4;
	byte al_3335 = al_3318 + 0xB4 + g_b7135;
	(fp - 0x0108).u0[(uint64) (al_3335 + 181)] = 181;
	byte al_3352 = al_3335 + 181 + g_b7136;
	(fp - 0x0108).u0[(uint64) (al_3352 + ~0x49)] = ~0x49;
	byte al_3369 = al_3352 + ~0x49 + g_b7137;
	(fp - 0x0108).u0[(uint64) (al_3369 + ~0x48)] = ~0x48;
	byte al_3386 = al_3369 + ~0x48 + g_b7138;
	(fp - 0x0108).u0[(uint64) (al_3386 + 0xB8)] = 0xB8;
	byte al_3403 = al_3386 + 0xB8 + g_b7139;
	(fp - 0x0108).u0[(uint64) (al_3403 + ~0x46)] = ~0x46;
	byte al_3420 = al_3403 + ~0x46 + g_b713A;
	(fp - 0x0108).u0[(uint64) (al_3420 + ~0x45)] = ~0x45;
	byte al_3437 = al_3420 + ~0x45 + g_b713B;
	(fp - 0x0108).u0[(uint64) (al_3437 + ~0x44)] = ~0x44;
	byte al_3454 = al_3437 + ~0x44 + g_b713C;
	(fp - 0x0108).u0[(uint64) (al_3454 + 188)] = 188;
	byte al_3471 = al_3454 + 188 + g_b713D;
	(fp - 0x0108).u0[(uint64) (al_3471 + ~0x42)] = ~0x42;
	byte al_3488 = al_3471 + ~0x42 + g_b713E;
	(fp - 0x0108).u0[(uint64) (al_3488 + ~0x41)] = ~0x41;
	byte al_3505 = al_3488 + ~0x41 + g_b713F;
	(fp - 0x0108).u0[(uint64) (al_3505 + 191)] = 191;
	byte al_3522 = al_3505 + 191 + g_b7140;
	(fp - 0x0108).u0[(uint64) (al_3522 + 0xC0)] = 0xC0;
	byte al_3539 = al_3522 + 0xC0 + g_b7141;
	(fp - 0x0108).u0[(uint64) (al_3539 + 0xC1)] = 0xC1;
	byte al_3556 = al_3539 + 0xC1 + g_b7142;
	(fp - 0x0108).u0[(uint64) (al_3556 + 0xC2)] = 0xC2;
	byte al_3573 = al_3556 + 0xC2 + g_b7143;
	(fp - 0x0108).u0[(uint64) (al_3573 + 0xC3)] = 0xC3;
	byte al_3590 = al_3573 + 0xC3 + g_b7144;
	(fp - 0x0108).u0[(uint64) (al_3590 + 0xC4)] = 0xC4;
	byte al_3607 = al_3590 + 0xC4 + g_b7145;
	(fp - 0x0108).u0[(uint64) (al_3607 + 0xC5)] = 0xC5;
	byte al_3624 = al_3607 + 0xC5 + g_b7146;
	(fp - 0x0108).u0[(uint64) (al_3624 + 0xC6)] = 0xC6;
	byte al_3641 = al_3624 + 0xC6 + g_b7147;
	(fp - 0x0108).u0[(uint64) (al_3641 + 199)] = 199;
	byte al_3658 = al_3641 + 199 + g_b7148;
	(fp - 0x0108).u0[(uint64) (al_3658 + 200)] = 200;
	byte al_3675 = al_3658 + 200 + g_b7149;
	(fp - 0x0108).u0[(uint64) (al_3675 + 0xC9)] = 0xC9;
	byte al_3692 = al_3675 + 0xC9 + g_b714A;
	(fp - 0x0108).u0[(uint64) (al_3692 + 202)] = 202;
	byte al_3709 = al_3692 + 202 + g_b714B;
	(fp - 0x0108).u0[(uint64) (al_3709 + ~0x34)] = ~0x34;
	byte al_3726 = al_3709 + ~0x34 + g_b714C;
	(fp - 0x0108).u0[(uint64) (al_3726 + 0xCC)] = 0xCC;
	byte al_3743 = al_3726 + 0xCC + g_b714D;
	(fp - 0x0108).u0[(uint64) (al_3743 + ~0x32)] = ~0x32;
	byte al_3760 = al_3743 + ~0x32 + g_b714E;
	(fp - 0x0108).u0[(uint64) (al_3760 + ~0x31)] = ~0x31;
	byte al_3777 = al_3760 + ~0x31 + g_b714F;
	(fp - 0x0108).u0[(uint64) (al_3777 + ~0x30)] = ~0x30;
	byte al_3794 = al_3777 + ~0x30 + g_b7150;
	(fp - 0x0108).u0[(uint64) (al_3794 + 0xD0)] = 0xD0;
	byte al_3811 = al_3794 + 0xD0 + g_b7151;
	(fp - 0x0108).u0[(uint64) (al_3811 + 0xD1)] = 0xD1;
	byte al_3828 = al_3811 + 0xD1 + g_b7152;
	(fp - 0x0108).u0[(uint64) (al_3828 + 0xD2)] = 0xD2;
	byte al_3845 = al_3828 + 0xD2 + g_b7153;
	(fp - 0x0108).u0[(uint64) (al_3845 + 211)] = 211;
	byte al_3862 = al_3845 + 211 + g_b7154;
	(fp - 0x0108).u0[(uint64) (al_3862 + 212)] = 212;
	byte al_3879 = al_3862 + 212 + g_b7155;
	(fp - 0x0108).u0[(uint64) (al_3879 + ~0x2A)] = ~0x2A;
	byte al_3896 = al_3879 + ~0x2A + g_b7156;
	(fp - 0x0108).u0[(uint64) (al_3896 + ~0x29)] = ~0x29;
	byte al_3913 = al_3896 + ~0x29 + g_b7157;
	(fp - 0x0108).u0[(uint64) (al_3913 + ~0x28)] = ~0x28;
	byte al_3930 = al_3913 + ~0x28 + g_b7158;
	(fp - 0x0108).u0[(uint64) (al_3930 + 0xD8)] = 0xD8;
	byte al_3947 = al_3930 + 0xD8 + g_b7159;
	(fp - 0x0108).u0[(uint64) (al_3947 + ~0x26)] = ~0x26;
	byte al_3964 = al_3947 + ~0x26 + g_b715A;
	(fp - 0x0108).u0[(uint64) (al_3964 + ~0x25)] = ~0x25;
	byte al_3981 = al_3964 + ~0x25 + g_b715B;
	(fp - 0x0108).u0[(uint64) (al_3981 + ~0x24)] = ~0x24;
	byte al_3998 = al_3981 + ~0x24 + g_b715C;
	(fp - 0x0108).u0[(uint64) (al_3998 + 220)] = 220;
	byte al_4015 = al_3998 + 220 + g_b715D;
	(fp - 0x0108).u0[(uint64) (al_4015 + ~0x22)] = ~0x22;
	byte al_4032 = al_4015 + ~0x22 + g_b715E;
	(fp - 0x0108).u0[(uint64) (al_4032 + 222)] = 222;
	byte al_4049 = al_4032 + 222 + g_b715F;
	(fp - 0x0108).u0[(uint64) (al_4049 + 223)] = 223;
	byte al_4066 = al_4049 + 223 + g_b7160;
	(fp - 0x0108).u0[(uint64) (al_4066 + 0xE0)] = 0xE0;
	byte al_4083 = al_4066 + 0xE0 + g_b7161;
	(fp - 0x0108).u0[(uint64) (al_4083 + 225)] = 225;
	byte al_4100 = al_4083 + 225 + g_b7162;
	(fp - 0x0108).u0[(uint64) (al_4100 + 226)] = 226;
	byte al_4117 = al_4100 + 226 + g_b7163;
	(fp - 0x0108).u0[(uint64) (al_4117 + 227)] = 227;
	byte al_4134 = al_4117 + 227 + g_b7164;
	(fp - 0x0108).u0[(uint64) (al_4134 + 228)] = 228;
	byte al_4151 = al_4134 + 228 + g_b7165;
	(fp - 0x0108).u0[(uint64) (al_4151 + 229)] = 229;
	byte al_4168 = al_4151 + 229 + g_b7166;
	(fp - 0x0108).u0[(uint64) (al_4168 + ~0x19)] = ~0x19;
	byte al_4185 = al_4168 + ~0x19 + g_b7167;
	(fp - 0x0108).u0[(uint64) (al_4185 + ~0x18)] = ~0x18;
	byte al_4202 = al_4185 + ~0x18 + g_b7168;
	(fp - 0x0108).u0[(uint64) (al_4202 + 232)] = 232;
	byte al_4219 = al_4202 + 232 + g_b7169;
	(fp - 0x0108).u0[(uint64) (al_4219 + 233)] = 233;
	byte al_4236 = al_4219 + 233 + g_b716A;
	(fp - 0x0108).u0[(uint64) (al_4236 + ~0x15)] = ~0x15;
	byte al_4253 = al_4236 + ~0x15 + g_b716B;
	(fp - 0x0108).u0[(uint64) (al_4253 + ~0x14)] = ~0x14;
	byte al_4270 = al_4253 + ~0x14 + g_b716C;
	(fp - 0x0108).u0[(uint64) (al_4270 + ~0x13)] = ~0x13;
	byte al_4287 = al_4270 + ~0x13 + g_b716D;
	(fp - 0x0108).u0[(uint64) (al_4287 + ~0x12)] = ~0x12;
	byte al_4304 = al_4287 + ~0x12 + g_b716E;
	(fp - 0x0108).u0[(uint64) (al_4304 + ~0x11)] = ~0x11;
	byte al_4321 = al_4304 + ~0x11 + g_b716F;
	(fp - 0x0108).u0[(uint64) (al_4321 + ~0x10)] = ~0x10;
	byte al_4338 = al_4321 + ~0x10 + g_b7170;
	(fp - 0x0108).u0[(uint64) (al_4338 + 0xF0)] = 0xF0;
	byte al_4355 = al_4338 + 0xF0 + g_b7171;
	(fp - 0x0108).u0[(uint64) (al_4355 + ~0x0E)] = ~0x0E;
	byte al_4372 = al_4355 + ~0x0E + g_b7172;
	(fp - 0x0108).u0[(uint64) (al_4372 + 242)] = 242;
	byte al_4389 = al_4372 + 242 + g_b7173;
	(fp - 0x0108).u0[(uint64) (al_4389 + ~0x0C)] = ~0x0C;
	byte al_4406 = al_4389 + ~0x0C + g_b7174;
	(fp - 0x0108).u0[(uint64) (al_4406 + 244)] = 244;
	byte al_4423 = al_4406 + 244 + g_b7175;
	(fp - 0x0108).u0[(uint64) (al_4423 + ~0x0A)] = ~0x0A;
	byte al_4440 = al_4423 + ~0x0A + g_b7176;
	(fp - 0x0108).u0[(uint64) (al_4440 + ~0x09)] = ~0x09;
	byte al_4457 = al_4440 + ~0x09 + g_b7177;
	(fp - 0x0108).u0[(uint64) (al_4457 + ~0x08)] = ~0x08;
	byte al_4474 = al_4457 + ~0x08 + g_b7178;
	(fp - 0x0108).u0[(uint64) (al_4474 + ~0x07)] = ~0x07;
	byte al_4491 = al_4474 + ~0x07 + g_b7179;
	(fp - 0x0108).u0[(uint64) (al_4491 + ~0x06)] = ~0x06;
	byte al_4508 = al_4491 + ~0x06 + g_b717A;
	(fp - 0x0108).u0[(uint64) (al_4508 + ~0x05)] = ~0x05;
	byte al_4525 = al_4508 + ~0x05 + g_b717B;
	(fp - 0x0108).u0[(uint64) (al_4525 + ~0x04)] = ~0x04;
	byte al_4542 = al_4525 + ~0x04 + g_b717C;
	(fp - 0x0108).u0[(uint64) (al_4542 + 252)] = 252;
	byte al_4559 = al_4542 + 252 + g_b717D;
	(fp - 0x0108).u0[(uint64) (al_4559 + ~0x02)] = ~0x02;
	byte al_4576 = al_4559 + ~0x02 + g_b717E;
	(fp - 0x0108).u0[(uint64) (al_4576 + ~0x01)] = ~0x01;
	(fp - 0x0108).u0[(uint64) (al_4576 + ~0x01 + g_b717F + ~0x00)] = ~0x00;
	(fp - 0x0108).u0[(uint64) sil_288] = sil_288;
	word32 eax_4630 = (word32) (sil_288 + sil_305);
	(fp - 0x0108).u0[(uint64) (byte) eax_4630] = sil_305;
	word32 eax_4653 = eax_4630 + (word32) sil_322;
	(fp - 0x0108).u0[(uint64) (byte) eax_4653] = sil_322;
	word32 eax_4676 = eax_4653 + (word32) sil_339;
	(fp - 0x0108).u0[(uint64) (byte) eax_4676] = sil_339;
	word32 eax_4699 = eax_4676 + (word32) sil_356;
	(fp - 0x0108).u0[(uint64) (byte) eax_4699] = sil_356;
	word32 eax_4722 = eax_4699 + (word32) sil_373;
	(fp - 0x0108).u0[(uint64) (byte) eax_4722] = sil_373;
	word32 eax_4745 = eax_4722 + (word32) sil_390;
	(fp - 0x0108).u0[(uint64) (byte) eax_4745] = sil_390;
	word32 eax_4768 = eax_4745 + (word32) sil_407;
	(fp - 0x0108).u0[(uint64) (byte) eax_4768] = sil_407;
	word32 eax_4791 = eax_4768 + (word32) sil_424;
	(fp - 0x0108).u0[(uint64) (byte) eax_4791] = sil_424;
	word32 eax_4814 = eax_4791 + (word32) sil_441;
	(fp - 0x0108).u0[(uint64) (byte) eax_4814] = sil_441;
	word32 eax_4837 = eax_4814 + (word32) sil_458;
	(fp - 0x0108).u0[(uint64) (byte) eax_4837] = sil_458;
	word32 eax_4860 = eax_4837 + (word32) sil_475;
	(fp - 0x0108).u0[(uint64) (byte) eax_4860] = sil_475;
	word32 eax_4883 = eax_4860 + (word32) sil_492;
	(fp - 0x0108).u0[(uint64) (byte) eax_4883] = sil_492;
	word32 eax_4906 = eax_4883 + (word32) sil_509;
	(fp - 0x0108).u0[(uint64) (byte) eax_4906] = sil_509;
	word32 eax_4929 = eax_4906 + (word32) sil_526;
	(fp - 0x0108).u0[(uint64) (byte) eax_4929] = sil_526;
	word32 eax_4952 = eax_4929 + (word32) sil_543;
	(fp - 0x0108).u0[(uint64) (byte) eax_4952] = sil_543;
	word32 eax_4975 = eax_4952 + (word32) sil_560;
	(fp - 0x0108).u0[(uint64) (byte) eax_4975] = sil_560;
	word32 eax_4998 = eax_4975 + (word32) sil_577;
	(fp - 0x0108).u0[(uint64) (byte) eax_4998] = sil_577;
	word32 eax_5021 = eax_4998 + (word32) sil_594;
	(fp - 0x0108).u0[(uint64) (byte) eax_5021] = sil_594;
	word32 eax_5044 = eax_5021 + (word32) sil_611;
	(fp - 0x0108).u0[(uint64) (byte) eax_5044] = sil_611;
	word32 eax_5067 = eax_5044 + (word32) sil_628;
	(fp - 0x0108).u0[(uint64) (byte) eax_5067] = sil_628;
	word32 eax_5090 = eax_5067 + (word32) sil_645;
	(fp - 0x0108).u0[(uint64) (byte) eax_5090] = sil_645;
	word32 eax_5113 = eax_5090 + (word32) sil_662;
	(fp - 0x0108).u0[(uint64) (byte) eax_5113] = sil_662;
	word32 eax_5136 = eax_5113 + (word32) sil_679;
	(fp - 0x0108).u0[(uint64) (byte) eax_5136] = sil_679;
	word32 eax_5159 = eax_5136 + (word32) sil_696;
	(fp - 0x0108).u0[(uint64) (byte) eax_5159] = sil_696;
	word32 eax_5182 = eax_5159 + (word32) sil_713;
	(fp - 0x0108).u0[(uint64) (byte) eax_5182] = sil_713;
	word32 eax_5205 = eax_5182 + (word32) sil_730;
	(fp - 0x0108).u0[(uint64) (byte) eax_5205] = sil_730;
	word32 eax_5228 = eax_5205 + (word32) sil_747;
	(fp - 0x0108).u0[(uint64) (byte) eax_5228] = sil_747;
	word32 eax_5251 = eax_5228 + (word32) sil_764;
	(fp - 0x0108).u0[(uint64) (byte) eax_5251] = sil_764;
	word32 eax_5274 = eax_5251 + (word32) sil_781;
	(fp - 0x0108).u0[(uint64) (byte) eax_5274] = sil_781;
	word32 eax_5297 = eax_5274 + (word32) sil_798;
	(fp - 0x0108).u0[(uint64) (byte) eax_5297] = sil_798;
	word32 eax_5320 = eax_5297 + (word32) sil_815;
	(fp - 0x0108).u0[(uint64) (byte) eax_5320] = sil_815;
	word32 eax_5343 = eax_5320 + (word32) sil_832;
	(fp - 0x0108).u0[(uint64) (byte) eax_5343] = sil_832;
	word32 eax_5366 = eax_5343 + (word32) sil_849;
	(fp - 0x0108).u0[(uint64) (byte) eax_5366] = sil_849;
	word32 eax_5389 = eax_5366 + (word32) sil_866;
	(fp - 0x0108).u0[(uint64) (byte) eax_5389] = sil_866;
	word32 eax_5412 = eax_5389 + (word32) sil_883;
	(fp - 0x0108).u0[(uint64) (byte) eax_5412] = sil_883;
	word32 eax_5435 = eax_5412 + (word32) sil_900;
	(fp - 0x0108).u0[(uint64) (byte) eax_5435] = sil_900;
	word32 eax_5458 = eax_5435 + (word32) sil_917;
	(fp - 0x0108).u0[(uint64) (byte) eax_5458] = sil_917;
	word32 eax_5481 = eax_5458 + (word32) sil_934;
	(fp - 0x0108).u0[(uint64) (byte) eax_5481] = sil_934;
	word32 eax_5504 = eax_5481 + (word32) sil_951;
	(fp - 0x0108).u0[(uint64) (byte) eax_5504] = sil_951;
	word32 eax_5527 = eax_5504 + (word32) sil_968;
	(fp - 0x0108).u0[(uint64) (byte) eax_5527] = sil_968;
	word32 eax_5550 = eax_5527 + (word32) sil_985;
	(fp - 0x0108).u0[(uint64) (byte) eax_5550] = sil_985;
	word32 eax_5573 = eax_5550 + (word32) sil_1002;
	(fp - 0x0108).u0[(uint64) (byte) eax_5573] = sil_1002;
	word32 eax_5596 = eax_5573 + (word32) sil_1019;
	(fp - 0x0108).u0[(uint64) (byte) eax_5596] = sil_1019;
	word32 eax_5619 = eax_5596 + (word32) sil_1036;
	(fp - 0x0108).u0[(uint64) (byte) eax_5619] = sil_1036;
	word32 eax_5642 = eax_5619 + (word32) sil_1053;
	(fp - 0x0108).u0[(uint64) (byte) eax_5642] = sil_1053;
	word32 eax_5665 = eax_5642 + (word32) sil_1070;
	(fp - 0x0108).u0[(uint64) (byte) eax_5665] = sil_1070;
	word32 eax_5688 = eax_5665 + (word32) sil_1087;
	(fp - 0x0108).u0[(uint64) (byte) eax_5688] = sil_1087;
	word32 eax_5711 = eax_5688 + (word32) sil_1104;
	(fp - 0x0108).u0[(uint64) (byte) eax_5711] = sil_1104;
	word32 eax_5734 = eax_5711 + (word32) sil_1121;
	(fp - 0x0108).u0[(uint64) (byte) eax_5734] = sil_1121;
	word32 eax_5757 = eax_5734 + (word32) sil_1138;
	(fp - 0x0108).u0[(uint64) (byte) eax_5757] = sil_1138;
	word32 eax_5780 = eax_5757 + (word32) sil_1155;
	(fp - 0x0108).u0[(uint64) (byte) eax_5780] = sil_1155;
	word32 eax_5803 = eax_5780 + (word32) sil_1172;
	(fp - 0x0108).u0[(uint64) (byte) eax_5803] = sil_1172;
	word32 eax_5826 = eax_5803 + (word32) sil_1189;
	(fp - 0x0108).u0[(uint64) (byte) eax_5826] = sil_1189;
	word32 eax_5849 = eax_5826 + (word32) sil_1206;
	(fp - 0x0108).u0[(uint64) (byte) eax_5849] = sil_1206;
	word32 eax_5872 = eax_5849 + (word32) sil_1223;
	(fp - 0x0108).u0[(uint64) (byte) eax_5872] = sil_1223;
	word32 eax_5895 = eax_5872 + (word32) sil_1240;
	(fp - 0x0108).u0[(uint64) (byte) eax_5895] = sil_1240;
	word32 eax_5918 = eax_5895 + (word32) sil_1257;
	(fp - 0x0108).u0[(uint64) (byte) eax_5918] = sil_1257;
	word32 eax_5941 = eax_5918 + (word32) sil_1274;
	(fp - 0x0108).u0[(uint64) (byte) eax_5941] = sil_1274;
	word32 eax_5964 = eax_5941 + (word32) sil_1291;
	(fp - 0x0108).u0[(uint64) (byte) eax_5964] = sil_1291;
	word32 eax_5987 = eax_5964 + (word32) sil_1308;
	(fp - 0x0108).u0[(uint64) (byte) eax_5987] = sil_1308;
	(fp - 0x0108).u0[(uint64) ((byte) eax_5987 + sil_1325)] = sil_1325;
	printf("Decrypted message: %s\n", fp - 0x0148);
}

// 000000000000488A: void main()
void main()
{
	multiplication_table(0x11);
	decrypt_message();
}

// tmpibt98ua1_plt.c
// Generated by decompiling tmpibt98ua1
// using Reko decompiler version 0.11.6.0.

#include "tmpibt98ua1.h"

<anonymous> g_t1036 = <code>; // 0000000000001036
// tmpibt98ua1_bss.c
// Generated by decompiling tmpibt98ua1
// using Reko decompiler version 0.11.6.0.

#include "tmpibt98ua1.h"

byte g_b7187 = 0x00; // 0000000000007187
// tmpibt98ua1_got.c
// Generated by decompiling tmpibt98ua1
// using Reko decompiler version 0.11.6.0.

#include "tmpibt98ua1.h"

<anonymous> * __libc_start_main_GOT = null; // 0000000000006FC0
<anonymous> * _ITM_deregisterTMCloneTable_GOT = null; // 0000000000006FC8
<anonymous> * __gmon_start___GOT = null; // 0000000000006FD0
<anonymous> * _ITM_registerTMCloneTable_GOT = null; // 0000000000006FD8
<anonymous> * __cxa_finalize_GOT = null; // 0000000000006FE0
// tmpibt98ua1_init.c
// Generated by decompiling tmpibt98ua1
// using Reko decompiler version 0.11.6.0.

#include "tmpibt98ua1.h"

// 0000000000001000: void _init()
void _init()
{
	if (__gmon_start__ != 0x00)
		__gmon_start__();
}

// tmpibt98ua1_data.c
// Generated by decompiling tmpibt98ua1
// using Reko decompiler version 0.11.6.0.

#include "tmpibt98ua1.h"

word64 g_qw7028 = 0x7028; // 0000000000007028
byte g_b7080 = 0x49; // 0000000000007080
byte g_b7081 = 110; // 0000000000007081
byte g_b7082 = 0x20; // 0000000000007082
byte g_b7083 = 99; // 0000000000007083
byte g_b7084 = 114; // 0000000000007084
byte g_b7085 = 121; // 0000000000007085
byte g_b7086 = 0x70; // 0000000000007086
byte g_b7087 = 116; // 0000000000007087
byte g_b7088 = 111; // 0000000000007088
byte g_b7089 = 0x67; // 0000000000007089
byte g_b708A = 114; // 000000000000708A
byte g_b708B = 0x61; // 000000000000708B
byte g_b708C = 0x70; // 000000000000708C
byte g_b708D = 0x68; // 000000000000708D
byte g_b708E = 121; // 000000000000708E
byte g_b708F = 44; // 000000000000708F
byte g_b7090 = 0x20; // 0000000000007090
byte g_b7091 = 0x52; // 0000000000007091
byte g_b7092 = 0x43; // 0000000000007092
byte g_b7093 = 0x34; // 0000000000007093
byte g_b7094 = 0x20; // 0000000000007094
byte g_b7095 = 0x28; // 0000000000007095
byte g_b7096 = 0x52; // 0000000000007096
byte g_b7097 = 0x69; // 0000000000007097
byte g_b7098 = 118; // 0000000000007098
byte g_b7099 = 101; // 0000000000007099
byte g_b709A = 115; // 000000000000709A
byte g_b709B = 116; // 000000000000709B
byte g_b709C = 0x20; // 000000000000709C
byte g_b709D = 0x43; // 000000000000709D
byte g_b709E = 0x69; // 000000000000709E
byte g_b709F = 0x70; // 000000000000709F
byte g_b70A0 = 0x68; // 00000000000070A0
byte g_b70A1 = 101; // 00000000000070A1
byte g_b70A2 = 114; // 00000000000070A2
byte g_b70A3 = 0x20; // 00000000000070A3
byte g_b70A4 = 0x34; // 00000000000070A4
byte g_b70A5 = 44; // 00000000000070A5
byte g_b70A6 = 0x20; // 00000000000070A6
byte g_b70A7 = 0x61; // 00000000000070A7
byte g_b70A8 = 0x6C; // 00000000000070A8
byte g_b70A9 = 115; // 00000000000070A9
byte g_b70AA = 111; // 00000000000070AA
byte g_b70AB = 0x20; // 00000000000070AB
byte g_b70AC = 0x6B; // 00000000000070AC
byte g_b70AD = 110; // 00000000000070AD
byte g_b70AE = 111; // 00000000000070AE
byte g_b70AF = 0x77; // 00000000000070AF
byte g_b70B0 = 110; // 00000000000070B0
byte g_b70B1 = 0x20; // 00000000000070B1
byte g_b70B2 = 0x61; // 00000000000070B2
byte g_b70B3 = 115; // 00000000000070B3
byte g_b70B4 = 0x20; // 00000000000070B4
byte g_b70B5 = 0x41; // 00000000000070B5
byte g_b70B6 = 0x52; // 00000000000070B6
byte g_b70B7 = 0x43; // 00000000000070B7
byte g_b70B8 = 0x34; // 00000000000070B8
byte g_b70B9 = 0x20; // 00000000000070B9
byte g_b70BA = 111; // 00000000000070BA
byte g_b70BB = 114; // 00000000000070BB
byte g_b70BC = 0x20; // 00000000000070BC
byte g_b70BD = 0x41; // 00000000000070BD
byte g_b70BE = 0x52; // 00000000000070BE
byte g_b70BF = 0x43; // 00000000000070BF
byte g_b70C0 = 0x46; // 00000000000070C0
byte g_b70C1 = 0x4F; // 00000000000070C1
byte g_b70C2 = 0x55; // 00000000000070C2
byte g_b70C3 = 0x52; // 00000000000070C3
byte g_b70C4 = 44; // 00000000000070C4
byte g_b70C5 = 0x20; // 00000000000070C5
byte g_b70C6 = 0x6D; // 00000000000070C6
byte g_b70C7 = 101; // 00000000000070C7
byte g_b70C8 = 0x61; // 00000000000070C8
byte g_b70C9 = 110; // 00000000000070C9
byte g_b70CA = 0x69; // 00000000000070CA
byte g_b70CB = 110; // 00000000000070CB
byte g_b70CC = 0x67; // 00000000000070CC
byte g_b70CD = 0x20; // 00000000000070CD
byte g_b70CE = 0x41; // 00000000000070CE
byte g_b70CF = 0x6C; // 00000000000070CF
byte g_b70D0 = 0x6C; // 00000000000070D0
byte g_b70D1 = 101; // 00000000000070D1
byte g_b70D2 = 0x67; // 00000000000070D2
byte g_b70D3 = 101; // 00000000000070D3
byte g_b70D4 = 100; // 00000000000070D4
byte g_b70D5 = 0x20; // 00000000000070D5
byte g_b70D6 = 0x52; // 00000000000070D6
byte g_b70D7 = 0x43; // 00000000000070D7
byte g_b70D8 = 0x34; // 00000000000070D8
byte g_b70D9 = 44; // 00000000000070D9
byte g_b70DA = 0x20; // 00000000000070DA
byte g_b70DB = 115; // 00000000000070DB
byte g_b70DC = 101; // 00000000000070DC
byte g_b70DD = 101; // 00000000000070DD
byte g_b70DE = 0x20; // 00000000000070DE
byte g_b70DF = 0x62; // 00000000000070DF
byte g_b70E0 = 101; // 00000000000070E0
byte g_b70E1 = 0x6C; // 00000000000070E1
byte g_b70E2 = 111; // 00000000000070E2
byte g_b70E3 = 0x77; // 00000000000070E3
byte g_b70E4 = 0x29; // 00000000000070E4
byte g_b70E5 = 0x20; // 00000000000070E5
byte g_b70E6 = 0x69; // 00000000000070E6
byte g_b70E7 = 115; // 00000000000070E7
byte g_b70E8 = 0x20; // 00000000000070E8
byte g_b70E9 = 0x61; // 00000000000070E9
byte g_b70EA = 0x20; // 00000000000070EA
byte g_b70EB = 115; // 00000000000070EB
byte g_b70EC = 116; // 00000000000070EC
byte g_b70ED = 114; // 00000000000070ED
byte g_b70EE = 101; // 00000000000070EE
byte g_b70EF = 0x61; // 00000000000070EF
byte g_b70F0 = 0x6D; // 00000000000070F0
byte g_b70F1 = 0x20; // 00000000000070F1
byte g_b70F2 = 99; // 00000000000070F2
byte g_b70F3 = 0x69; // 00000000000070F3
byte g_b70F4 = 0x70; // 00000000000070F4
byte g_b70F5 = 0x68; // 00000000000070F5
byte g_b70F6 = 101; // 00000000000070F6
byte g_b70F7 = 114; // 00000000000070F7
byte g_b70F8 = 0x2E; // 00000000000070F8
byte g_b70F9 = 0x20; // 00000000000070F9
byte g_b70FA = 0x57; // 00000000000070FA
byte g_b70FB = 0x68; // 00000000000070FB
byte g_b70FC = 0x69; // 00000000000070FC
byte g_b70FD = 0x6C; // 00000000000070FD
byte g_b70FE = 101; // 00000000000070FE
byte g_b70FF = 0x20; // 00000000000070FF
byte g_b7100 = 0x69; // 0000000000007100
byte g_b7101 = 116; // 0000000000007101
byte g_b7102 = 0x20; // 0000000000007102
byte g_b7103 = 0x69; // 0000000000007103
byte g_b7104 = 115; // 0000000000007104
byte g_b7105 = 0x20; // 0000000000007105
byte g_b7106 = 114; // 0000000000007106
byte g_b7107 = 101; // 0000000000007107
byte g_b7108 = 0x6D; // 0000000000007108
byte g_b7109 = 0x61; // 0000000000007109
byte g_b710A = 114; // 000000000000710A
byte g_b710B = 0x6B; // 000000000000710B
byte g_b710C = 0x61; // 000000000000710C
byte g_b710D = 0x62; // 000000000000710D
byte g_b710E = 0x6C; // 000000000000710E
byte g_b710F = 101; // 000000000000710F
byte g_b7110 = 0x20; // 0000000000007110
byte g_b7111 = 0x66; // 0000000000007111
byte g_b7112 = 111; // 0000000000007112
byte g_b7113 = 114; // 0000000000007113
byte g_b7114 = 0x20; // 0000000000007114
byte g_b7115 = 0x69; // 0000000000007115
byte g_b7116 = 116; // 0000000000007116
byte g_b7117 = 115; // 0000000000007117
byte g_b7118 = 0x20; // 0000000000007118
byte g_b7119 = 115; // 0000000000007119
byte g_b711A = 0x69; // 000000000000711A
byte g_b711B = 0x6D; // 000000000000711B
byte g_b711C = 0x70; // 000000000000711C
byte g_b711D = 0x6C; // 000000000000711D
byte g_b711E = 0x69; // 000000000000711E
byte g_b711F = 99; // 000000000000711F
byte g_b7120 = 0x69; // 0000000000007120
byte g_b7121 = 116; // 0000000000007121
byte g_b7122 = 121; // 0000000000007122
byte g_b7123 = 0x20; // 0000000000007123
byte g_b7124 = 0x61; // 0000000000007124
byte g_b7125 = 110; // 0000000000007125
byte g_b7126 = 100; // 0000000000007126
byte g_b7127 = 0x20; // 0000000000007127
byte g_b7128 = 115; // 0000000000007128
byte g_b7129 = 0x70; // 0000000000007129
byte g_b712A = 101; // 000000000000712A
byte g_b712B = 101; // 000000000000712B
byte g_b712C = 100; // 000000000000712C
byte g_b712D = 0x20; // 000000000000712D
byte g_b712E = 0x69; // 000000000000712E
byte g_b712F = 110; // 000000000000712F
byte g_b7130 = 0x20; // 0000000000007130
byte g_b7131 = 115; // 0000000000007131
byte g_b7132 = 111; // 0000000000007132
byte g_b7133 = 0x66; // 0000000000007133
byte g_b7134 = 116; // 0000000000007134
byte g_b7135 = 0x77; // 0000000000007135
byte g_b7136 = 0x61; // 0000000000007136
byte g_b7137 = 114; // 0000000000007137
byte g_b7138 = 101; // 0000000000007138
byte g_b7139 = 44; // 0000000000007139
byte g_b713A = 0x20; // 000000000000713A
byte g_b713B = 0x6D; // 000000000000713B
byte g_b713C = 117; // 000000000000713C
byte g_b713D = 0x6C; // 000000000000713D
byte g_b713E = 116; // 000000000000713E
byte g_b713F = 0x69; // 000000000000713F
byte g_b7140 = 0x70; // 0000000000007140
byte g_b7141 = 0x6C; // 0000000000007141
byte g_b7142 = 101; // 0000000000007142
byte g_b7143 = 0x20; // 0000000000007143
byte g_b7144 = 118; // 0000000000007144
byte g_b7145 = 117; // 0000000000007145
byte g_b7146 = 0x6C; // 0000000000007146
byte g_b7147 = 110; // 0000000000007147
byte g_b7148 = 101; // 0000000000007148
byte g_b7149 = 114; // 0000000000007149
byte g_b714A = 0x61; // 000000000000714A
byte g_b714B = 0x62; // 000000000000714B
byte g_b714C = 0x69; // 000000000000714C
byte g_b714D = 0x6C; // 000000000000714D
byte g_b714E = 0x69; // 000000000000714E
byte g_b714F = 116; // 000000000000714F
byte g_b7150 = 0x69; // 0000000000007150
byte g_b7151 = 101; // 0000000000007151
byte g_b7152 = 115; // 0000000000007152
byte g_b7153 = 0x20; // 0000000000007153
byte g_b7154 = 0x68; // 0000000000007154
byte g_b7155 = 0x61; // 0000000000007155
byte g_b7156 = 118; // 0000000000007156
byte g_b7157 = 101; // 0000000000007157
byte g_b7158 = 0x20; // 0000000000007158
byte g_b7159 = 0x62; // 0000000000007159
byte g_b715A = 101; // 000000000000715A
byte g_b715B = 101; // 000000000000715B
byte g_b715C = 110; // 000000000000715C
byte g_b715D = 0x20; // 000000000000715D
byte g_b715E = 100; // 000000000000715E
byte g_b715F = 0x69; // 000000000000715F
byte g_b7160 = 115; // 0000000000007160
byte g_b7161 = 99; // 0000000000007161
byte g_b7162 = 111; // 0000000000007162
byte g_b7163 = 118; // 0000000000007163
byte g_b7164 = 101; // 0000000000007164
byte g_b7165 = 114; // 0000000000007165
byte g_b7166 = 101; // 0000000000007166
byte g_b7167 = 100; // 0000000000007167
byte g_b7168 = 0x20; // 0000000000007168
byte g_b7169 = 0x69; // 0000000000007169
byte g_b716A = 110; // 000000000000716A
byte g_b716B = 0x20; // 000000000000716B
byte g_b716C = 0x52; // 000000000000716C
byte g_b716D = 0x43; // 000000000000716D
byte g_b716E = 0x34; // 000000000000716E
byte g_b716F = 44; // 000000000000716F
byte g_b7170 = 0x20; // 0000000000007170
byte g_b7171 = 114; // 0000000000007171
byte g_b7172 = 101; // 0000000000007172
byte g_b7173 = 110; // 0000000000007173
byte g_b7174 = 100; // 0000000000007174
byte g_b7175 = 101; // 0000000000007175
byte g_b7176 = 114; // 0000000000007176
byte g_b7177 = 0x69; // 0000000000007177
byte g_b7178 = 110; // 0000000000007178
byte g_b7179 = 0x67; // 0000000000007179
byte g_b717A = 0x20; // 000000000000717A
byte g_b717B = 0x69; // 000000000000717B
byte g_b717C = 116; // 000000000000717C
byte g_b717D = 0x20; // 000000000000717D
byte g_b717E = 0x69; // 000000000000717E
byte g_b717F = 110; // 000000000000717F
// tmpibt98ua1_fini.c
// Generated by decompiling tmpibt98ua1
// using Reko decompiler version 0.11.6.0.

#include "tmpibt98ua1.h"

// 00000000000048AC: void _fini()
void _fini()
{
}

// tmpibt98ua1_got_plt.c
// Generated by decompiling tmpibt98ua1
// using Reko decompiler version 0.11.6.0.

#include "tmpibt98ua1.h"

<anonymous> * printf_GOT = &g_t1036; // 0000000000007000
