// tmpzwd6ztjv_text.c
// Generated by decompiling tmpzwd6ztjv
// using Reko decompiler version 0.11.6.0.

#include "tmpzwd6ztjv.h"

// 0000000000001060: void main()
void main()
{
	it_crowd();
	printf("Some calculation returned %d.\n", -1820555729);
}

// 0000000000001090: void _start(Register (ptr64 Eq_18) rdx, Stack word32 dwArg00, Stack (ptr64 char) ptrArg08)
void _start(void (* rdx)(), word32 dwArg00, char * ptrArg08)
{
	__align_stack<word64>(&ptrArg08);
	word64 qwArg00;
	void * fp;
	__libc_start_main(&g_t1060, (int32) qwArg00, &ptrArg08, null, null, rdx, fp);
	__halt();
}

// 00000000000010C0: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
	if (&g_b4020 == &g_b4020 || _ITM_deregisterTMCloneTable == null)
		return;
	_ITM_deregisterTMCloneTable();
}

// 00000000000010F0: void register_tm_clones()
// Called from:
//      frame_dummy
void register_tm_clones()
{
	Eq_53 rsi_6 = &g_b4020 - &g_b4020;
	if ((rsi_6 >> 0x3F) + (rsi_6 >> 0x03) >> 0x01 == 0x00 || _ITM_registerTMCloneTable == null)
		return;
	_ITM_registerTMCloneTable();
}

// 0000000000001130: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	if (g_b4020 != 0x00)
		return;
	if (__cxa_finalize != 0x00)
		__cxa_finalize(g_qw4018);
	deregister_tm_clones();
	g_b4020 = 0x01;
}

// 0000000000001170: void frame_dummy()
void frame_dummy()
{
	register_tm_clones();
}

// 0000000000001180: void it_crowd()
// Called from:
//      main
void it_crowd()
{
	puts("Are you feeling stressed, Jen?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Well, I guess you're not.\n");
	puts("Well done, Jen.\n");
}

// 0000000000001290: void some_calculation()
void some_calculation()
{
}

// tmpzwd6ztjv_data.c
// Generated by decompiling tmpzwd6ztjv
// using Reko decompiler version 0.11.6.0.

#include "tmpzwd6ztjv.h"

word64 g_qw4018 = 0x4018; // 0000000000004018
// tmpzwd6ztjv_bss.c
// Generated by decompiling tmpzwd6ztjv
// using Reko decompiler version 0.11.6.0.

#include "tmpzwd6ztjv.h"

byte g_b4020 = 0x00; // 0000000000004020
// tmpzwd6ztjv_init.c
// Generated by decompiling tmpzwd6ztjv
// using Reko decompiler version 0.11.6.0.

#include "tmpzwd6ztjv.h"

// 0000000000001000: void _init()
void _init()
{
	if (__gmon_start__ != 0x00)
		__gmon_start__();
}

// tmpzwd6ztjv_fini.c
// Generated by decompiling tmpzwd6ztjv
// using Reko decompiler version 0.11.6.0.

#include "tmpzwd6ztjv.h"

// 00000000000012D0: void _fini()
void _fini()
{
}

// tmpzwd6ztjv_got.c
// Generated by decompiling tmpzwd6ztjv
// using Reko decompiler version 0.11.6.0.

#include "tmpzwd6ztjv.h"

<anonymous> * __libc_start_main_GOT = null; // 0000000000003FC0
<anonymous> * _ITM_deregisterTMCloneTable_GOT = null; // 0000000000003FC8
<anonymous> * __gmon_start___GOT = null; // 0000000000003FD0
<anonymous> * _ITM_registerTMCloneTable_GOT = null; // 0000000000003FD8
<anonymous> * __cxa_finalize_GOT = null; // 0000000000003FE0
// tmpzwd6ztjv_plt.c
// Generated by decompiling tmpzwd6ztjv
// using Reko decompiler version 0.11.6.0.

#include "tmpzwd6ztjv.h"

<anonymous> g_t1036 = <code>; // 0000000000001036
<anonymous> g_t1046 = <code>; // 0000000000001046
// tmpzwd6ztjv_got_plt.c
// Generated by decompiling tmpzwd6ztjv
// using Reko decompiler version 0.11.6.0.

#include "tmpzwd6ztjv.h"

<anonymous> * puts_GOT = &g_t1036; // 0000000000004000
<anonymous> * printf_GOT = &g_t1046; // 0000000000004008
