// tmpbyu6zqm4_TEXT_text_startup.c
// Generated by decompiling tmpbyu6zqm4
// using Reko decompiler version 0.11.6.0.

#include "tmpbyu6zqm4.h"

// 0000000100001E7A: void main()
void main()
{
	short_multiplication_table();
	count_sheep();
}

// tmpbyu6zqm4_TEXT_text.c
// Generated by decompiling tmpbyu6zqm4
// using Reko decompiler version 0.11.6.0.

#include "tmpbyu6zqm4.h"

// 0000000100001517: void count_sheep()
// Called from:
//      main
void count_sheep()
{
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("(nice) ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	puts("ZzZzZz...");
}

// 0000000100001C46: void short_multiplication_table()
// Called from:
//      main
void short_multiplication_table()
{
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\n");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\n");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\n");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\n");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\n");
}

// tmpbyu6zqm4.globals.c
// Generated by decompiling tmpbyu6zqm4
// using Reko decompiler version 0.11.6.0.

#include "tmpbyu6zqm4.h"

<anonymous> * __imp__dyld_stub_binder; // 0000000000002000
<anonymous> * __imp__printf; // 0000000000003000
<anonymous> * __imp__puts; // 0000000000003008
// tmpbyu6zqm4_TEXT_stubs.c
// Generated by decompiling tmpbyu6zqm4
// using Reko decompiler version 0.11.6.0.

#include "tmpbyu6zqm4.h"

// 0000000100001E9C: Register int32 printf(Register (ptr64 char) rdi)
// Called from:
//      count_sheep
//      short_multiplication_table
int32 printf(char * rdi)
{
	return printf(rdi, 0x00);
}

// 0000000100001EA2: Register int32 puts(Register (ptr64 char) rdi)
// Called from:
//      count_sheep
int32 puts(char * rdi)
{
	return puts(rdi);
}

