// tmpqkxj5rn8_TEXT_text.c
// Generated by decompiling tmpqkxj5rn8
// using Reko decompiler version 0.11.6.0.

#include "tmpqkxj5rn8.h"

// 0000000100000D40: void it_crowd()
// Called from:
//      main
void it_crowd()
{
	puts("Are you feeling stressed, Jen?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Well, I guess you're not.\n");
	puts("Well done, Jen.\n");
}

// 0000000100000E50: void some_calculation()
void some_calculation()
{
}

// tmpqkxj5rn8_TEXT_text_startup.c
// Generated by decompiling tmpqkxj5rn8
// using Reko decompiler version 0.11.6.0.

#include "tmpqkxj5rn8.h"

// 0000000100000E90: void main()
void main()
{
	it_crowd();
	printf("Some calculation returned %d.\n");
}

// tmpqkxj5rn8.globals.c
// Generated by decompiling tmpqkxj5rn8
// using Reko decompiler version 0.11.6.0.

#include "tmpqkxj5rn8.h"

<anonymous> * __imp__dyld_stub_binder; // 0000000000001000
<anonymous> * __imp__printf; // 0000000000002000
<anonymous> * __imp__puts; // 0000000000002008
// tmpqkxj5rn8_TEXT_stubs.c
// Generated by decompiling tmpqkxj5rn8
// using Reko decompiler version 0.11.6.0.

#include "tmpqkxj5rn8.h"

// 0000000100000EB6: void printf(Register (ptr64 char) rdi)
// Called from:
//      main
void printf(char * rdi)
{
	printf(rdi, 0x00);
}

// 0000000100000EBC: void puts(Register (ptr64 char) rdi)
// Called from:
//      it_crowd
void puts(char * rdi)
{
	puts(rdi);
}

