//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int32_t __do_global_dtors_aux(void);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
int32_t deregister_tm_clones(void);
int32_t frame_dummy(void);
int32_t function_1030(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1040(char * format, ...);
int32_t function_1050(char * s);
int32_t function_1060(void);
int32_t function_10e8(int32_t a1);
int32_t it_crowd(void);
int32_t register_tm_clones(void);
int32_t some_calculation(int32_t a1);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1020
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x2fdf);
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1030
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * format, ...) {
    // 0x1040
    return printf(format);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(char * s) {
    // 0x1050
    return puts(s);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(void) {
    // 0x1060
    int32_t result; // 0x1060
    return result;
}

// Address range: 0x1070 - 0x10b2
int main(int argc, char ** argv) {
    // 0x1070
    int32_t v1; // 0x1070
    __x86_get_pc_thunk_bx(v1);
    it_crowd();
    printf((char *)(v1 + 4005));
    return 0;
}

// Address range: 0x10c0 - 0x10e8
int32_t _start(int32_t a1) {
    // 0x10c0
    int32_t v1; // 0x10c0
    function_10e8(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x2f1c); // 0x10dc
    int32_t v3; // 0x10c0
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g1);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x10e8 - 0x10ec
int32_t function_10e8(int32_t a1) {
    // 0x10e8
    int32_t result; // 0x10e8
    return result;
}

// Address range: 0x10f0 - 0x10f4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10f0
    int32_t result; // 0x10f0
    return result;
}

// Address range: 0x1100 - 0x1139
int32_t deregister_tm_clones(void) {
    // 0x1100
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x1100
    return v1 + 0x2f0f;
}

// Address range: 0x1140 - 0x1187
int32_t register_tm_clones(void) {
    // 0x1140
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x1190 - 0x11db
int32_t __do_global_dtors_aux(void) {
    // 0x1190
    int32_t v1; // 0x1190
    int32_t result = __x86_get_pc_thunk_bx(v1); // 0x1198
    char * v2 = (char *)(v1 + 0x2e77); // 0x11a6
    if (*v2 != 0) {
        // 0x11d6
        return result;
    }
    // 0x11af
    if (*(int32_t *)(v1 + 0x2e47) != 0) {
        // 0x11b9
        function_1060();
    }
    int32_t result2 = deregister_tm_clones(); // 0x11ca
    *v2 = 1;
    // 0x11d6
    return result2;
}

// Address range: 0x11e0 - 0x11e9
int32_t frame_dummy(void) {
    // 0x11e0
    return register_tm_clones();
}

// Address range: 0x11e9 - 0x11ed
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x11e9
    int32_t result; // 0x11e9
    return result;
}

// Address range: 0x11f0 - 0x130c
int32_t it_crowd(void) {
    // 0x11f0
    int32_t v1; // 0x11f0
    __x86_get_pc_thunk_bx(v1);
    puts((char *)(v1 + 3601));
    char * str = (char *)(v1 + 3664); // 0x1212
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts(str);
    puts((char *)(v1 + 3679));
    return puts((char *)(v1 + 3706));
}

// Address range: 0x1310 - 0x1353
int32_t some_calculation(int32_t a1) {
    int32_t v1 = (a1 + 2) * a1; // 0x1319
    int32_t v2 = v1 + a1 + v1 * v1; // 0x1323
    int32_t v3 = v2 + a1 + v2 * v2; // 0x132c
    int32_t v4 = v3 + a1 + v3 * v3; // 0x1335
    int32_t v5 = v4 + a1 + v4 * v4; // 0x133e
    int32_t v6 = v5 + a1 + v5 * v5; // 0x1347
    return v6 + a1 + v6 * v6;
}

// Address range: 0x1354 - 0x1368
int32_t _fini(void) {
    // 0x1354
    int32_t v1; // 0x1354
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (12.2.0)
// Detected functions: 17

