// tmpq26h7gnf_TEXT_text_startup.c
// Generated by decompiling tmpq26h7gnf
// using Reko decompiler version 0.11.6.0.

#include "tmpq26h7gnf.h"

// 0000000100003E58: void main()
void main()
{
	short_multiplication_table();
	count_sheep();
}

// tmpq26h7gnf_TEXT_text.c
// Generated by decompiling tmpq26h7gnf
// using Reko decompiler version 0.11.6.0.

#include "tmpq26h7gnf.h"

// 0000000100003574: void count_sheep()
// Called from:
//      main
void count_sheep()
{
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	puts();
}

// 0000000100003BF0: void short_multiplication_table()
// Called from:
//      main
void short_multiplication_table()
{
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
}

// tmpq26h7gnf_TEXT_stubs.c
// Generated by decompiling tmpq26h7gnf
// using Reko decompiler version 0.11.6.0.

#include "tmpq26h7gnf.h"

// 0000000100003E78: void printf()
// Called from:
//      count_sheep
//      short_multiplication_table
void printf()
{
	__imp__printf();
}

// 0000000100003E84: void puts()
// Called from:
//      count_sheep
void puts()
{
	__imp__puts();
}

// tmpq26h7gnf.globals.c
// Generated by decompiling tmpq26h7gnf
// using Reko decompiler version 0.11.6.0.

#include "tmpq26h7gnf.h"

<anonymous> * __imp__dyld_stub_binder; // 0000000000004000
<anonymous> * __imp__printf; // 0000000000008000
<anonymous> * __imp__puts; // 0000000000008008
