// tmpv57yc1vb_TEXT_text.c
// Generated by decompiling tmpv57yc1vb
// using Reko decompiler version 0.11.6.0.

#include "tmpv57yc1vb.h"

// 0000000100003B80: void all_badges()
// Called from:
//      main
void all_badges()
{
	printf();
}

// 0000000100003C20: void polynome_table()
// Called from:
//      main
void polynome_table()
{
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
}

// 0000000100003D60: void red_herring()
// Called from:
//      main
void red_herring()
{
	puts();
	printf();
	printf();
	printf();
	printf();
	printf();
}

// tmpv57yc1vb_TEXT_text_startup.c
// Generated by decompiling tmpv57yc1vb
// using Reko decompiler version 0.11.6.0.

#include "tmpv57yc1vb.h"

// 0000000100003E00: void main()
void main()
{
	all_badges();
	polynome_table();
	red_herring();
}

// tmpv57yc1vb_TEXT_stubs.c
// Generated by decompiling tmpv57yc1vb
// using Reko decompiler version 0.11.6.0.

#include "tmpv57yc1vb.h"

// 0000000100003E20: void printf()
// Called from:
//      all_badges
//      polynome_table
//      red_herring
void printf()
{
	__imp__printf();
}

// 0000000100003E2C: void puts()
// Called from:
//      red_herring
void puts()
{
	__imp__puts();
}

// tmpv57yc1vb.globals.c
// Generated by decompiling tmpv57yc1vb
// using Reko decompiler version 0.11.6.0.

#include "tmpv57yc1vb.h"

<anonymous> * __imp__dyld_stub_binder; // 0000000000004000
<anonymous> * __imp__printf; // 0000000000008000
<anonymous> * __imp__puts; // 0000000000008008
