// Generated by Rec Studio 4 - build Sep 23 2015

_all_badges()
{// addr = 0x0000000100000CB0
    goto ( *4294975488);
}

_polynome_table()
{// addr = 0x0000000100000D30
    __rbx = "P(%d) = %d\n";
    L1();
    L1();
    L1();
    L1();
    L1();
    L1();
    L1();
    L1();
    L1();
    L1();
    _pop(__rbx);
    goto ( *4294975488);
}

_red_herring()
{// addr = 0x0000000100000E20
    L0000000100000EA6();
    __rbx = " *  %d\n";
    L1();
    L1();
    L1();
    L1();
    _pop(__rbx);
    goto ( *4294975488);
}

_main(
    _unknown_ __rax                        // r53
)
{// addr = 0x0000000100000E80
    __rax = __rax;
    _all_badges();
    _polynome_table();
    _red_herring();
}

L0000000100000EA0()
{
    goto ( *4294975488);
}

L0000000100000EA6()
{
    goto ( *4294975496);
}

L0000000100000EA6()
{
    goto ( *4294975496);
}

// Statistics:
//       6 Register nodes
//       0 Temporaries nodes
//       0 Casts
//      28 Statements
//       0 Labels
//       0 Gotos
//       6 Blocks
//      67 Nodes
//       0 Assembly nodes
//       1 Unknown Types


Total time: 0 seconds.
