// tmpl1tu5hcf_TEXT_text.c
// Generated by decompiling tmpl1tu5hcf
// using Reko decompiler version 0.11.6.0.

#include "tmpl1tu5hcf.h"

// 0000000100003540: void count_sheep()
// Called from:
//      main
void count_sheep()
{
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	puts();
}

// 0000000100003BC0: void short_multiplication_table()
// Called from:
//      main
void short_multiplication_table()
{
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
}

// tmpl1tu5hcf_TEXT_text_startup.c
// Generated by decompiling tmpl1tu5hcf
// using Reko decompiler version 0.11.6.0.

#include "tmpl1tu5hcf.h"

// 0000000100003E40: void main()
void main()
{
	short_multiplication_table();
	count_sheep();
}

// tmpl1tu5hcf.globals.c
// Generated by decompiling tmpl1tu5hcf
// using Reko decompiler version 0.11.6.0.

#include "tmpl1tu5hcf.h"

<anonymous> * __imp__dyld_stub_binder; // 0000000000004000
<anonymous> * __imp__printf; // 0000000000008000
<anonymous> * __imp__puts; // 0000000000008008
// tmpl1tu5hcf_TEXT_stubs.c
// Generated by decompiling tmpl1tu5hcf
// using Reko decompiler version 0.11.6.0.

#include "tmpl1tu5hcf.h"

// 0000000100003E60: void printf()
// Called from:
//      count_sheep
//      short_multiplication_table
void printf()
{
	__imp__printf();
}

// 0000000100003E6C: void puts()
// Called from:
//      count_sheep
void puts()
{
	__imp__puts();
}

