// tmp61r6hv6n_text.c
// Generated by decompiling tmp61r6hv6n
// using Reko decompiler version 0.11.6.0.

#include "tmp61r6hv6n.h"

// 00001060: void _start()
void _start()
{
	ptr32 fp;
	__align_stack<word32>(fp + 4);
	__libc_start_main(&g_t6FF4);
	__halt();
}

// 00001090: void __x86.get_pc_thunk.bx()
void __x86.get_pc_thunk.bx()
{
}

// 000010A0: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
	if (0x7188 == 0x7188)
		return;
	<anonymous> * eax_11 = g_ptr6FE0;
	if (eax_11 == null)
		return;
	eax_11();
}

// 000010E0: void register_tm_clones()
// Called from:
//      frame_dummy
void register_tm_clones()
{
	Eq_40 eax_16 = 0x7188 - 0x7188;
	Eq_46 eax_20 = (eax_16 >> 0x1F) + (eax_16 >> 0x02);
	if (eax_20 >> 0x01 != 0x00)
	{
		<anonymous> * edx_25 = g_ptr6FF0;
		if (edx_25 != null)
			edx_25();
	}
}

// 00001130: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	if (g_b7187 == 0x00)
	{
		if (__cxa_finalize_GOT != 0x00)
			fn00001050(&g_t6FF4);
		deregister_tm_clones();
		g_b7187 = 0x01;
	}
}

// 00001180: void frame_dummy()
void frame_dummy()
{
	register_tm_clones();
}

// 00001189: void __x86.get_pc_thunk.dx()
void __x86.get_pc_thunk.dx()
{
}

// 0000118D: void multiplication_table()
// Called from:
//      main
void multiplication_table()
{
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
	printf(&g_t6FF4);
}

// 0000130D: void decrypt_message()
// Called from:
//      main
void decrypt_message()
{
	int32 edx_266 = (word32) g_b7080;
	ptr32 fp;
	*((word32) (fp - 0x010C) + edx_266) = (ptr32) 0x00;
	int32 ecx_279 = (word32) (g_b7081 + 0x01 + (byte) edx_266);
	byte dl_283 = (byte) *((word32) (fp - 0x010C) + ecx_279);
	(fp - 0x010C)[ecx_279] = 0x01;
	int32 edx_293 = (word32) (g_b7082 + 0x02 + (byte) ecx_279);
	byte cl_297 = (byte) *((word32) (fp - 0x010C) + edx_293);
	(fp - 0x010C)[edx_293] = 0x02;
	int32 ecx_307 = (word32) (g_b7083 + 0x03 + (byte) edx_293);
	byte dl_311 = (byte) *((word32) (fp - 0x010C) + ecx_307);
	(fp - 0x010C)[ecx_307] = 0x03;
	int32 edx_321 = (word32) (g_b7084 + 0x04 + (byte) ecx_307);
	byte cl_325 = (byte) *((word32) (fp - 0x010C) + edx_321);
	(fp - 0x010C)[edx_321] = 0x04;
	int32 ecx_335 = (word32) (g_b7085 + 0x05 + (byte) edx_321);
	byte dl_339 = (byte) *((word32) (fp - 0x010C) + ecx_335);
	(fp - 0x010C)[ecx_335] = 0x05;
	int32 edx_349 = (word32) (g_b7086 + 0x06 + (byte) ecx_335);
	byte cl_353 = (byte) *((word32) (fp - 0x010C) + edx_349);
	(fp - 0x010C)[edx_349] = 0x06;
	int32 ecx_363 = (word32) (g_b7087 + 0x07 + (byte) edx_349);
	byte dl_367 = (byte) *((word32) (fp - 0x010C) + ecx_363);
	(fp - 0x010C)[ecx_363] = 0x07;
	int32 edx_377 = (word32) (g_b7088 + 0x08 + (byte) ecx_363);
	byte cl_381 = (byte) *((word32) (fp - 0x010C) + edx_377);
	(fp - 0x010C)[edx_377] = 0x08;
	int32 ecx_391 = (word32) (g_b7089 + 0x09 + (byte) edx_377);
	byte dl_395 = (byte) *((word32) (fp - 0x010C) + ecx_391);
	(fp - 0x010C)[ecx_391] = 0x09;
	int32 edx_405 = (word32) (g_b708A + 0x0A + (byte) ecx_391);
	byte cl_409 = (byte) *((word32) (fp - 0x010C) + edx_405);
	(fp - 0x010C)[edx_405] = 0x0A;
	int32 ecx_419 = (word32) (g_b708B + 11 + (byte) edx_405);
	byte dl_423 = (byte) *((word32) (fp - 0x010C) + ecx_419);
	(fp - 0x010C)[ecx_419] = 11;
	int32 edx_433 = (word32) (g_b708C + 0x0C + (byte) ecx_419);
	byte cl_437 = (byte) *((word32) (fp - 0x010C) + edx_433);
	(fp - 0x010C)[edx_433] = 0x0C;
	int32 ecx_447 = (word32) (g_b708D + 0x0D + (byte) edx_433);
	byte dl_451 = (byte) *((word32) (fp - 0x010C) + ecx_447);
	(fp - 0x010C)[ecx_447] = 0x0D;
	int32 edx_461 = (word32) (g_b708E + 0x0E + (byte) ecx_447);
	byte cl_465 = (byte) *((word32) (fp - 0x010C) + edx_461);
	(fp - 0x010C)[edx_461] = 0x0E;
	int32 ecx_475 = (word32) (g_b708F + 0x0F + (byte) edx_461);
	byte dl_479 = (byte) *((word32) (fp - 0x010C) + ecx_475);
	(fp - 0x010C)[ecx_475] = 0x0F;
	int32 edx_489 = (word32) (g_b7090 + 0x10 + (byte) ecx_475);
	byte cl_493 = (byte) *((word32) (fp - 0x010C) + edx_489);
	(fp - 0x010C)[edx_489] = 0x10;
	int32 ecx_503 = (word32) (g_b7091 + 0x11 + (byte) edx_489);
	byte dl_507 = (byte) *((word32) (fp - 0x010C) + ecx_503);
	(fp - 0x010C)[ecx_503] = 0x11;
	int32 edx_517 = (word32) (g_b7092 + 0x12 + (byte) ecx_503);
	byte cl_521 = (byte) *((word32) (fp - 0x010C) + edx_517);
	(fp - 0x010C)[edx_517] = 0x12;
	int32 ecx_531 = (word32) (g_b7093 + 0x13 + (byte) edx_517);
	byte dl_535 = (byte) *((word32) (fp - 0x010C) + ecx_531);
	(fp - 0x010C)[ecx_531] = 0x13;
	int32 edx_545 = (word32) (g_b7094 + 0x14 + (byte) ecx_531);
	byte cl_549 = (byte) *((word32) (fp - 0x010C) + edx_545);
	(fp - 0x010C)[edx_545] = 0x14;
	int32 ecx_559 = (word32) (g_b7095 + 0x15 + (byte) edx_545);
	byte dl_563 = (byte) *((word32) (fp - 0x010C) + ecx_559);
	(fp - 0x010C)[ecx_559] = 0x15;
	int32 edx_573 = (word32) (g_b7096 + 22 + (byte) ecx_559);
	byte cl_577 = (byte) *((word32) (fp - 0x010C) + edx_573);
	(fp - 0x010C)[edx_573] = 22;
	int32 ecx_587 = (word32) (g_b7097 + 0x17 + (byte) edx_573);
	byte dl_591 = (byte) *((word32) (fp - 0x010C) + ecx_587);
	(fp - 0x010C)[ecx_587] = 0x17;
	int32 edx_601 = (word32) (g_b7098 + 0x18 + (byte) ecx_587);
	byte cl_605 = (byte) *((word32) (fp - 0x010C) + edx_601);
	(fp - 0x010C)[edx_601] = 0x18;
	int32 ecx_615 = (word32) (g_b7099 + 0x19 + (byte) edx_601);
	byte dl_619 = (byte) *((word32) (fp - 0x010C) + ecx_615);
	(fp - 0x010C)[ecx_615] = 0x19;
	int32 edx_629 = (word32) (g_b709A + 0x1A + (byte) ecx_615);
	byte cl_633 = (byte) *((word32) (fp - 0x010C) + edx_629);
	(fp - 0x010C)[edx_629] = 0x1A;
	int32 ecx_643 = (word32) (g_b709B + 0x1B + (byte) edx_629);
	byte dl_647 = (byte) *((word32) (fp - 0x010C) + ecx_643);
	(fp - 0x010C)[ecx_643] = 0x1B;
	int32 edx_657 = (word32) (g_b709C + 0x1C + (byte) ecx_643);
	byte cl_661 = (byte) *((word32) (fp - 0x010C) + edx_657);
	(fp - 0x010C)[edx_657] = 0x1C;
	int32 ecx_671 = (word32) (g_b709D + 0x1D + (byte) edx_657);
	byte dl_675 = (byte) *((word32) (fp - 0x010C) + ecx_671);
	(fp - 0x010C)[ecx_671] = 0x1D;
	int32 edx_685 = (word32) (g_b709E + 0x1E + (byte) ecx_671);
	byte cl_689 = (byte) *((word32) (fp - 0x010C) + edx_685);
	(fp - 0x010C)[edx_685] = 0x1E;
	int32 ecx_699 = (word32) (g_b709F + 0x1F + (byte) edx_685);
	byte dl_703 = (byte) *((word32) (fp - 0x010C) + ecx_699);
	(fp - 0x010C)[ecx_699] = 0x1F;
	int32 edx_713 = (word32) (g_b70A0 + 0x20 + (byte) ecx_699);
	byte cl_717 = (byte) *((word32) (fp - 0x010C) + edx_713);
	(fp - 0x010C)[edx_713] = 0x20;
	int32 ecx_727 = (word32) (g_b70A1 + 33 + (byte) edx_713);
	byte dl_731 = (byte) *((word32) (fp - 0x010C) + ecx_727);
	(fp - 0x010C)[ecx_727] = 33;
	int32 edx_741 = (word32) (g_b70A2 + 0x22 + (byte) ecx_727);
	byte cl_745 = (byte) *((word32) (fp - 0x010C) + edx_741);
	(fp - 0x010C)[edx_741] = 0x22;
	int32 ecx_755 = (word32) (g_b70A3 + 0x23 + (byte) edx_741);
	byte dl_759 = (byte) *((word32) (fp - 0x010C) + ecx_755);
	(fp - 0x010C)[ecx_755] = 0x23;
	int32 edx_769 = (word32) (g_b70A4 + 0x24 + (byte) ecx_755);
	byte cl_773 = (byte) *((word32) (fp - 0x010C) + edx_769);
	(fp - 0x010C)[edx_769] = 0x24;
	int32 ecx_783 = (word32) (g_b70A5 + 0x25 + (byte) edx_769);
	byte dl_787 = (byte) *((word32) (fp - 0x010C) + ecx_783);
	(fp - 0x010C)[ecx_783] = 0x25;
	int32 edx_797 = (word32) (g_b70A6 + 0x26 + (byte) ecx_783);
	byte cl_801 = (byte) *((word32) (fp - 0x010C) + edx_797);
	(fp - 0x010C)[edx_797] = 0x26;
	int32 ecx_811 = (word32) (g_b70A7 + 0x27 + (byte) edx_797);
	byte dl_815 = (byte) *((word32) (fp - 0x010C) + ecx_811);
	(fp - 0x010C)[ecx_811] = 0x27;
	int32 edx_825 = (word32) (g_b70A8 + 0x28 + (byte) ecx_811);
	byte cl_829 = (byte) *((word32) (fp - 0x010C) + edx_825);
	(fp - 0x010C)[edx_825] = 0x28;
	int32 ecx_839 = (word32) (g_b70A9 + 0x29 + (byte) edx_825);
	byte dl_843 = (byte) *((word32) (fp - 0x010C) + ecx_839);
	(fp - 0x010C)[ecx_839] = 0x29;
	int32 edx_853 = (word32) (g_b70AA + 0x2A + (byte) ecx_839);
	byte cl_857 = (byte) *((word32) (fp - 0x010C) + edx_853);
	(fp - 0x010C)[edx_853] = 0x2A;
	int32 ecx_867 = (word32) (g_b70AB + 0x2B + (byte) edx_853);
	byte dl_871 = (byte) *((word32) (fp - 0x010C) + ecx_867);
	(fp - 0x010C)[ecx_867] = 0x2B;
	int32 edx_881 = (word32) (g_b70AC + 44 + (byte) ecx_867);
	byte cl_885 = (byte) *((word32) (fp - 0x010C) + edx_881);
	(fp - 0x010C)[edx_881] = 44;
	int32 ecx_895 = (word32) (g_b70AD + 0x2D + (byte) edx_881);
	byte dl_899 = (byte) *((word32) (fp - 0x010C) + ecx_895);
	(fp - 0x010C)[ecx_895] = 0x2D;
	int32 edx_909 = (word32) (g_b70AE + 0x2E + (byte) ecx_895);
	byte cl_913 = (byte) *((word32) (fp - 0x010C) + edx_909);
	(fp - 0x010C)[edx_909] = 0x2E;
	int32 ecx_923 = (word32) (g_b70AF + 0x2F + (byte) edx_909);
	byte dl_927 = (byte) *((word32) (fp - 0x010C) + ecx_923);
	(fp - 0x010C)[ecx_923] = 0x2F;
	int32 edx_937 = (word32) (g_b70B0 + 0x30 + (byte) ecx_923);
	byte cl_941 = (byte) *((word32) (fp - 0x010C) + edx_937);
	(fp - 0x010C)[edx_937] = 0x30;
	int32 ecx_951 = (word32) (g_b70B1 + 0x31 + (byte) edx_937);
	byte dl_955 = (byte) *((word32) (fp - 0x010C) + ecx_951);
	(fp - 0x010C)[ecx_951] = 0x31;
	int32 edx_965 = (word32) (g_b70B2 + 0x32 + (byte) ecx_951);
	byte cl_969 = (byte) *((word32) (fp - 0x010C) + edx_965);
	(fp - 0x010C)[edx_965] = 0x32;
	int32 ecx_979 = (word32) (g_b70B3 + 0x33 + (byte) edx_965);
	byte dl_983 = (byte) *((word32) (fp - 0x010C) + ecx_979);
	(fp - 0x010C)[ecx_979] = 0x33;
	int32 edx_993 = (word32) (g_b70B4 + 0x34 + (byte) ecx_979);
	byte cl_997 = (byte) *((word32) (fp - 0x010C) + edx_993);
	(fp - 0x010C)[edx_993] = 0x34;
	int32 ecx_1007 = (word32) (g_b70B5 + 0x35 + (byte) edx_993);
	byte dl_1011 = (byte) *((word32) (fp - 0x010C) + ecx_1007);
	(fp - 0x010C)[ecx_1007] = 0x35;
	int32 edx_1021 = (word32) (g_b70B6 + 0x36 + (byte) ecx_1007);
	byte cl_1025 = (byte) *((word32) (fp - 0x010C) + edx_1021);
	(fp - 0x010C)[edx_1021] = 0x36;
	int32 ecx_1035 = (word32) (g_b70B7 + 55 + (byte) edx_1021);
	byte dl_1039 = (byte) *((word32) (fp - 0x010C) + ecx_1035);
	(fp - 0x010C)[ecx_1035] = 55;
	int32 edx_1049 = (word32) (g_b70B8 + 0x38 + (byte) ecx_1035);
	byte cl_1053 = (byte) *((word32) (fp - 0x010C) + edx_1049);
	(fp - 0x010C)[edx_1049] = 0x38;
	int32 ecx_1063 = (word32) (g_b70B9 + 0x39 + (byte) edx_1049);
	byte dl_1067 = (byte) *((word32) (fp - 0x010C) + ecx_1063);
	(fp - 0x010C)[ecx_1063] = 0x39;
	int32 edx_1077 = (word32) (g_b70BA + 0x3A + (byte) ecx_1063);
	byte cl_1081 = (byte) *((word32) (fp - 0x010C) + edx_1077);
	(fp - 0x010C)[edx_1077] = 0x3A;
	int32 ecx_1091 = (word32) (g_b70BB + 0x3B + (byte) edx_1077);
	byte dl_1095 = (byte) *((word32) (fp - 0x010C) + ecx_1091);
	(fp - 0x010C)[ecx_1091] = 0x3B;
	int32 edx_1105 = (word32) (g_b70BC + 0x3C + (byte) ecx_1091);
	byte cl_1109 = (byte) *((word32) (fp - 0x010C) + edx_1105);
	(fp - 0x010C)[edx_1105] = 0x3C;
	int32 ecx_1119 = (word32) (g_b70BD + 0x3D + (byte) edx_1105);
	byte dl_1123 = (byte) *((word32) (fp - 0x010C) + ecx_1119);
	(fp - 0x010C)[ecx_1119] = 0x3D;
	int32 edx_1133 = (word32) (g_b70BE + 0x3E + (byte) ecx_1119);
	byte cl_1137 = (byte) *((word32) (fp - 0x010C) + edx_1133);
	(fp - 0x010C)[edx_1133] = 0x3E;
	int32 ecx_1147 = (word32) (g_b70BF + 0x3F + (byte) edx_1133);
	*((word32) (fp - 0x010C) + ecx_1147) = (ptr32) 0x3F;
	int32 edx_1161 = (word32) (g_b70C0 + 0x40 + (byte) ecx_1147);
	*((word32) (fp - 0x010C) + edx_1161) = (ptr32) 0x40;
	int32 ecx_1175 = (word32) (g_b70C1 + 0x41 + (byte) edx_1161);
	*((word32) (fp - 0x010C) + ecx_1175) = (ptr32) 0x41;
	int32 edx_1189 = (word32) (g_b70C2 + 66 + (byte) ecx_1175);
	*((word32) (fp - 0x010C) + edx_1189) = (ptr32) 66;
	int32 ecx_1203 = (word32) (g_b70C3 + 0x43 + (byte) edx_1189);
	*((word32) (fp - 0x010C) + ecx_1203) = (ptr32) 0x43;
	int32 edx_1217 = (word32) (g_b70C4 + 0x44 + (byte) ecx_1203);
	*((word32) (fp - 0x010C) + edx_1217) = (ptr32) 0x44;
	int32 ecx_1231 = (word32) (g_b70C5 + 0x45 + (byte) edx_1217);
	*((word32) (fp - 0x010C) + ecx_1231) = (ptr32) 0x45;
	int32 edx_1245 = (word32) (g_b70C6 + 0x46 + (byte) ecx_1231);
	*((word32) (fp - 0x010C) + edx_1245) = (ptr32) 0x46;
	int32 ecx_1259 = (word32) (g_b70C7 + 0x47 + (byte) edx_1245);
	*((word32) (fp - 0x010C) + ecx_1259) = (ptr32) 0x47;
	int32 edx_1273 = (word32) (g_b70C8 + 0x48 + (byte) ecx_1259);
	*((word32) (fp - 0x010C) + edx_1273) = (ptr32) 0x48;
	int32 ecx_1287 = (word32) (g_b70C9 + 0x49 + (byte) edx_1273);
	*((word32) (fp - 0x010C) + ecx_1287) = (ptr32) 0x49;
	int32 edx_1301 = (word32) (g_b70CA + 0x4A + (byte) ecx_1287);
	*((word32) (fp - 0x010C) + edx_1301) = (ptr32) 0x4A;
	int32 ecx_1315 = (word32) (g_b70CB + 0x4B + (byte) edx_1301);
	*((word32) (fp - 0x010C) + ecx_1315) = (ptr32) 0x4B;
	int32 edx_1329 = (word32) (g_b70CC + 0x4C + (byte) ecx_1315);
	*((word32) (fp - 0x010C) + edx_1329) = (ptr32) 0x4C;
	int32 ecx_1343 = (word32) (g_b70CD + 77 + (byte) edx_1329);
	*((word32) (fp - 0x010C) + ecx_1343) = (ptr32) 77;
	int32 edx_1357 = (word32) (g_b70CE + 0x4E + (byte) ecx_1343);
	*((word32) (fp - 0x010C) + edx_1357) = (ptr32) 0x4E;
	int32 ecx_1371 = (word32) (g_b70CF + 0x4F + (byte) edx_1357);
	*((word32) (fp - 0x010C) + ecx_1371) = (ptr32) 0x4F;
	int32 edx_1385 = (word32) (g_b70D0 + 0x50 + (byte) ecx_1371);
	*((word32) (fp - 0x010C) + edx_1385) = (ptr32) 0x50;
	int32 ecx_1399 = (word32) (g_b70D1 + 0x51 + (byte) edx_1385);
	*((word32) (fp - 0x010C) + ecx_1399) = (ptr32) 0x51;
	int32 edx_1413 = (word32) (g_b70D2 + 0x52 + (byte) ecx_1399);
	*((word32) (fp - 0x010C) + edx_1413) = (ptr32) 0x52;
	int32 ecx_1427 = (word32) (g_b70D3 + 0x53 + (byte) edx_1413);
	*((word32) (fp - 0x010C) + ecx_1427) = (ptr32) 0x53;
	int32 edx_1441 = (word32) (g_b70D4 + 0x54 + (byte) ecx_1427);
	*((word32) (fp - 0x010C) + edx_1441) = (ptr32) 0x54;
	int32 ecx_1455 = (word32) (g_b70D5 + 0x55 + (byte) edx_1441);
	*((word32) (fp - 0x010C) + ecx_1455) = (ptr32) 0x55;
	int32 edx_1469 = (word32) (g_b70D6 + 0x56 + (byte) ecx_1455);
	*((word32) (fp - 0x010C) + edx_1469) = (ptr32) 0x56;
	int32 ecx_1483 = (word32) (g_b70D7 + 0x57 + (byte) edx_1469);
	*((word32) (fp - 0x010C) + ecx_1483) = (ptr32) 0x57;
	int32 edx_1497 = (word32) (g_b70D8 + 88 + (byte) ecx_1483);
	*((word32) (fp - 0x010C) + edx_1497) = (ptr32) 88;
	int32 ecx_1511 = (word32) (g_b70D9 + 0x59 + (byte) edx_1497);
	*((word32) (fp - 0x010C) + ecx_1511) = (ptr32) 0x59;
	int32 edx_1525 = (word32) (g_b70DA + 0x5A + (byte) ecx_1511);
	*((word32) (fp - 0x010C) + edx_1525) = (ptr32) 0x5A;
	int32 ecx_1539 = (word32) (g_b70DB + 0x5B + (byte) edx_1525);
	*((word32) (fp - 0x010C) + ecx_1539) = (ptr32) 0x5B;
	int32 edx_1553 = (word32) (g_b70DC + 0x5C + (byte) ecx_1539);
	*((word32) (fp - 0x010C) + edx_1553) = (ptr32) 0x5C;
	int32 ecx_1567 = (word32) (g_b70DD + 0x5D + (byte) edx_1553);
	*((word32) (fp - 0x010C) + ecx_1567) = (ptr32) 0x5D;
	int32 edx_1581 = (word32) (g_b70DE + 0x5E + (byte) ecx_1567);
	*((word32) (fp - 0x010C) + edx_1581) = (ptr32) 0x5E;
	int32 ecx_1595 = (word32) (g_b70DF + 0x5F + (byte) edx_1581);
	*((word32) (fp - 0x010C) + ecx_1595) = (ptr32) 0x5F;
	int32 edx_1609 = (word32) (g_b70E0 + 0x60 + (byte) ecx_1595);
	*((word32) (fp - 0x010C) + edx_1609) = (ptr32) 0x60;
	int32 ecx_1623 = (word32) (g_b70E1 + 0x61 + (byte) edx_1609);
	*((word32) (fp - 0x010C) + ecx_1623) = (ptr32) 0x61;
	int32 edx_1637 = (word32) (g_b70E2 + 0x62 + (byte) ecx_1623);
	*((word32) (fp - 0x010C) + edx_1637) = (ptr32) 0x62;
	int32 ecx_1651 = (word32) (g_b70E3 + 99 + (byte) edx_1637);
	*((word32) (fp - 0x010C) + ecx_1651) = (ptr32) 99;
	int32 edx_1665 = (word32) (g_b70E4 + 100 + (byte) ecx_1651);
	*((word32) (fp - 0x010C) + edx_1665) = (ptr32) 100;
	int32 ecx_1679 = (word32) (g_b70E5 + 101 + (byte) edx_1665);
	*((word32) (fp - 0x010C) + ecx_1679) = (ptr32) 101;
	int32 edx_1693 = (word32) (g_b70E6 + 0x66 + (byte) ecx_1679);
	*((word32) (fp - 0x010C) + edx_1693) = (ptr32) 0x66;
	int32 ecx_1707 = (word32) (g_b70E7 + 0x67 + (byte) edx_1693);
	*((word32) (fp - 0x010C) + ecx_1707) = (ptr32) 0x67;
	int32 edx_1721 = (word32) (g_b70E8 + 0x68 + (byte) ecx_1707);
	*((word32) (fp - 0x010C) + edx_1721) = (ptr32) 0x68;
	int32 ecx_1735 = (word32) (g_b70E9 + 0x69 + (byte) edx_1721);
	*((word32) (fp - 0x010C) + ecx_1735) = (ptr32) 0x69;
	int32 edx_1749 = (word32) (g_b70EA + 0x6A + (byte) ecx_1735);
	*((word32) (fp - 0x010C) + edx_1749) = (ptr32) 0x6A;
	int32 ecx_1763 = (word32) (g_b70EB + 0x6B + (byte) edx_1749);
	*((word32) (fp - 0x010C) + ecx_1763) = (ptr32) 0x6B;
	int32 edx_1777 = (word32) (g_b70EC + 0x6C + (byte) ecx_1763);
	*((word32) (fp - 0x010C) + edx_1777) = (ptr32) 0x6C;
	int32 ecx_1791 = (word32) (g_b70ED + 0x6D + (byte) edx_1777);
	*((word32) (fp - 0x010C) + ecx_1791) = (ptr32) 0x6D;
	int32 edx_1805 = (word32) (g_b70EE + 110 + (byte) ecx_1791);
	*((word32) (fp - 0x010C) + edx_1805) = (ptr32) 110;
	int32 ecx_1819 = (word32) (g_b70EF + 111 + (byte) edx_1805);
	*((word32) (fp - 0x010C) + ecx_1819) = (ptr32) 111;
	int32 edx_1833 = (word32) (g_b70F0 + 0x70 + (byte) ecx_1819);
	*((word32) (fp - 0x010C) + edx_1833) = (ptr32) 0x70;
	int32 ecx_1847 = (word32) (g_b70F1 + 113 + (byte) edx_1833);
	*((word32) (fp - 0x010C) + ecx_1847) = (ptr32) 113;
	int32 edx_1861 = (word32) (g_b70F2 + 114 + (byte) ecx_1847);
	*((word32) (fp - 0x010C) + edx_1861) = (ptr32) 114;
	int32 ecx_1875 = (word32) (g_b70F3 + 115 + (byte) edx_1861);
	*((word32) (fp - 0x010C) + ecx_1875) = (ptr32) 115;
	int32 edx_1889 = (word32) (g_b70F4 + 116 + (byte) ecx_1875);
	*((word32) (fp - 0x010C) + edx_1889) = (ptr32) 116;
	int32 ecx_1903 = (word32) (g_b70F5 + 117 + (byte) edx_1889);
	*((word32) (fp - 0x010C) + ecx_1903) = (ptr32) 117;
	int32 edx_1917 = (word32) (g_b70F6 + 118 + (byte) ecx_1903);
	*((word32) (fp - 0x010C) + edx_1917) = (ptr32) 118;
	int32 ecx_1931 = (word32) (g_b70F7 + 0x77 + (byte) edx_1917);
	*((word32) (fp - 0x010C) + ecx_1931) = (ptr32) 0x77;
	int32 edx_1945 = (word32) (g_b70F8 + 0x78 + (byte) ecx_1931);
	*((word32) (fp - 0x010C) + edx_1945) = (ptr32) 0x78;
	int32 ecx_1959 = (word32) (g_b70F9 + 121 + (byte) edx_1945);
	*((word32) (fp - 0x010C) + ecx_1959) = (ptr32) 121;
	int32 edx_1973 = (word32) (g_b70FA + 122 + (byte) ecx_1959);
	*((word32) (fp - 0x010C) + edx_1973) = (ptr32) 122;
	int32 ecx_1987 = (word32) (g_b70FB + 0x7B + (byte) edx_1973);
	*((word32) (fp - 0x010C) + ecx_1987) = (ptr32) 0x7B;
	int32 edx_2001 = (word32) (g_b70FC + 0x7C + (byte) ecx_1987);
	*((word32) (fp - 0x010C) + edx_2001) = (ptr32) 0x7C;
	int32 ecx_2015 = (word32) (g_b70FD + 0x7D + (byte) edx_2001);
	*((word32) (fp - 0x010C) + ecx_2015) = (ptr32) 0x7D;
	int32 edx_2029 = (word32) (g_b70FE + 0x7E + (byte) ecx_2015);
	*((word32) (fp - 0x010C) + edx_2029) = (ptr32) 0x7E;
	int32 ecx_2043 = (word32) (g_b70FF + 0x7F + (byte) edx_2029);
	*((word32) (fp - 0x010C) + ecx_2043) = (ptr32) 0x7F;
	int32 edx_2057 = (word32) (g_b7100 + 0x80 + (byte) ecx_2043);
	*((word32) (fp - 0x010C) + edx_2057) = (ptr32) 0x80;
	int32 ecx_2071 = (word32) (g_b7101 + 0x81 + (byte) edx_2057);
	*((word32) (fp - 0x010C) + ecx_2071) = (ptr32) 0x81;
	int32 edx_2085 = (word32) (g_b7102 + 0x82 + (byte) ecx_2071);
	*((word32) (fp - 0x010C) + edx_2085) = (ptr32) 0x82;
	int32 ecx_2099 = (word32) (g_b7103 + 131 + (byte) edx_2085);
	*((word32) (fp - 0x010C) + ecx_2099) = (ptr32) 131;
	int32 edx_2113 = (word32) (g_b7104 + 0x84 + (byte) ecx_2099);
	*((word32) (fp - 0x010C) + edx_2113) = (ptr32) 0x84;
	int32 ecx_2127 = (word32) (g_b7105 + 133 + (byte) edx_2113);
	*((word32) (fp - 0x010C) + ecx_2127) = (ptr32) 133;
	int32 edx_2141 = (word32) (g_b7106 + 0x86 + (byte) ecx_2127);
	*((word32) (fp - 0x010C) + edx_2141) = (ptr32) 0x86;
	int32 ecx_2155 = (word32) (g_b7107 + 0x87 + (byte) edx_2141);
	*((word32) (fp - 0x010C) + ecx_2155) = (ptr32) 0x87;
	int32 edx_2169 = (word32) (g_b7108 + 0x88 + (byte) ecx_2155);
	*((word32) (fp - 0x010C) + edx_2169) = (ptr32) 0x88;
	int32 ecx_2183 = (word32) (g_b7109 + 0x89 + (byte) edx_2169);
	*((word32) (fp - 0x010C) + ecx_2183) = (ptr32) 0x89;
	int32 edx_2197 = (word32) (g_b710A + 0x8A + (byte) ecx_2183);
	*((word32) (fp - 0x010C) + edx_2197) = (ptr32) 0x8A;
	int32 ecx_2211 = (word32) (g_b710B + 0x8B + (byte) edx_2197);
	*((word32) (fp - 0x010C) + ecx_2211) = (ptr32) 0x8B;
	int32 edx_2225 = (word32) (g_b710C + 0x8C + (byte) ecx_2211);
	*((word32) (fp - 0x010C) + edx_2225) = (ptr32) 0x8C;
	int32 ecx_2239 = (word32) (g_b710D + 141 + (byte) edx_2225);
	*((word32) (fp - 0x010C) + ecx_2239) = (ptr32) 141;
	int32 edx_2253 = (word32) (g_b710E + 0x8E + (byte) ecx_2239);
	*((word32) (fp - 0x010C) + edx_2253) = (ptr32) 0x8E;
	int32 ecx_2267 = (word32) (g_b710F + ~0x70 + (byte) edx_2253);
	*((word32) (fp - 0x010C) + ecx_2267) = (ptr32) ~0x70;
	int32 edx_2281 = (word32) (g_b7110 + 0x90 + (byte) ecx_2267);
	*((word32) (fp - 0x010C) + edx_2281) = (ptr32) 0x90;
	int32 ecx_2295 = (word32) (g_b7111 + 0x91 + (byte) edx_2281);
	*((word32) (fp - 0x010C) + ecx_2295) = (ptr32) 0x91;
	int32 edx_2309 = (word32) (g_b7112 + 0x92 + (byte) ecx_2295);
	*((word32) (fp - 0x010C) + edx_2309) = (ptr32) 0x92;
	int32 ecx_2323 = (word32) (g_b7113 + 0x93 + (byte) edx_2309);
	*((word32) (fp - 0x010C) + ecx_2323) = (ptr32) 0x93;
	int32 edx_2337 = (word32) (g_b7114 + 0x94 + (byte) ecx_2323);
	*((word32) (fp - 0x010C) + edx_2337) = (ptr32) 0x94;
	int32 ecx_2351 = (word32) (g_b7115 + 0x95 + (byte) edx_2337);
	*((word32) (fp - 0x010C) + ecx_2351) = (ptr32) 0x95;
	int32 edx_2365 = (word32) (g_b7116 + 0x96 + (byte) ecx_2351);
	*((word32) (fp - 0x010C) + edx_2365) = (ptr32) 0x96;
	int32 ecx_2379 = (word32) (g_b7117 + 151 + (byte) edx_2365);
	*((word32) (fp - 0x010C) + ecx_2379) = (ptr32) 151;
	int32 edx_2393 = (word32) (g_b7118 + 0x98 + (byte) ecx_2379);
	*((word32) (fp - 0x010C) + edx_2393) = (ptr32) 0x98;
	int32 ecx_2407 = (word32) (g_b7119 + 0x99 + (byte) edx_2393);
	*((word32) (fp - 0x010C) + ecx_2407) = (ptr32) 0x99;
	int32 edx_2421 = (word32) (g_b711A + 0x9A + (byte) ecx_2407);
	*((word32) (fp - 0x010C) + edx_2421) = (ptr32) 0x9A;
	int32 ecx_2435 = (word32) (g_b711B + 155 + (byte) edx_2421);
	*((word32) (fp - 0x010C) + ecx_2435) = (ptr32) 155;
	int32 edx_2449 = (word32) (g_b711C + 0x9C + (byte) ecx_2435);
	*((word32) (fp - 0x010C) + edx_2449) = (ptr32) 0x9C;
	int32 ecx_2463 = (word32) (g_b711D + ~0x62 + (byte) edx_2449);
	*((word32) (fp - 0x010C) + ecx_2463) = (ptr32) ~0x62;
	int32 edx_2477 = (word32) (g_b711E + ~0x61 + (byte) ecx_2463);
	*((word32) (fp - 0x010C) + edx_2477) = (ptr32) ~0x61;
	int32 ecx_2491 = (word32) (g_b711F + ~0x60 + (byte) edx_2477);
	*((word32) (fp - 0x010C) + ecx_2491) = (ptr32) ~0x60;
	int32 edx_2505 = (word32) (g_b7120 + 0xA0 + (byte) ecx_2491);
	*((word32) (fp - 0x010C) + edx_2505) = (ptr32) 0xA0;
	int32 ecx_2519 = (word32) (g_b7121 + 161 + (byte) edx_2505);
	*((word32) (fp - 0x010C) + ecx_2519) = (ptr32) 161;
	int32 edx_2533 = (word32) (g_b7122 + 0xA2 + (byte) ecx_2519);
	*((word32) (fp - 0x010C) + edx_2533) = (ptr32) 0xA2;
	int32 ecx_2547 = (word32) (g_b7123 + 0xA3 + (byte) edx_2533);
	*((word32) (fp - 0x010C) + ecx_2547) = (ptr32) 0xA3;
	int32 edx_2561 = (word32) (g_b7124 + 0xA4 + (byte) ecx_2547);
	*((word32) (fp - 0x010C) + edx_2561) = (ptr32) 0xA4;
	int32 ecx_2575 = (word32) (g_b7125 + 0xA5 + (byte) edx_2561);
	*((word32) (fp - 0x010C) + ecx_2575) = (ptr32) 0xA5;
	int32 edx_2589 = (word32) (g_b7126 + 166 + (byte) ecx_2575);
	*((word32) (fp - 0x010C) + edx_2589) = (ptr32) 166;
	int32 ecx_2603 = (word32) (g_b7127 + ~0x58 + (byte) edx_2589);
	*((word32) (fp - 0x010C) + ecx_2603) = (ptr32) ~0x58;
	int32 edx_2617 = (word32) (g_b7128 + 0xA8 + (byte) ecx_2603);
	*((word32) (fp - 0x010C) + edx_2617) = (ptr32) 0xA8;
	int32 ecx_2631 = (word32) (g_b7129 + 0xA9 + (byte) edx_2617);
	*((word32) (fp - 0x010C) + ecx_2631) = (ptr32) 0xA9;
	int32 edx_2645 = (word32) (g_b712A + 0xAA + (byte) ecx_2631);
	*((word32) (fp - 0x010C) + edx_2645) = (ptr32) 0xAA;
	int32 ecx_2659 = (word32) (g_b712B + 171 + (byte) edx_2645);
	*((word32) (fp - 0x010C) + ecx_2659) = (ptr32) 171;
	int32 edx_2673 = (word32) (g_b712C + 0xAC + (byte) ecx_2659);
	*((word32) (fp - 0x010C) + edx_2673) = (ptr32) 0xAC;
	int32 ecx_2687 = (word32) (g_b712D + ~0x52 + (byte) edx_2673);
	*((word32) (fp - 0x010C) + ecx_2687) = (ptr32) ~0x52;
	int32 edx_2701 = (word32) (g_b712E + ~0x51 + (byte) ecx_2687);
	*((word32) (fp - 0x010C) + edx_2701) = (ptr32) ~0x51;
	int32 ecx_2715 = (word32) (g_b712F + ~0x50 + (byte) edx_2701);
	*((word32) (fp - 0x010C) + ecx_2715) = (ptr32) ~0x50;
	int32 edx_2729 = (word32) (g_b7130 + 0xB0 + (byte) ecx_2715);
	*((word32) (fp - 0x010C) + edx_2729) = (ptr32) 0xB0;
	int32 ecx_2743 = (word32) (g_b7131 + 177 + (byte) edx_2729);
	*((word32) (fp - 0x010C) + ecx_2743) = (ptr32) 177;
	int32 edx_2757 = (word32) (g_b7132 + 0xB2 + (byte) ecx_2743);
	*((word32) (fp - 0x010C) + edx_2757) = (ptr32) 0xB2;
	int32 ecx_2771 = (word32) (g_b7133 + ~0x4C + (byte) edx_2757);
	*((word32) (fp - 0x010C) + ecx_2771) = (ptr32) ~0x4C;
	int32 edx_2785 = (word32) (g_b7134 + 0xB4 + (byte) ecx_2771);
	*((word32) (fp - 0x010C) + edx_2785) = (ptr32) 0xB4;
	int32 ecx_2799 = (word32) (g_b7135 + 181 + (byte) edx_2785);
	*((word32) (fp - 0x010C) + ecx_2799) = (ptr32) 181;
	int32 edx_2813 = (word32) (g_b7136 + ~0x49 + (byte) ecx_2799);
	*((word32) (fp - 0x010C) + edx_2813) = (ptr32) ~0x49;
	int32 ecx_2827 = (word32) (g_b7137 + ~0x48 + (byte) edx_2813);
	*((word32) (fp - 0x010C) + ecx_2827) = (ptr32) ~0x48;
	int32 edx_2841 = (word32) (g_b7138 + 0xB8 + (byte) ecx_2827);
	*((word32) (fp - 0x010C) + edx_2841) = (ptr32) 0xB8;
	int32 ecx_2855 = (word32) (g_b7139 + ~0x46 + (byte) edx_2841);
	*((word32) (fp - 0x010C) + ecx_2855) = (ptr32) ~0x46;
	int32 edx_2869 = (word32) (g_b713A + ~0x45 + (byte) ecx_2855);
	*((word32) (fp - 0x010C) + edx_2869) = (ptr32) ~0x45;
	int32 ecx_2883 = (word32) (g_b713B + ~0x44 + (byte) edx_2869);
	*((word32) (fp - 0x010C) + ecx_2883) = (ptr32) ~0x44;
	int32 edx_2897 = (word32) (g_b713C + 188 + (byte) ecx_2883);
	*((word32) (fp - 0x010C) + edx_2897) = (ptr32) 188;
	int32 ecx_2911 = (word32) (g_b713D + ~0x42 + (byte) edx_2897);
	*((word32) (fp - 0x010C) + ecx_2911) = (ptr32) ~0x42;
	int32 edx_2925 = (word32) (g_b713E + ~0x41 + (byte) ecx_2911);
	*((word32) (fp - 0x010C) + edx_2925) = (ptr32) ~0x41;
	int32 ecx_2939 = (word32) (g_b713F + 191 + (byte) edx_2925);
	*((word32) (fp - 0x010C) + ecx_2939) = (ptr32) 191;
	int32 edx_2953 = (word32) (g_b7140 + 0xC0 + (byte) ecx_2939);
	*((word32) (fp - 0x010C) + edx_2953) = (ptr32) 0xC0;
	int32 ecx_2967 = (word32) (g_b7141 + 0xC1 + (byte) edx_2953);
	*((word32) (fp - 0x010C) + ecx_2967) = (ptr32) 0xC1;
	int32 edx_2981 = (word32) (g_b7142 + 0xC2 + (byte) ecx_2967);
	*((word32) (fp - 0x010C) + edx_2981) = (ptr32) 0xC2;
	int32 ecx_2995 = (word32) (g_b7143 + 0xC3 + (byte) edx_2981);
	*((word32) (fp - 0x010C) + ecx_2995) = (ptr32) 0xC3;
	int32 edx_3009 = (word32) (g_b7144 + 0xC4 + (byte) ecx_2995);
	*((word32) (fp - 0x010C) + edx_3009) = (ptr32) 0xC4;
	int32 ecx_3023 = (word32) (g_b7145 + 0xC5 + (byte) edx_3009);
	*((word32) (fp - 0x010C) + ecx_3023) = (ptr32) 0xC5;
	int32 edx_3037 = (word32) (g_b7146 + 0xC6 + (byte) ecx_3023);
	*((word32) (fp - 0x010C) + edx_3037) = (ptr32) 0xC6;
	int32 ecx_3051 = (word32) (g_b7147 + 199 + (byte) edx_3037);
	*((word32) (fp - 0x010C) + ecx_3051) = (ptr32) 199;
	int32 edx_3065 = (word32) (g_b7148 + 200 + (byte) ecx_3051);
	*((word32) (fp - 0x010C) + edx_3065) = (ptr32) 200;
	int32 ecx_3079 = (word32) (g_b7149 + 0xC9 + (byte) edx_3065);
	*((word32) (fp - 0x010C) + ecx_3079) = (ptr32) 0xC9;
	int32 edx_3093 = (word32) (g_b714A + 202 + (byte) ecx_3079);
	*((word32) (fp - 0x010C) + edx_3093) = (ptr32) 202;
	int32 ecx_3107 = (word32) (g_b714B + ~0x34 + (byte) edx_3093);
	*((word32) (fp - 0x010C) + ecx_3107) = (ptr32) ~0x34;
	int32 edx_3121 = (word32) (g_b714C + 0xCC + (byte) ecx_3107);
	*((word32) (fp - 0x010C) + edx_3121) = (ptr32) 0xCC;
	int32 ecx_3135 = (word32) (g_b714D + ~0x32 + (byte) edx_3121);
	*((word32) (fp - 0x010C) + ecx_3135) = (ptr32) ~0x32;
	int32 edx_3149 = (word32) (g_b714E + ~0x31 + (byte) ecx_3135);
	*((word32) (fp - 0x010C) + edx_3149) = (ptr32) ~0x31;
	int32 ecx_3163 = (word32) (g_b714F + ~0x30 + (byte) edx_3149);
	*((word32) (fp - 0x010C) + ecx_3163) = (ptr32) ~0x30;
	int32 edx_3177 = (word32) (g_b7150 + 0xD0 + (byte) ecx_3163);
	*((word32) (fp - 0x010C) + edx_3177) = (ptr32) 0xD0;
	int32 ecx_3191 = (word32) (g_b7151 + 0xD1 + (byte) edx_3177);
	*((word32) (fp - 0x010C) + ecx_3191) = (ptr32) 0xD1;
	int32 edx_3205 = (word32) (g_b7152 + 0xD2 + (byte) ecx_3191);
	*((word32) (fp - 0x010C) + edx_3205) = (ptr32) 0xD2;
	int32 ecx_3219 = (word32) (g_b7153 + 211 + (byte) edx_3205);
	*((word32) (fp - 0x010C) + ecx_3219) = (ptr32) 211;
	int32 edx_3233 = (word32) (g_b7154 + 212 + (byte) ecx_3219);
	*((word32) (fp - 0x010C) + edx_3233) = (ptr32) 212;
	int32 ecx_3247 = (word32) (g_b7155 + ~0x2A + (byte) edx_3233);
	*((word32) (fp - 0x010C) + ecx_3247) = (ptr32) ~0x2A;
	int32 edx_3261 = (word32) (g_b7156 + ~0x29 + (byte) ecx_3247);
	*((word32) (fp - 0x010C) + edx_3261) = (ptr32) ~0x29;
	int32 ecx_3275 = (word32) (g_b7157 + ~0x28 + (byte) edx_3261);
	*((word32) (fp - 0x010C) + ecx_3275) = (ptr32) ~0x28;
	int32 edx_3289 = (word32) (g_b7158 + 0xD8 + (byte) ecx_3275);
	*((word32) (fp - 0x010C) + edx_3289) = (ptr32) 0xD8;
	int32 ecx_3303 = (word32) (g_b7159 + ~0x26 + (byte) edx_3289);
	*((word32) (fp - 0x010C) + ecx_3303) = (ptr32) ~0x26;
	int32 edx_3317 = (word32) (g_b715A + ~0x25 + (byte) ecx_3303);
	*((word32) (fp - 0x010C) + edx_3317) = (ptr32) ~0x25;
	int32 ecx_3331 = (word32) (g_b715B + ~0x24 + (byte) edx_3317);
	*((word32) (fp - 0x010C) + ecx_3331) = (ptr32) ~0x24;
	int32 edx_3345 = (word32) (g_b715C + 220 + (byte) ecx_3331);
	*((word32) (fp - 0x010C) + edx_3345) = (ptr32) 220;
	int32 ecx_3359 = (word32) (g_b715D + ~0x22 + (byte) edx_3345);
	*((word32) (fp - 0x010C) + ecx_3359) = (ptr32) ~0x22;
	int32 edx_3373 = (word32) (g_b715E + 222 + (byte) ecx_3359);
	*((word32) (fp - 0x010C) + edx_3373) = (ptr32) 222;
	int32 ecx_3387 = (word32) (g_b715F + 223 + (byte) edx_3373);
	*((word32) (fp - 0x010C) + ecx_3387) = (ptr32) 223;
	int32 edx_3401 = (word32) (g_b7160 + 0xE0 + (byte) ecx_3387);
	*((word32) (fp - 0x010C) + edx_3401) = (ptr32) 0xE0;
	int32 ecx_3415 = (word32) (g_b7161 + 225 + (byte) edx_3401);
	*((word32) (fp - 0x010C) + ecx_3415) = (ptr32) 225;
	int32 edx_3429 = (word32) (g_b7162 + 226 + (byte) ecx_3415);
	*((word32) (fp - 0x010C) + edx_3429) = (ptr32) 226;
	int32 ecx_3443 = (word32) (g_b7163 + 227 + (byte) edx_3429);
	*((word32) (fp - 0x010C) + ecx_3443) = (ptr32) 227;
	int32 edx_3457 = (word32) (g_b7164 + 228 + (byte) ecx_3443);
	*((word32) (fp - 0x010C) + edx_3457) = (ptr32) 228;
	int32 ecx_3471 = (word32) (g_b7165 + 229 + (byte) edx_3457);
	*((word32) (fp - 0x010C) + ecx_3471) = (ptr32) 229;
	int32 edx_3485 = (word32) (g_b7166 + ~0x19 + (byte) ecx_3471);
	*((word32) (fp - 0x010C) + edx_3485) = (ptr32) ~0x19;
	int32 ecx_3499 = (word32) (g_b7167 + ~0x18 + (byte) edx_3485);
	*((word32) (fp - 0x010C) + ecx_3499) = (ptr32) ~0x18;
	int32 edx_3513 = (word32) (g_b7168 + 232 + (byte) ecx_3499);
	*((word32) (fp - 0x010C) + edx_3513) = (ptr32) 232;
	int32 ecx_3527 = (word32) (g_b7169 + 233 + (byte) edx_3513);
	*((word32) (fp - 0x010C) + ecx_3527) = (ptr32) 233;
	int32 edx_3541 = (word32) (g_b716A + ~0x15 + (byte) ecx_3527);
	*((word32) (fp - 0x010C) + edx_3541) = (ptr32) ~0x15;
	int32 ecx_3555 = (word32) (g_b716B + ~0x14 + (byte) edx_3541);
	*((word32) (fp - 0x010C) + ecx_3555) = (ptr32) ~0x14;
	int32 edx_3569 = (word32) (g_b716C + ~0x13 + (byte) ecx_3555);
	*((word32) (fp - 0x010C) + edx_3569) = (ptr32) ~0x13;
	int32 ecx_3583 = (word32) (g_b716D + ~0x12 + (byte) edx_3569);
	*((word32) (fp - 0x010C) + ecx_3583) = (ptr32) ~0x12;
	int32 edx_3597 = (word32) (g_b716E + ~0x11 + (byte) ecx_3583);
	*((word32) (fp - 0x010C) + edx_3597) = (ptr32) ~0x11;
	int32 ecx_3611 = (word32) (g_b716F + ~0x10 + (byte) edx_3597);
	*((word32) (fp - 0x010C) + ecx_3611) = (ptr32) ~0x10;
	int32 edx_3625 = (word32) (g_b7170 + 0xF0 + (byte) ecx_3611);
	*((word32) (fp - 0x010C) + edx_3625) = (ptr32) 0xF0;
	int32 ecx_3639 = (word32) (g_b7171 + ~0x0E + (byte) edx_3625);
	*((word32) (fp - 0x010C) + ecx_3639) = (ptr32) ~0x0E;
	int32 edx_3653 = (word32) (g_b7172 + 242 + (byte) ecx_3639);
	*((word32) (fp - 0x010C) + edx_3653) = (ptr32) 242;
	int32 ecx_3667 = (word32) (g_b7173 + ~0x0C + (byte) edx_3653);
	*((word32) (fp - 0x010C) + ecx_3667) = (ptr32) ~0x0C;
	int32 edx_3681 = (word32) (g_b7174 + 244 + (byte) ecx_3667);
	*((word32) (fp - 0x010C) + edx_3681) = (ptr32) 244;
	int32 ecx_3695 = (word32) (g_b7175 + ~0x0A + (byte) edx_3681);
	*((word32) (fp - 0x010C) + ecx_3695) = (ptr32) ~0x0A;
	int32 edx_3709 = (word32) (g_b7176 + ~0x09 + (byte) ecx_3695);
	*((word32) (fp - 0x010C) + edx_3709) = (ptr32) ~0x09;
	int32 ecx_3723 = (word32) (g_b7177 + ~0x08 + (byte) edx_3709);
	*((word32) (fp - 0x010C) + ecx_3723) = (ptr32) ~0x08;
	int32 edx_3737 = (word32) (g_b7178 + ~0x07 + (byte) ecx_3723);
	*((word32) (fp - 0x010C) + edx_3737) = (ptr32) ~0x07;
	int32 ecx_3751 = (word32) (g_b7179 + ~0x06 + (byte) edx_3737);
	*((word32) (fp - 0x010C) + ecx_3751) = (ptr32) ~0x06;
	int32 edx_3765 = (word32) (g_b717A + ~0x05 + (byte) ecx_3751);
	*((word32) (fp - 0x010C) + edx_3765) = (ptr32) ~0x05;
	int32 ecx_3779 = (word32) (g_b717B + ~0x04 + (byte) edx_3765);
	*((word32) (fp - 0x010C) + ecx_3779) = (ptr32) ~0x04;
	int32 edx_3793 = (word32) (g_b717C + 252 + (byte) ecx_3779);
	*((word32) (fp - 0x010C) + edx_3793) = (ptr32) 252;
	int32 ecx_3807 = (word32) (g_b717D + ~0x02 + (byte) edx_3793);
	*((word32) (fp - 0x010C) + ecx_3807) = (ptr32) ~0x02;
	int32 eax_3821 = (word32) (g_b717E + ~0x01 + (byte) ecx_3807);
	*((word32) (fp - 0x010C) + eax_3821) = (ptr32) ~0x01;
	*((word32) (fp - 0x010C) + (word32) ((byte) eax_3821 + (g_b717F + ~0x00))) = (ptr32) ~0x00;
	int32 eax_3843 = (word32) dl_283;
	*((word32) (fp - 0x010C) + eax_3843) = (ptr32) dl_283;
	int32 eax_3857 = (word32) (dl_283 + cl_297);
	*((word32) (fp - 0x010C) + eax_3857) = (ptr32) cl_297;
	int32 eax_3872 = (word32) ((byte) eax_3857 + dl_311);
	*((word32) (fp - 0x010C) + eax_3872) = (ptr32) dl_311;
	int32 eax_3887 = (word32) ((byte) eax_3872 + cl_325);
	*((word32) (fp - 0x010C) + eax_3887) = (ptr32) cl_325;
	int32 eax_3902 = (word32) ((byte) eax_3887 + dl_339);
	*((word32) (fp - 0x010C) + eax_3902) = (ptr32) dl_339;
	int32 eax_3917 = (word32) ((byte) eax_3902 + cl_353);
	*((word32) (fp - 0x010C) + eax_3917) = (ptr32) cl_353;
	int32 eax_3932 = (word32) ((byte) eax_3917 + dl_367);
	*((word32) (fp - 0x010C) + eax_3932) = (ptr32) dl_367;
	int32 eax_3947 = (word32) ((byte) eax_3932 + cl_381);
	*((word32) (fp - 0x010C) + eax_3947) = (ptr32) cl_381;
	int32 eax_3962 = (word32) ((byte) eax_3947 + dl_395);
	*((word32) (fp - 0x010C) + eax_3962) = (ptr32) dl_395;
	int32 eax_3977 = (word32) ((byte) eax_3962 + cl_409);
	*((word32) (fp - 0x010C) + eax_3977) = (ptr32) cl_409;
	int32 eax_3992 = (word32) ((byte) eax_3977 + dl_423);
	*((word32) (fp - 0x010C) + eax_3992) = (ptr32) dl_423;
	int32 eax_4007 = (word32) ((byte) eax_3992 + cl_437);
	*((word32) (fp - 0x010C) + eax_4007) = (ptr32) cl_437;
	int32 eax_4022 = (word32) ((byte) eax_4007 + dl_451);
	*((word32) (fp - 0x010C) + eax_4022) = (ptr32) dl_451;
	int32 eax_4037 = (word32) ((byte) eax_4022 + cl_465);
	*((word32) (fp - 0x010C) + eax_4037) = (ptr32) cl_465;
	int32 eax_4052 = (word32) ((byte) eax_4037 + dl_479);
	*((word32) (fp - 0x010C) + eax_4052) = (ptr32) dl_479;
	int32 eax_4067 = (word32) ((byte) eax_4052 + cl_493);
	*((word32) (fp - 0x010C) + eax_4067) = (ptr32) cl_493;
	int32 eax_4082 = (word32) ((byte) eax_4067 + dl_507);
	*((word32) (fp - 0x010C) + eax_4082) = (ptr32) dl_507;
	int32 eax_4097 = (word32) ((byte) eax_4082 + cl_521);
	*((word32) (fp - 0x010C) + eax_4097) = (ptr32) cl_521;
	int32 eax_4112 = (word32) ((byte) eax_4097 + dl_535);
	*((word32) (fp - 0x010C) + eax_4112) = (ptr32) dl_535;
	int32 eax_4127 = (word32) ((byte) eax_4112 + cl_549);
	*((word32) (fp - 0x010C) + eax_4127) = (ptr32) cl_549;
	int32 eax_4142 = (word32) ((byte) eax_4127 + dl_563);
	*((word32) (fp - 0x010C) + eax_4142) = (ptr32) dl_563;
	int32 eax_4157 = (word32) ((byte) eax_4142 + cl_577);
	*((word32) (fp - 0x010C) + eax_4157) = (ptr32) cl_577;
	int32 eax_4172 = (word32) ((byte) eax_4157 + dl_591);
	*((word32) (fp - 0x010C) + eax_4172) = (ptr32) dl_591;
	int32 eax_4187 = (word32) ((byte) eax_4172 + cl_605);
	*((word32) (fp - 0x010C) + eax_4187) = (ptr32) cl_605;
	int32 eax_4202 = (word32) ((byte) eax_4187 + dl_619);
	*((word32) (fp - 0x010C) + eax_4202) = (ptr32) dl_619;
	int32 eax_4217 = (word32) ((byte) eax_4202 + cl_633);
	*((word32) (fp - 0x010C) + eax_4217) = (ptr32) cl_633;
	int32 eax_4232 = (word32) ((byte) eax_4217 + dl_647);
	*((word32) (fp - 0x010C) + eax_4232) = (ptr32) dl_647;
	int32 eax_4247 = (word32) ((byte) eax_4232 + cl_661);
	*((word32) (fp - 0x010C) + eax_4247) = (ptr32) cl_661;
	int32 eax_4262 = (word32) ((byte) eax_4247 + dl_675);
	*((word32) (fp - 0x010C) + eax_4262) = (ptr32) dl_675;
	int32 eax_4277 = (word32) ((byte) eax_4262 + cl_689);
	*((word32) (fp - 0x010C) + eax_4277) = (ptr32) cl_689;
	int32 eax_4292 = (word32) ((byte) eax_4277 + dl_703);
	*((word32) (fp - 0x010C) + eax_4292) = (ptr32) dl_703;
	int32 eax_4307 = (word32) ((byte) eax_4292 + cl_717);
	*((word32) (fp - 0x010C) + eax_4307) = (ptr32) cl_717;
	int32 eax_4322 = (word32) ((byte) eax_4307 + dl_731);
	*((word32) (fp - 0x010C) + eax_4322) = (ptr32) dl_731;
	int32 eax_4337 = (word32) ((byte) eax_4322 + cl_745);
	*((word32) (fp - 0x010C) + eax_4337) = (ptr32) cl_745;
	int32 eax_4352 = (word32) ((byte) eax_4337 + dl_759);
	*((word32) (fp - 0x010C) + eax_4352) = (ptr32) dl_759;
	int32 eax_4367 = (word32) ((byte) eax_4352 + cl_773);
	*((word32) (fp - 0x010C) + eax_4367) = (ptr32) cl_773;
	int32 eax_4382 = (word32) ((byte) eax_4367 + dl_787);
	*((word32) (fp - 0x010C) + eax_4382) = (ptr32) dl_787;
	int32 eax_4397 = (word32) ((byte) eax_4382 + cl_801);
	*((word32) (fp - 0x010C) + eax_4397) = (ptr32) cl_801;
	int32 eax_4412 = (word32) ((byte) eax_4397 + dl_815);
	*((word32) (fp - 0x010C) + eax_4412) = (ptr32) dl_815;
	int32 eax_4427 = (word32) ((byte) eax_4412 + cl_829);
	*((word32) (fp - 0x010C) + eax_4427) = (ptr32) cl_829;
	int32 eax_4442 = (word32) ((byte) eax_4427 + dl_843);
	*((word32) (fp - 0x010C) + eax_4442) = (ptr32) dl_843;
	int32 eax_4457 = (word32) ((byte) eax_4442 + cl_857);
	*((word32) (fp - 0x010C) + eax_4457) = (ptr32) cl_857;
	int32 eax_4472 = (word32) ((byte) eax_4457 + dl_871);
	*((word32) (fp - 0x010C) + eax_4472) = (ptr32) dl_871;
	int32 eax_4487 = (word32) ((byte) eax_4472 + cl_885);
	*((word32) (fp - 0x010C) + eax_4487) = (ptr32) cl_885;
	int32 eax_4502 = (word32) ((byte) eax_4487 + dl_899);
	*((word32) (fp - 0x010C) + eax_4502) = (ptr32) dl_899;
	int32 eax_4517 = (word32) ((byte) eax_4502 + cl_913);
	*((word32) (fp - 0x010C) + eax_4517) = (ptr32) cl_913;
	int32 eax_4532 = (word32) ((byte) eax_4517 + dl_927);
	*((word32) (fp - 0x010C) + eax_4532) = (ptr32) dl_927;
	int32 eax_4547 = (word32) ((byte) eax_4532 + cl_941);
	*((word32) (fp - 0x010C) + eax_4547) = (ptr32) cl_941;
	int32 eax_4562 = (word32) ((byte) eax_4547 + dl_955);
	*((word32) (fp - 0x010C) + eax_4562) = (ptr32) dl_955;
	int32 eax_4577 = (word32) ((byte) eax_4562 + cl_969);
	*((word32) (fp - 0x010C) + eax_4577) = (ptr32) cl_969;
	int32 eax_4592 = (word32) ((byte) eax_4577 + dl_983);
	*((word32) (fp - 0x010C) + eax_4592) = (ptr32) dl_983;
	int32 eax_4607 = (word32) ((byte) eax_4592 + cl_997);
	*((word32) (fp - 0x010C) + eax_4607) = (ptr32) cl_997;
	int32 eax_4622 = (word32) ((byte) eax_4607 + dl_1011);
	*((word32) (fp - 0x010C) + eax_4622) = (ptr32) dl_1011;
	int32 eax_4637 = (word32) ((byte) eax_4622 + cl_1025);
	*((word32) (fp - 0x010C) + eax_4637) = (ptr32) cl_1025;
	int32 eax_4652 = (word32) ((byte) eax_4637 + dl_1039);
	*((word32) (fp - 0x010C) + eax_4652) = (ptr32) dl_1039;
	int32 eax_4667 = (word32) ((byte) eax_4652 + cl_1053);
	*((word32) (fp - 0x010C) + eax_4667) = (ptr32) cl_1053;
	int32 eax_4682 = (word32) ((byte) eax_4667 + dl_1067);
	*((word32) (fp - 0x010C) + eax_4682) = (ptr32) dl_1067;
	int32 eax_4697 = (word32) ((byte) eax_4682 + cl_1081);
	*((word32) (fp - 0x010C) + eax_4697) = (ptr32) cl_1081;
	int32 eax_4712 = (word32) ((byte) eax_4697 + dl_1095);
	*((word32) (fp - 0x010C) + eax_4712) = (ptr32) dl_1095;
	int32 eax_4727 = (word32) ((byte) eax_4712 + cl_1109);
	*((word32) (fp - 0x010C) + eax_4727) = (ptr32) cl_1109;
	int32 eax_4742 = (word32) ((byte) eax_4727 + dl_1123);
	*((word32) (fp - 0x010C) + eax_4742) = (ptr32) dl_1123;
	*((word32) (fp - 0x010C) + (word32) ((byte) eax_4742 + cl_1137)) = (ptr32) cl_1137;
	printf(&g_t6FF4);
}

// 000048DE: void main()
void main()
{
	ptr32 fp;
	__align_stack<word32>(fp);
	multiplication_table();
	decrypt_message();
}

// tmp61r6hv6n_got_plt.c
// Generated by decompiling tmp61r6hv6n
// using Reko decompiler version 0.11.6.0.

#include "tmp61r6hv6n.h"

struct Eq_7 g_t6FF4 = // 00006FF4
	{
		null,
		&g_t1036,
		&g_t1046,
	};
<anonymous> * __libc_start_main_GOT = &g_t1036; // 00007000
<anonymous> * printf_GOT = &g_t1046; // 00007004
// tmp61r6hv6n_fini.c
// Generated by decompiling tmp61r6hv6n
// using Reko decompiler version 0.11.6.0.

#include "tmp61r6hv6n.h"

// 0000490C: void _fini()
void _fini()
{
}

// tmp61r6hv6n_plt.c
// Generated by decompiling tmp61r6hv6n
// using Reko decompiler version 0.11.6.0.

#include "tmp61r6hv6n.h"

// 00001030: void __libc_start_main(Register (ptr32 Eq_7) ebx)
// Called from:
//      _start
void __libc_start_main(struct Eq_7 * ebx)
{
	ebx->ptr000C();
}

<anonymous> g_t1036 = <code>; // 00001036
// 00001040: void printf(Register (ptr32 Eq_7) ebx)
// Called from:
//      multiplication_table
//      decrypt_message
void printf(struct Eq_7 * ebx)
{
	ebx->ptr0010();
}

<anonymous> g_t1046 = <code>; // 00001046
// tmp61r6hv6n_bss.c
// Generated by decompiling tmp61r6hv6n
// using Reko decompiler version 0.11.6.0.

#include "tmp61r6hv6n.h"

byte g_b7187 = 0x00; // 00007187
// tmp61r6hv6n_plt_got.c
// Generated by decompiling tmp61r6hv6n
// using Reko decompiler version 0.11.6.0.

#include "tmp61r6hv6n.h"

// 00001050: void fn00001050(Register (ptr32 Eq_7) ebx)
// Called from:
//      __do_global_dtors_aux
void fn00001050(struct Eq_7 * ebx)
{
	ebx->ptrFFFFFFF0();
}

// tmp61r6hv6n_data.c
// Generated by decompiling tmp61r6hv6n
// using Reko decompiler version 0.11.6.0.

#include "tmp61r6hv6n.h"

byte g_b7080 = 0x49; // 00007080
byte g_b7081 = 110; // 00007081
byte g_b7082 = 0x20; // 00007082
byte g_b7083 = 99; // 00007083
byte g_b7084 = 114; // 00007084
byte g_b7085 = 121; // 00007085
byte g_b7086 = 0x70; // 00007086
byte g_b7087 = 116; // 00007087
byte g_b7088 = 111; // 00007088
byte g_b7089 = 0x67; // 00007089
byte g_b708A = 114; // 0000708A
byte g_b708B = 0x61; // 0000708B
byte g_b708C = 0x70; // 0000708C
byte g_b708D = 0x68; // 0000708D
byte g_b708E = 121; // 0000708E
byte g_b708F = 44; // 0000708F
byte g_b7090 = 0x20; // 00007090
byte g_b7091 = 0x52; // 00007091
byte g_b7092 = 0x43; // 00007092
byte g_b7093 = 0x34; // 00007093
byte g_b7094 = 0x20; // 00007094
byte g_b7095 = 0x28; // 00007095
byte g_b7096 = 0x52; // 00007096
byte g_b7097 = 0x69; // 00007097
byte g_b7098 = 118; // 00007098
byte g_b7099 = 101; // 00007099
byte g_b709A = 115; // 0000709A
byte g_b709B = 116; // 0000709B
byte g_b709C = 0x20; // 0000709C
byte g_b709D = 0x43; // 0000709D
byte g_b709E = 0x69; // 0000709E
byte g_b709F = 0x70; // 0000709F
byte g_b70A0 = 0x68; // 000070A0
byte g_b70A1 = 101; // 000070A1
byte g_b70A2 = 114; // 000070A2
byte g_b70A3 = 0x20; // 000070A3
byte g_b70A4 = 0x34; // 000070A4
byte g_b70A5 = 44; // 000070A5
byte g_b70A6 = 0x20; // 000070A6
byte g_b70A7 = 0x61; // 000070A7
byte g_b70A8 = 0x6C; // 000070A8
byte g_b70A9 = 115; // 000070A9
byte g_b70AA = 111; // 000070AA
byte g_b70AB = 0x20; // 000070AB
byte g_b70AC = 0x6B; // 000070AC
byte g_b70AD = 110; // 000070AD
byte g_b70AE = 111; // 000070AE
byte g_b70AF = 0x77; // 000070AF
byte g_b70B0 = 110; // 000070B0
byte g_b70B1 = 0x20; // 000070B1
byte g_b70B2 = 0x61; // 000070B2
byte g_b70B3 = 115; // 000070B3
byte g_b70B4 = 0x20; // 000070B4
byte g_b70B5 = 0x41; // 000070B5
byte g_b70B6 = 0x52; // 000070B6
byte g_b70B7 = 0x43; // 000070B7
byte g_b70B8 = 0x34; // 000070B8
byte g_b70B9 = 0x20; // 000070B9
byte g_b70BA = 111; // 000070BA
byte g_b70BB = 114; // 000070BB
byte g_b70BC = 0x20; // 000070BC
byte g_b70BD = 0x41; // 000070BD
byte g_b70BE = 0x52; // 000070BE
byte g_b70BF = 0x43; // 000070BF
byte g_b70C0 = 0x46; // 000070C0
byte g_b70C1 = 0x4F; // 000070C1
byte g_b70C2 = 0x55; // 000070C2
byte g_b70C3 = 0x52; // 000070C3
byte g_b70C4 = 44; // 000070C4
byte g_b70C5 = 0x20; // 000070C5
byte g_b70C6 = 0x6D; // 000070C6
byte g_b70C7 = 101; // 000070C7
byte g_b70C8 = 0x61; // 000070C8
byte g_b70C9 = 110; // 000070C9
byte g_b70CA = 0x69; // 000070CA
byte g_b70CB = 110; // 000070CB
byte g_b70CC = 0x67; // 000070CC
byte g_b70CD = 0x20; // 000070CD
byte g_b70CE = 0x41; // 000070CE
byte g_b70CF = 0x6C; // 000070CF
byte g_b70D0 = 0x6C; // 000070D0
byte g_b70D1 = 101; // 000070D1
byte g_b70D2 = 0x67; // 000070D2
byte g_b70D3 = 101; // 000070D3
byte g_b70D4 = 100; // 000070D4
byte g_b70D5 = 0x20; // 000070D5
byte g_b70D6 = 0x52; // 000070D6
byte g_b70D7 = 0x43; // 000070D7
byte g_b70D8 = 0x34; // 000070D8
byte g_b70D9 = 44; // 000070D9
byte g_b70DA = 0x20; // 000070DA
byte g_b70DB = 115; // 000070DB
byte g_b70DC = 101; // 000070DC
byte g_b70DD = 101; // 000070DD
byte g_b70DE = 0x20; // 000070DE
byte g_b70DF = 0x62; // 000070DF
byte g_b70E0 = 101; // 000070E0
byte g_b70E1 = 0x6C; // 000070E1
byte g_b70E2 = 111; // 000070E2
byte g_b70E3 = 0x77; // 000070E3
byte g_b70E4 = 0x29; // 000070E4
byte g_b70E5 = 0x20; // 000070E5
byte g_b70E6 = 0x69; // 000070E6
byte g_b70E7 = 115; // 000070E7
byte g_b70E8 = 0x20; // 000070E8
byte g_b70E9 = 0x61; // 000070E9
byte g_b70EA = 0x20; // 000070EA
byte g_b70EB = 115; // 000070EB
byte g_b70EC = 116; // 000070EC
byte g_b70ED = 114; // 000070ED
byte g_b70EE = 101; // 000070EE
byte g_b70EF = 0x61; // 000070EF
byte g_b70F0 = 0x6D; // 000070F0
byte g_b70F1 = 0x20; // 000070F1
byte g_b70F2 = 99; // 000070F2
byte g_b70F3 = 0x69; // 000070F3
byte g_b70F4 = 0x70; // 000070F4
byte g_b70F5 = 0x68; // 000070F5
byte g_b70F6 = 101; // 000070F6
byte g_b70F7 = 114; // 000070F7
byte g_b70F8 = 0x2E; // 000070F8
byte g_b70F9 = 0x20; // 000070F9
byte g_b70FA = 0x57; // 000070FA
byte g_b70FB = 0x68; // 000070FB
byte g_b70FC = 0x69; // 000070FC
byte g_b70FD = 0x6C; // 000070FD
byte g_b70FE = 101; // 000070FE
byte g_b70FF = 0x20; // 000070FF
byte g_b7100 = 0x69; // 00007100
byte g_b7101 = 116; // 00007101
byte g_b7102 = 0x20; // 00007102
byte g_b7103 = 0x69; // 00007103
byte g_b7104 = 115; // 00007104
byte g_b7105 = 0x20; // 00007105
byte g_b7106 = 114; // 00007106
byte g_b7107 = 101; // 00007107
byte g_b7108 = 0x6D; // 00007108
byte g_b7109 = 0x61; // 00007109
byte g_b710A = 114; // 0000710A
byte g_b710B = 0x6B; // 0000710B
byte g_b710C = 0x61; // 0000710C
byte g_b710D = 0x62; // 0000710D
byte g_b710E = 0x6C; // 0000710E
byte g_b710F = 101; // 0000710F
byte g_b7110 = 0x20; // 00007110
byte g_b7111 = 0x66; // 00007111
byte g_b7112 = 111; // 00007112
byte g_b7113 = 114; // 00007113
byte g_b7114 = 0x20; // 00007114
byte g_b7115 = 0x69; // 00007115
byte g_b7116 = 116; // 00007116
byte g_b7117 = 115; // 00007117
byte g_b7118 = 0x20; // 00007118
byte g_b7119 = 115; // 00007119
byte g_b711A = 0x69; // 0000711A
byte g_b711B = 0x6D; // 0000711B
byte g_b711C = 0x70; // 0000711C
byte g_b711D = 0x6C; // 0000711D
byte g_b711E = 0x69; // 0000711E
byte g_b711F = 99; // 0000711F
byte g_b7120 = 0x69; // 00007120
byte g_b7121 = 116; // 00007121
byte g_b7122 = 121; // 00007122
byte g_b7123 = 0x20; // 00007123
byte g_b7124 = 0x61; // 00007124
byte g_b7125 = 110; // 00007125
byte g_b7126 = 100; // 00007126
byte g_b7127 = 0x20; // 00007127
byte g_b7128 = 115; // 00007128
byte g_b7129 = 0x70; // 00007129
byte g_b712A = 101; // 0000712A
byte g_b712B = 101; // 0000712B
byte g_b712C = 100; // 0000712C
byte g_b712D = 0x20; // 0000712D
byte g_b712E = 0x69; // 0000712E
byte g_b712F = 110; // 0000712F
byte g_b7130 = 0x20; // 00007130
byte g_b7131 = 115; // 00007131
byte g_b7132 = 111; // 00007132
byte g_b7133 = 0x66; // 00007133
byte g_b7134 = 116; // 00007134
byte g_b7135 = 0x77; // 00007135
byte g_b7136 = 0x61; // 00007136
byte g_b7137 = 114; // 00007137
byte g_b7138 = 101; // 00007138
byte g_b7139 = 44; // 00007139
byte g_b713A = 0x20; // 0000713A
byte g_b713B = 0x6D; // 0000713B
byte g_b713C = 117; // 0000713C
byte g_b713D = 0x6C; // 0000713D
byte g_b713E = 116; // 0000713E
byte g_b713F = 0x69; // 0000713F
byte g_b7140 = 0x70; // 00007140
byte g_b7141 = 0x6C; // 00007141
byte g_b7142 = 101; // 00007142
byte g_b7143 = 0x20; // 00007143
byte g_b7144 = 118; // 00007144
byte g_b7145 = 117; // 00007145
byte g_b7146 = 0x6C; // 00007146
byte g_b7147 = 110; // 00007147
byte g_b7148 = 101; // 00007148
byte g_b7149 = 114; // 00007149
byte g_b714A = 0x61; // 0000714A
byte g_b714B = 0x62; // 0000714B
byte g_b714C = 0x69; // 0000714C
byte g_b714D = 0x6C; // 0000714D
byte g_b714E = 0x69; // 0000714E
byte g_b714F = 116; // 0000714F
byte g_b7150 = 0x69; // 00007150
byte g_b7151 = 101; // 00007151
byte g_b7152 = 115; // 00007152
byte g_b7153 = 0x20; // 00007153
byte g_b7154 = 0x68; // 00007154
byte g_b7155 = 0x61; // 00007155
byte g_b7156 = 118; // 00007156
byte g_b7157 = 101; // 00007157
byte g_b7158 = 0x20; // 00007158
byte g_b7159 = 0x62; // 00007159
byte g_b715A = 101; // 0000715A
byte g_b715B = 101; // 0000715B
byte g_b715C = 110; // 0000715C
byte g_b715D = 0x20; // 0000715D
byte g_b715E = 100; // 0000715E
byte g_b715F = 0x69; // 0000715F
byte g_b7160 = 115; // 00007160
byte g_b7161 = 99; // 00007161
byte g_b7162 = 111; // 00007162
byte g_b7163 = 118; // 00007163
byte g_b7164 = 101; // 00007164
byte g_b7165 = 114; // 00007165
byte g_b7166 = 101; // 00007166
byte g_b7167 = 100; // 00007167
byte g_b7168 = 0x20; // 00007168
byte g_b7169 = 0x69; // 00007169
byte g_b716A = 110; // 0000716A
byte g_b716B = 0x20; // 0000716B
byte g_b716C = 0x52; // 0000716C
byte g_b716D = 0x43; // 0000716D
byte g_b716E = 0x34; // 0000716E
byte g_b716F = 44; // 0000716F
byte g_b7170 = 0x20; // 00007170
byte g_b7171 = 114; // 00007171
byte g_b7172 = 101; // 00007172
byte g_b7173 = 110; // 00007173
byte g_b7174 = 100; // 00007174
byte g_b7175 = 101; // 00007175
byte g_b7176 = 114; // 00007176
byte g_b7177 = 0x69; // 00007177
byte g_b7178 = 110; // 00007178
byte g_b7179 = 0x67; // 00007179
byte g_b717A = 0x20; // 0000717A
byte g_b717B = 0x69; // 0000717B
byte g_b717C = 116; // 0000717C
byte g_b717D = 0x20; // 0000717D
byte g_b717E = 0x69; // 0000717E
byte g_b717F = 110; // 0000717F
// tmp61r6hv6n_comment.c
// Generated by decompiling tmp61r6hv6n
// using Reko decompiler version 0.11.6.0.

#include "tmp61r6hv6n.h"

<anonymous> g_t0000 = <code>; // 00000000
// tmp61r6hv6n_got.c
// Generated by decompiling tmp61r6hv6n
// using Reko decompiler version 0.11.6.0.

#include "tmp61r6hv6n.h"

<anonymous> * g_ptr6FE0 = null; // 00006FE0
<anonymous> * __cxa_finalize_GOT = null; // 00006FE4
<anonymous> * g_ptr6FE8 = null; // 00006FE8
<anonymous> * g_ptr6FF0 = null; // 00006FF0
// tmp61r6hv6n_init.c
// Generated by decompiling tmp61r6hv6n
// using Reko decompiler version 0.11.6.0.

#include "tmp61r6hv6n.h"

// 00001000: void _init()
void _init()
{
	<anonymous> * eax_10 = g_ptr6FE8;
	if (eax_10 != null)
		eax_10();
}

// tmp61r6hv6n_rodata.c
// Generated by decompiling tmp61r6hv6n
// using Reko decompiler version 0.11.6.0.

#include "tmp61r6hv6n.h"

word32 _fp_hw = 0x03; // 00005000
word32 _IO_stdin_used = 0x00020001; // 00005004
