//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t function_1035c(void);
int32_t function_10368(void);
int32_t it_crowd(void);

// ------------------------ Functions -------------------------

// Address range: 0x1035c - 0x10368
int32_t function_1035c(void) {
    // 0x1035c
    int32_t result; // 0x1035c
    return result;
}

// Address range: 0x10368 - 0x10374
int32_t function_10368(void) {
    // 0x10368
    int32_t result; // 0x10368
    return result;
}

// Address range: 0x1038c - 0x103b0
int main(int argc, char ** argv) {
    // 0x1038c
    it_crowd();
    function_1035c();
    return 0;
}

// Address range: 0x10494 - 0x105a0
int32_t it_crowd(void) {
    // 0x10494
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    function_10368();
    return function_10368();
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.3.0)
// Detected functions: 4

