// tmpq7901zkc_text.c
// Generated by decompiling tmpq7901zkc
// using Reko decompiler version 0.11.6.0.

#include "tmpq7901zkc.h"

// 00001070: void main()
void main()
{
	ptr32 fp;
	__align_stack<word32>(fp - 4);
	all_badges();
	polynome_table();
	red_herring();
}

// 00001090: void _start()
void _start()
{
	ptr32 fp;
	__align_stack<word32>(fp + 4);
	__libc_start_main(&g_t3FF4);
	__halt();
}

// 000010C0: void __x86.get_pc_thunk.bx()
void __x86.get_pc_thunk.bx()
{
}

// 000010D0: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
	if (0x40CC == 0x40CC)
		return;
	<anonymous> * eax_11 = g_ptr3FE0;
	if (eax_11 == null)
		return;
	eax_11();
}

// 00001110: void register_tm_clones()
// Called from:
//      frame_dummy
void register_tm_clones()
{
	Eq_58 eax_16 = 0x40CC - 0x40CC;
	Eq_64 eax_20 = (eax_16 >> 0x1F) + (eax_16 >> 0x02);
	if (eax_20 >> 0x01 != 0x00)
	{
		<anonymous> * edx_25 = g_ptr3FF0;
		if (edx_25 != null)
			edx_25();
	}
}

// 00001160: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	if (g_b40CA == 0x00)
	{
		if (__cxa_finalize_GOT != 0x00)
			fn00001060(&g_t3FF4);
		deregister_tm_clones();
		g_b40CA = 0x01;
	}
}

// 000011B0: void frame_dummy()
void frame_dummy()
{
	register_tm_clones();
}

// 000011B9: void __x86.get_pc_thunk.dx()
void __x86.get_pc_thunk.dx()
{
}

// 000011C0: void all_badges()
// Called from:
//      main
void all_badges()
{
	printf(&g_t3FF4);
}

// 00001250: void polynome_table()
// Called from:
//      main
void polynome_table()
{
	printf(&g_t3FF4);
	printf(&g_t3FF4);
	printf(&g_t3FF4);
	printf(&g_t3FF4);
	printf(&g_t3FF4);
	printf(&g_t3FF4);
	printf(&g_t3FF4);
	printf(&g_t3FF4);
	printf(&g_t3FF4);
	printf(&g_t3FF4);
	printf(&g_t3FF4);
}

// 00001310: void red_herring()
// Called from:
//      main
void red_herring()
{
	puts(&g_t3FF4);
	printf(&g_t3FF4);
	printf(&g_t3FF4);
	printf(&g_t3FF4);
	printf(&g_t3FF4);
	printf(&g_t3FF4);
}

// tmpq7901zkc_got_plt.c
// Generated by decompiling tmpq7901zkc
// using Reko decompiler version 0.11.6.0.

#include "tmpq7901zkc.h"

struct Eq_7 g_t3FF4 = // 00003FF4
	{
		null,
		&g_t1036,
		&g_t1046,
		&g_t1056,
	};
<anonymous> * __libc_start_main_GOT = &g_t1036; // 00004000
<anonymous> * printf_GOT = &g_t1046; // 00004004
<anonymous> * puts_GOT = &g_t1056; // 00004008
// tmpq7901zkc_rodata.c
// Generated by decompiling tmpq7901zkc
// using Reko decompiler version 0.11.6.0.

#include "tmpq7901zkc.h"

word32 _fp_hw = 0x03; // 00002000
word32 _IO_stdin_used = 0x00020001; // 00002004
// tmpq7901zkc_fini.c
// Generated by decompiling tmpq7901zkc
// using Reko decompiler version 0.11.6.0.

#include "tmpq7901zkc.h"

// 0000136C: void _fini()
void _fini()
{
}

// tmpq7901zkc_plt_got.c
// Generated by decompiling tmpq7901zkc
// using Reko decompiler version 0.11.6.0.

#include "tmpq7901zkc.h"

// 00001060: void fn00001060(Register (ptr32 Eq_7) ebx)
// Called from:
//      __do_global_dtors_aux
void fn00001060(struct Eq_7 * ebx)
{
	ebx->ptrFFFFFFF0();
}

// tmpq7901zkc_init.c
// Generated by decompiling tmpq7901zkc
// using Reko decompiler version 0.11.6.0.

#include "tmpq7901zkc.h"

// 00001000: void _init()
void _init()
{
	<anonymous> * eax_10 = g_ptr3FE8;
	if (eax_10 != null)
		eax_10();
}

// tmpq7901zkc_plt.c
// Generated by decompiling tmpq7901zkc
// using Reko decompiler version 0.11.6.0.

#include "tmpq7901zkc.h"

// 00001030: void __libc_start_main(Register (ptr32 Eq_7) ebx)
// Called from:
//      _start
void __libc_start_main(struct Eq_7 * ebx)
{
	ebx->ptr000C();
}

<anonymous> g_t1036 = <code>; // 00001036
// 00001040: void printf(Register (ptr32 Eq_7) ebx)
// Called from:
//      all_badges
//      polynome_table
//      red_herring
void printf(struct Eq_7 * ebx)
{
	ebx->ptr0010();
}

<anonymous> g_t1046 = <code>; // 00001046
// 00001050: void puts(Register (ptr32 Eq_7) ebx)
// Called from:
//      red_herring
void puts(struct Eq_7 * ebx)
{
	ebx->ptr0014();
}

<anonymous> g_t1056 = <code>; // 00001056
// tmpq7901zkc_bss.c
// Generated by decompiling tmpq7901zkc
// using Reko decompiler version 0.11.6.0.

#include "tmpq7901zkc.h"

byte g_b40CA = 0x00; // 000040CA
// tmpq7901zkc_comment.c
// Generated by decompiling tmpq7901zkc
// using Reko decompiler version 0.11.6.0.

#include "tmpq7901zkc.h"

<anonymous> g_t0000 = <code>; // 00000000
// tmpq7901zkc_got.c
// Generated by decompiling tmpq7901zkc
// using Reko decompiler version 0.11.6.0.

#include "tmpq7901zkc.h"

<anonymous> * g_ptr3FE0 = null; // 00003FE0
<anonymous> * __cxa_finalize_GOT = null; // 00003FE4
<anonymous> * g_ptr3FE8 = null; // 00003FE8
<anonymous> * g_ptr3FF0 = null; // 00003FF0
