//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t _all_badges(void);
int64_t _polynome_table(void);
int64_t _red_herring(void);

// ------- Dynamically Linked Functions Without Header --------

int32_t _printf(char * a1, ...);
int32_t _puts(char * a1);

// ------------------------ Functions -------------------------

// Address range: 0x100003bd8 - 0x100003c64
int64_t _all_badges(void) {
    uint16_t v1 = *(int16_t *)((int64_t)"Allison" + 131); // 0x100003c38
    return _printf("We can open every door with badge #%d\n", (int64_t)v1);
}

// Address range: 0x100003c64 - 0x100003d8c
int64_t _polynome_table(void) {
    // 0x100003c64
    int64_t v1; // 0x100003c64
    _printf("P(%d) = %d\n", v1, v1);
    _printf("P(%d) = %d\n", 1, v1);
    _printf("P(%d) = %d\n", 1, 0xffffffa3);
    _printf("P(%d) = %d\n", 1, 0xffffffa3);
    _printf("P(%d) = %d\n", 1, 0xffffffa3);
    _printf("P(%d) = %d\n", 1, 0xffffffa3);
    _printf("P(%d) = %d\n", 1, 0xffffffa3);
    _printf("P(%d) = %d\n", 1, 0xffffffa3);
    _printf("P(%d) = %d\n", 1, 0xffffffa3);
    _printf("P(%d) = %d\n", 1, 0xffffffa3);
    return _printf("P(%d) = %d\n", 10, 0xffffffa3);
}

// Address range: 0x100003d8c - 0x100003e10
int64_t _red_herring(void) {
    // 0x100003d8c
    _puts("These are a few of my favorite numbers:");
    _printf(" *  %d\n", 16);
    _printf(" *  %d\n", 16);
    _printf(" *  %d\n", 16);
    _printf(" *  %d\n", 16);
    return _printf(" *  %d\n", 16);
}

// Address range: 0x100003e10 - 0x100003e30
int main(int argc, char ** argv) {
    // 0x100003e10
    _all_badges();
    _polynome_table();
    _red_herring();
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 4

