//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int32_t __do_global_dtors_aux(void);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
int32_t decrypt_message(void);
int32_t deregister_tm_clones(void);
int32_t frame_dummy(void);
int32_t function_1030(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1040(char * format, ...);
int32_t function_1050(void);
int32_t function_1088(int32_t a1);
int32_t multiplication_table(int32_t a1);
int32_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1020
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x5fdf);
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1030
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * format, ...) {
    // 0x1040
    return printf(format);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(void) {
    // 0x1050
    int32_t result; // 0x1050
    return result;
}

// Address range: 0x1060 - 0x1088
int32_t _start(int32_t a1) {
    // 0x1060
    int32_t v1; // 0x1060
    function_1088(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x5f7c); // 0x107c
    int32_t v3; // 0x1060
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g1);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1088 - 0x108c
int32_t function_1088(int32_t a1) {
    // 0x1088
    int32_t result; // 0x1088
    return result;
}

// Address range: 0x1090 - 0x1094
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x1090
    int32_t result; // 0x1090
    return result;
}

// Address range: 0x10a0 - 0x10d9
int32_t deregister_tm_clones(void) {
    // 0x10a0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x10a0
    return v1 + 0x60e3;
}

// Address range: 0x10e0 - 0x1127
int32_t register_tm_clones(void) {
    // 0x10e0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return (int32_t)((uint32_t)((int32_t)"/lib/ld-linux.so.2" + 0x5f0f + -0x5f0f - (int32_t)"/lib/ld-linux.so.2") / 0x80000000 + ((int32_t)"/lib/ld-linux.so.2" + 0x5f0f + -0x5f0f - (int32_t)"/lib/ld-linux.so.2" >> 2)) >> 1;
}

// Address range: 0x1130 - 0x117b
int32_t __do_global_dtors_aux(void) {
    // 0x1130
    int32_t v1; // 0x1130
    int32_t result = __x86_get_pc_thunk_bx(v1); // 0x1138
    char * v2 = (char *)(v1 + 0x604a); // 0x1146
    if (*v2 != 0) {
        // 0x1176
        return result;
    }
    // 0x114f
    if (*(int32_t *)(v1 + 0x5ea7) != 0) {
        // 0x1159
        function_1050();
    }
    int32_t result2 = deregister_tm_clones(); // 0x116a
    *v2 = 1;
    // 0x1176
    return result2;
}

// Address range: 0x1180 - 0x1189
int32_t frame_dummy(void) {
    // 0x1180
    return register_tm_clones();
}

// Address range: 0x1189 - 0x118d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1189
    int32_t result; // 0x1189
    return result;
}

// Address range: 0x118d - 0x130d
int32_t multiplication_table(int32_t a1) {
    // 0x118d
    int32_t v1; // 0x118d
    __x86_get_pc_thunk_bx(v1);
    char * format = (char *)(v1 + 0x3e6f); // 0x11ae
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    printf(format);
    return printf(format);
}

// Address range: 0x130d - 0x48de
int32_t decrypt_message(void) {
    // 0x130d
    int32_t v1; // 0x130d
    __x86_get_pc_thunk_bx(v1);
    int32_t v2 = (int32_t)*(char *)(v1 + 0x5d67); // 0x1a5f
    int32_t v3; // bp-332, 0x130d
    int32_t v4 = (int32_t)&v3 + 64; // 0x1a6b
    *(char *)(v4 + v2) = 0;
    uint32_t v5 = (int32_t)(*(char *)(v1 + 0x5d68) + 1) + v2; // 0x1a81
    char * v6 = (char *)(v5 % 256 + v4); // 0x1a86
    unsigned char v7 = *v6; // 0x1a86
    int32_t v8 = v7; // 0x1a86
    *v6 = 1;
    uint32_t v9 = v5 + (int32_t)(*(char *)(v1 + 0x5d69) + 2); // 0x1aa0
    char * v10 = (char *)(v9 % 256 + v4); // 0x1aa5
    unsigned char v11 = *v10; // 0x1aa5
    *v10 = 2;
    uint32_t v12 = v9 + (int32_t)(*(char *)(v1 + 0x5d6a) + 3); // 0x1abf
    char * v13 = (char *)(v12 % 256 + v4); // 0x1ac4
    unsigned char v14 = *v13; // 0x1ac4
    *v13 = 3;
    uint32_t v15 = v12 + (int32_t)(*(char *)(v1 + 0x5d6b) + 4); // 0x1ade
    char * v16 = (char *)(v15 % 256 + v4); // 0x1ae3
    unsigned char v17 = *v16; // 0x1ae3
    *v16 = 4;
    uint32_t v18 = v15 + (int32_t)(*(char *)(v1 + 0x5d6c) + 5); // 0x1afd
    char * v19 = (char *)(v18 % 256 + v4); // 0x1b02
    unsigned char v20 = *v19; // 0x1b02
    *v19 = 5;
    uint32_t v21 = v18 + (int32_t)(*(char *)(v1 + 0x5d6d) + 6); // 0x1b1c
    char * v22 = (char *)(v21 % 256 + v4); // 0x1b21
    unsigned char v23 = *v22; // 0x1b21
    *v22 = 6;
    uint32_t v24 = v21 + (int32_t)(*(char *)(v1 + 0x5d6e) + 7); // 0x1b3b
    char * v25 = (char *)(v24 % 256 + v4); // 0x1b40
    unsigned char v26 = *v25; // 0x1b40
    *v25 = 7;
    uint32_t v27 = v24 + (int32_t)(*(char *)(v1 + 0x5d6f) + 8); // 0x1b5a
    char * v28 = (char *)(v27 % 256 + v4); // 0x1b5f
    unsigned char v29 = *v28; // 0x1b5f
    *v28 = 8;
    uint32_t v30 = v27 + (int32_t)(*(char *)(v1 + 0x5d70) + 9); // 0x1b79
    char * v31 = (char *)(v30 % 256 + v4); // 0x1b7e
    unsigned char v32 = *v31; // 0x1b7e
    *v31 = 9;
    uint32_t v33 = v30 + (int32_t)(*(char *)(v1 + 0x5d71) + 10); // 0x1b98
    char * v34 = (char *)(v33 % 256 + v4); // 0x1b9d
    unsigned char v35 = *v34; // 0x1b9d
    *v34 = 10;
    uint32_t v36 = v33 + (int32_t)(*(char *)(v1 + 0x5d72) + 11); // 0x1bb7
    char * v37 = (char *)(v36 % 256 + v4); // 0x1bbc
    unsigned char v38 = *v37; // 0x1bbc
    *v37 = 11;
    uint32_t v39 = v36 + (int32_t)(*(char *)(v1 + 0x5d73) + 12); // 0x1bd6
    char * v40 = (char *)(v39 % 256 + v4); // 0x1bdb
    unsigned char v41 = *v40; // 0x1bdb
    *v40 = 12;
    uint32_t v42 = v39 + (int32_t)(*(char *)(v1 + 0x5d74) + 13); // 0x1bf5
    char * v43 = (char *)(v42 % 256 + v4); // 0x1bfa
    unsigned char v44 = *v43; // 0x1bfa
    *v43 = 13;
    uint32_t v45 = v42 + (int32_t)(*(char *)(v1 + 0x5d75) + 14); // 0x1c14
    char * v46 = (char *)(v45 % 256 + v4); // 0x1c19
    unsigned char v47 = *v46; // 0x1c19
    *v46 = 14;
    uint32_t v48 = v45 + (int32_t)(*(char *)(v1 + 0x5d76) + 15); // 0x1c33
    char * v49 = (char *)(v48 % 256 + v4); // 0x1c38
    unsigned char v50 = *v49; // 0x1c38
    *v49 = 15;
    uint32_t v51 = v48 + (int32_t)(*(char *)(v1 + 0x5d77) + 16); // 0x1c52
    char * v52 = (char *)(v51 % 256 + v4); // 0x1c57
    unsigned char v53 = *v52; // 0x1c57
    *v52 = 16;
    uint32_t v54 = v51 + (int32_t)(*(char *)(v1 + 0x5d78) + 17); // 0x1c71
    char * v55 = (char *)(v54 % 256 + v4); // 0x1c76
    unsigned char v56 = *v55; // 0x1c76
    *v55 = 17;
    uint32_t v57 = v54 + (int32_t)(*(char *)(v1 + 0x5d79) + 18); // 0x1c90
    char * v58 = (char *)(v57 % 256 + v4); // 0x1c95
    unsigned char v59 = *v58; // 0x1c95
    *v58 = 18;
    uint32_t v60 = v57 + (int32_t)(*(char *)(v1 + 0x5d7a) + 19); // 0x1caf
    char * v61 = (char *)(v60 % 256 + v4); // 0x1cb4
    unsigned char v62 = *v61; // 0x1cb4
    *v61 = 19;
    uint32_t v63 = v60 + (int32_t)(*(char *)(v1 + 0x5d7b) + 20); // 0x1cce
    char * v64 = (char *)(v63 % 256 + v4); // 0x1cd3
    unsigned char v65 = *v64; // 0x1cd3
    *v64 = 20;
    uint32_t v66 = v63 + (int32_t)(*(char *)(v1 + 0x5d7c) + 21); // 0x1ced
    char * v67 = (char *)(v66 % 256 + v4); // 0x1cf2
    unsigned char v68 = *v67; // 0x1cf2
    *v67 = 21;
    uint32_t v69 = v66 + (int32_t)(*(char *)(v1 + 0x5d7d) + 22); // 0x1d0c
    char * v70 = (char *)(v69 % 256 + v4); // 0x1d11
    unsigned char v71 = *v70; // 0x1d11
    *v70 = 22;
    uint32_t v72 = v69 + (int32_t)(*(char *)(v1 + 0x5d7e) + 23); // 0x1d2b
    char * v73 = (char *)(v72 % 256 + v4); // 0x1d30
    unsigned char v74 = *v73; // 0x1d30
    *v73 = 23;
    uint32_t v75 = v72 + (int32_t)(*(char *)(v1 + 0x5d7f) + 24); // 0x1d4a
    char * v76 = (char *)(v75 % 256 + v4); // 0x1d4f
    unsigned char v77 = *v76; // 0x1d4f
    *v76 = 24;
    uint32_t v78 = v75 + (int32_t)(*(char *)(v1 + 0x5d80) + 25); // 0x1d69
    char * v79 = (char *)(v78 % 256 + v4); // 0x1d6e
    unsigned char v80 = *v79; // 0x1d6e
    *v79 = 25;
    uint32_t v81 = v78 + (int32_t)(*(char *)(v1 + 0x5d81) + 26); // 0x1d88
    char * v82 = (char *)(v81 % 256 + v4); // 0x1d8d
    unsigned char v83 = *v82; // 0x1d8d
    *v82 = 26;
    uint32_t v84 = v81 + (int32_t)(*(char *)(v1 + 0x5d82) + 27); // 0x1da7
    char * v85 = (char *)(v84 % 256 + v4); // 0x1dac
    unsigned char v86 = *v85; // 0x1dac
    *v85 = 27;
    uint32_t v87 = v84 + (int32_t)(*(char *)(v1 + 0x5d83) + 28); // 0x1dc6
    char * v88 = (char *)(v87 % 256 + v4); // 0x1dcb
    unsigned char v89 = *v88; // 0x1dcb
    *v88 = 28;
    uint32_t v90 = v87 + (int32_t)(*(char *)(v1 + 0x5d84) + 29); // 0x1de5
    char * v91 = (char *)(v90 % 256 + v4); // 0x1dea
    unsigned char v92 = *v91; // 0x1dea
    *v91 = 29;
    uint32_t v93 = v90 + (int32_t)(*(char *)(v1 + 0x5d85) + 30); // 0x1e04
    char * v94 = (char *)(v93 % 256 + v4); // 0x1e09
    unsigned char v95 = *v94; // 0x1e09
    *v94 = 30;
    uint32_t v96 = v93 + (int32_t)(*(char *)(v1 + 0x5d86) + 31); // 0x1e23
    char * v97 = (char *)(v96 % 256 + v4); // 0x1e28
    unsigned char v98 = *v97; // 0x1e28
    *v97 = 31;
    uint32_t v99 = v96 + (int32_t)(*(char *)(v1 + 0x5d87) + 32); // 0x1e42
    char * v100 = (char *)(v99 % 256 + v4); // 0x1e47
    unsigned char v101 = *v100; // 0x1e47
    *v100 = 32;
    uint32_t v102 = v99 + (int32_t)(*(char *)(v1 + 0x5d88) + 33); // 0x1e61
    char * v103 = (char *)(v102 % 256 + v4); // 0x1e66
    unsigned char v104 = *v103; // 0x1e66
    *v103 = 33;
    uint32_t v105 = v102 + (int32_t)(*(char *)(v1 + 0x5d89) + 34); // 0x1e80
    char * v106 = (char *)(v105 % 256 + v4); // 0x1e85
    unsigned char v107 = *v106; // 0x1e85
    *v106 = 34;
    uint32_t v108 = v105 + (int32_t)(*(char *)(v1 + 0x5d8a) + 35); // 0x1e9f
    char * v109 = (char *)(v108 % 256 + v4); // 0x1ea4
    unsigned char v110 = *v109; // 0x1ea4
    *v109 = 35;
    uint32_t v111 = v108 + (int32_t)(*(char *)(v1 + 0x5d8b) + 36); // 0x1ebe
    char * v112 = (char *)(v111 % 256 + v4); // 0x1ec3
    unsigned char v113 = *v112; // 0x1ec3
    *v112 = 36;
    uint32_t v114 = v111 + (int32_t)(*(char *)(v1 + 0x5d8c) + 37); // 0x1edd
    char * v115 = (char *)(v114 % 256 + v4); // 0x1ee2
    unsigned char v116 = *v115; // 0x1ee2
    *v115 = 37;
    uint32_t v117 = v114 + (int32_t)(*(char *)(v1 + 0x5d8d) + 38); // 0x1efc
    char * v118 = (char *)(v117 % 256 + v4); // 0x1f01
    unsigned char v119 = *v118; // 0x1f01
    *v118 = 38;
    uint32_t v120 = v117 + (int32_t)(*(char *)(v1 + 0x5d8e) + 39); // 0x1f1b
    char * v121 = (char *)(v120 % 256 + v4); // 0x1f20
    unsigned char v122 = *v121; // 0x1f20
    *v121 = 39;
    uint32_t v123 = v120 + (int32_t)(*(char *)(v1 + 0x5d8f) + 40); // 0x1f3a
    char * v124 = (char *)(v123 % 256 + v4); // 0x1f3f
    unsigned char v125 = *v124; // 0x1f3f
    *v124 = 40;
    uint32_t v126 = v123 + (int32_t)(*(char *)(v1 + 0x5d90) + 41); // 0x1f59
    char * v127 = (char *)(v126 % 256 + v4); // 0x1f5e
    unsigned char v128 = *v127; // 0x1f5e
    *v127 = 41;
    uint32_t v129 = v126 + (int32_t)(*(char *)(v1 + 0x5d91) + 42); // 0x1f78
    char * v130 = (char *)(v129 % 256 + v4); // 0x1f7d
    unsigned char v131 = *v130; // 0x1f7d
    *v130 = 42;
    uint32_t v132 = v129 + (int32_t)(*(char *)(v1 + 0x5d92) + 43); // 0x1f97
    char * v133 = (char *)(v132 % 256 + v4); // 0x1f9c
    unsigned char v134 = *v133; // 0x1f9c
    *v133 = 43;
    uint32_t v135 = v132 + (int32_t)(*(char *)(v1 + 0x5d93) + 44); // 0x1fb6
    char * v136 = (char *)(v135 % 256 + v4); // 0x1fbb
    unsigned char v137 = *v136; // 0x1fbb
    *v136 = 44;
    uint32_t v138 = v135 + (int32_t)(*(char *)(v1 + 0x5d94) + 45); // 0x1fd5
    char * v139 = (char *)(v138 % 256 + v4); // 0x1fda
    unsigned char v140 = *v139; // 0x1fda
    *v139 = 45;
    uint32_t v141 = v138 + (int32_t)(*(char *)(v1 + 0x5d95) + 46); // 0x1ff4
    char * v142 = (char *)(v141 % 256 + v4); // 0x1ff9
    unsigned char v143 = *v142; // 0x1ff9
    *v142 = 46;
    uint32_t v144 = v141 + (int32_t)(*(char *)(v1 + 0x5d96) + 47); // 0x2013
    char * v145 = (char *)(v144 % 256 + v4); // 0x2018
    unsigned char v146 = *v145; // 0x2018
    *v145 = 47;
    uint32_t v147 = v144 + (int32_t)(*(char *)(v1 + 0x5d97) + 48); // 0x2032
    char * v148 = (char *)(v147 % 256 + v4); // 0x2037
    unsigned char v149 = *v148; // 0x2037
    *v148 = 48;
    uint32_t v150 = v147 + (int32_t)(*(char *)(v1 + 0x5d98) + 49); // 0x2051
    char * v151 = (char *)(v150 % 256 + v4); // 0x2056
    unsigned char v152 = *v151; // 0x2056
    *v151 = 49;
    uint32_t v153 = v150 + (int32_t)(*(char *)(v1 + 0x5d99) + 50); // 0x2070
    char * v154 = (char *)(v153 % 256 + v4); // 0x2075
    unsigned char v155 = *v154; // 0x2075
    *v154 = 50;
    uint32_t v156 = v153 + (int32_t)(*(char *)(v1 + 0x5d9a) + 51); // 0x208f
    char * v157 = (char *)(v156 % 256 + v4); // 0x2094
    unsigned char v158 = *v157; // 0x2094
    *v157 = 51;
    uint32_t v159 = v156 + (int32_t)(*(char *)(v1 + 0x5d9b) + 52); // 0x20ae
    char * v160 = (char *)(v159 % 256 + v4); // 0x20b3
    unsigned char v161 = *v160; // 0x20b3
    *v160 = 52;
    uint32_t v162 = v159 + (int32_t)(*(char *)(v1 + 0x5d9c) + 53); // 0x20cd
    char * v163 = (char *)(v162 % 256 + v4); // 0x20d2
    unsigned char v164 = *v163; // 0x20d2
    *v163 = 53;
    uint32_t v165 = v162 + (int32_t)(*(char *)(v1 + 0x5d9d) + 54); // 0x20ec
    char * v166 = (char *)(v165 % 256 + v4); // 0x20f1
    unsigned char v167 = *v166; // 0x20f1
    *v166 = 54;
    uint32_t v168 = v165 + (int32_t)(*(char *)(v1 + 0x5d9e) + 55); // 0x210b
    char * v169 = (char *)(v168 % 256 + v4); // 0x2110
    unsigned char v170 = *v169; // 0x2110
    *v169 = 55;
    uint32_t v171 = v168 + (int32_t)(*(char *)(v1 + 0x5d9f) + 56); // 0x212a
    char * v172 = (char *)(v171 % 256 + v4); // 0x212f
    unsigned char v173 = *v172; // 0x212f
    *v172 = 56;
    uint32_t v174 = v171 + (int32_t)(*(char *)(v1 + 0x5da0) + 57); // 0x2149
    char * v175 = (char *)(v174 % 256 + v4); // 0x214e
    unsigned char v176 = *v175; // 0x214e
    *v175 = 57;
    uint32_t v177 = v174 + (int32_t)(*(char *)(v1 + 0x5da1) + 58); // 0x2168
    char * v178 = (char *)(v177 % 256 + v4); // 0x216d
    unsigned char v179 = *v178; // 0x216d
    *v178 = 58;
    uint32_t v180 = v177 + (int32_t)(*(char *)(v1 + 0x5da2) + 59); // 0x2187
    char * v181 = (char *)(v180 % 256 + v4); // 0x218c
    unsigned char v182 = *v181; // 0x218c
    *v181 = 59;
    uint32_t v183 = v180 + (int32_t)(*(char *)(v1 + 0x5da3) + 60); // 0x21a6
    char * v184 = (char *)(v183 % 256 + v4); // 0x21ab
    unsigned char v185 = *v184; // 0x21ab
    *v184 = 60;
    uint32_t v186 = v183 + (int32_t)(*(char *)(v1 + 0x5da4) + 61); // 0x21c5
    char * v187 = (char *)(v186 % 256 + v4); // 0x21ca
    unsigned char v188 = *v187; // 0x21ca
    *v187 = 61;
    uint32_t v189 = v186 + (int32_t)(*(char *)(v1 + 0x5da5) + 62); // 0x21e4
    char * v190 = (char *)(v189 % 256 + v4); // 0x21e9
    unsigned char v191 = *v190; // 0x21e9
    *v190 = 62;
    uint32_t v192 = v189 + (int32_t)(*(char *)(v1 + 0x5da6) + 63); // 0x2203
    *(char *)(v192 % 256 + v4) = 63;
    uint32_t v193 = v192 + (int32_t)(*(char *)(v1 + 0x5da7) + 64); // 0x2225
    *(char *)(v193 % 256 + v4) = 64;
    uint32_t v194 = v193 + (int32_t)(*(char *)(v1 + 0x5da8) + 65); // 0x224a
    *(char *)(v194 % 256 + v4) = 65;
    uint32_t v195 = v194 + (int32_t)(*(char *)(v1 + 0x5da9) + 66); // 0x226f
    *(char *)(v195 % 256 + v4) = 66;
    uint32_t v196 = v195 + (int32_t)(*(char *)(v1 + 0x5daa) + 67); // 0x2294
    *(char *)(v196 % 256 + v4) = 67;
    uint32_t v197 = v196 + (int32_t)(*(char *)(v1 + 0x5dab) + 68); // 0x22b9
    *(char *)(v197 % 256 + v4) = 68;
    uint32_t v198 = v197 + (int32_t)(*(char *)(v1 + 0x5dac) + 69); // 0x22de
    *(char *)(v198 % 256 + v4) = 69;
    uint32_t v199 = v198 + (int32_t)(*(char *)(v1 + 0x5dad) + 70); // 0x2303
    *(char *)(v199 % 256 + v4) = 70;
    uint32_t v200 = v199 + (int32_t)(*(char *)(v1 + 0x5dae) + 71); // 0x2328
    *(char *)(v200 % 256 + v4) = 71;
    uint32_t v201 = v200 + (int32_t)(*(char *)(v1 + 0x5daf) + 72); // 0x234d
    *(char *)(v201 % 256 + v4) = 72;
    uint32_t v202 = v201 + (int32_t)(*(char *)(v1 + 0x5db0) + 73); // 0x2372
    *(char *)(v202 % 256 + v4) = 73;
    uint32_t v203 = v202 + (int32_t)(*(char *)(v1 + 0x5db1) + 74); // 0x2397
    *(char *)(v203 % 256 + v4) = 74;
    uint32_t v204 = v203 + (int32_t)(*(char *)(v1 + 0x5db2) + 75); // 0x23bc
    *(char *)(v204 % 256 + v4) = 75;
    uint32_t v205 = v204 + (int32_t)(*(char *)(v1 + 0x5db3) + 76); // 0x23e1
    *(char *)(v205 % 256 + v4) = 76;
    uint32_t v206 = v205 + (int32_t)(*(char *)(v1 + 0x5db4) + 77); // 0x2406
    *(char *)(v206 % 256 + v4) = 77;
    uint32_t v207 = v206 + (int32_t)(*(char *)(v1 + 0x5db5) + 78); // 0x242b
    *(char *)(v207 % 256 + v4) = 78;
    uint32_t v208 = v207 + (int32_t)(*(char *)(v1 + 0x5db6) + 79); // 0x2450
    *(char *)(v208 % 256 + v4) = 79;
    uint32_t v209 = v208 + (int32_t)(*(char *)(v1 + 0x5db7) + 80); // 0x2475
    *(char *)(v209 % 256 + v4) = 80;
    uint32_t v210 = v209 + (int32_t)(*(char *)(v1 + 0x5db8) + 81); // 0x249a
    *(char *)(v210 % 256 + v4) = 81;
    uint32_t v211 = v210 + (int32_t)(*(char *)(v1 + 0x5db9) + 82); // 0x24bf
    *(char *)(v211 % 256 + v4) = 82;
    uint32_t v212 = v211 + (int32_t)(*(char *)(v1 + 0x5dba) + 83); // 0x24e4
    *(char *)(v212 % 256 + v4) = 83;
    uint32_t v213 = v212 + (int32_t)(*(char *)(v1 + 0x5dbb) + 84); // 0x2509
    *(char *)(v213 % 256 + v4) = 84;
    uint32_t v214 = v213 + (int32_t)(*(char *)(v1 + 0x5dbc) + 85); // 0x252e
    *(char *)(v214 % 256 + v4) = 85;
    uint32_t v215 = v214 + (int32_t)(*(char *)(v1 + 0x5dbd) + 86); // 0x2553
    *(char *)(v215 % 256 + v4) = 86;
    uint32_t v216 = v215 + (int32_t)(*(char *)(v1 + 0x5dbe) + 87); // 0x2578
    *(char *)(v216 % 256 + v4) = 87;
    uint32_t v217 = v216 + (int32_t)(*(char *)(v1 + 0x5dbf) + 88); // 0x259d
    *(char *)(v217 % 256 + v4) = 88;
    uint32_t v218 = v217 + (int32_t)(*(char *)(v1 + 0x5dc0) + 89); // 0x25c2
    *(char *)(v218 % 256 + v4) = 89;
    uint32_t v219 = v218 + (int32_t)(*(char *)(v1 + 0x5dc1) + 90); // 0x25e7
    *(char *)(v219 % 256 + v4) = 90;
    uint32_t v220 = v219 + (int32_t)(*(char *)(v1 + 0x5dc2) + 91); // 0x260c
    *(char *)(v220 % 256 + v4) = 91;
    uint32_t v221 = v220 + (int32_t)(*(char *)(v1 + 0x5dc3) + 92); // 0x2631
    *(char *)(v221 % 256 + v4) = 92;
    uint32_t v222 = v221 + (int32_t)(*(char *)(v1 + 0x5dc4) + 93); // 0x2656
    *(char *)(v222 % 256 + v4) = 93;
    uint32_t v223 = v222 + (int32_t)(*(char *)(v1 + 0x5dc5) + 94); // 0x267b
    *(char *)(v223 % 256 + v4) = 94;
    uint32_t v224 = v223 + (int32_t)(*(char *)(v1 + 0x5dc6) + 95); // 0x26a0
    *(char *)(v224 % 256 + v4) = 95;
    uint32_t v225 = v224 + (int32_t)(*(char *)(v1 + 0x5dc7) + 96); // 0x26c5
    *(char *)(v225 % 256 + v4) = 96;
    uint32_t v226 = v225 + (int32_t)(*(char *)(v1 + 0x5dc8) + 97); // 0x26ea
    *(char *)(v226 % 256 + v4) = 97;
    uint32_t v227 = v226 + (int32_t)(*(char *)(v1 + 0x5dc9) + 98); // 0x270f
    *(char *)(v227 % 256 + v4) = 98;
    uint32_t v228 = v227 + (int32_t)(*(char *)(v1 + 0x5dca) + 99); // 0x2734
    *(char *)(v228 % 256 + v4) = 99;
    uint32_t v229 = v228 + (int32_t)(*(char *)(v1 + 0x5dcb) + 100); // 0x2759
    *(char *)(v229 % 256 + v4) = 100;
    uint32_t v230 = v229 + (int32_t)(*(char *)(v1 + 0x5dcc) + 101); // 0x277e
    *(char *)(v230 % 256 + v4) = 101;
    uint32_t v231 = v230 + (int32_t)(*(char *)(v1 + 0x5dcd) + 102); // 0x27a3
    *(char *)(v231 % 256 + v4) = 102;
    uint32_t v232 = v231 + (int32_t)(*(char *)(v1 + 0x5dce) + 103); // 0x27c8
    *(char *)(v232 % 256 + v4) = 103;
    uint32_t v233 = v232 + (int32_t)(*(char *)(v1 + 0x5dcf) + 104); // 0x27ed
    *(char *)(v233 % 256 + v4) = 104;
    uint32_t v234 = v233 + (int32_t)(*(char *)(v1 + 0x5dd0) + 105); // 0x2812
    *(char *)(v234 % 256 + v4) = 105;
    uint32_t v235 = v234 + (int32_t)(*(char *)(v1 + 0x5dd1) + 106); // 0x2837
    *(char *)(v235 % 256 + v4) = 106;
    uint32_t v236 = v235 + (int32_t)(*(char *)(v1 + 0x5dd2) + 107); // 0x285c
    *(char *)(v236 % 256 + v4) = 107;
    uint32_t v237 = v236 + (int32_t)(*(char *)(v1 + 0x5dd3) + 108); // 0x2881
    *(char *)(v237 % 256 + v4) = 108;
    uint32_t v238 = v237 + (int32_t)(*(char *)(v1 + 0x5dd4) + 109); // 0x28a6
    *(char *)(v238 % 256 + v4) = 109;
    uint32_t v239 = v238 + (int32_t)(*(char *)(v1 + 0x5dd5) + 110); // 0x28cb
    *(char *)(v239 % 256 + v4) = 110;
    uint32_t v240 = v239 + (int32_t)(*(char *)(v1 + 0x5dd6) + 111); // 0x28f0
    *(char *)(v240 % 256 + v4) = 111;
    uint32_t v241 = v240 + (int32_t)(*(char *)(v1 + 0x5dd7) + 112); // 0x2915
    *(char *)(v241 % 256 + v4) = 112;
    uint32_t v242 = v241 + (int32_t)(*(char *)(v1 + 0x5dd8) + 113); // 0x293a
    *(char *)(v242 % 256 + v4) = 113;
    uint32_t v243 = v242 + (int32_t)(*(char *)(v1 + 0x5dd9) + 114); // 0x295f
    *(char *)(v243 % 256 + v4) = 114;
    uint32_t v244 = v243 + (int32_t)(*(char *)(v1 + 0x5dda) + 115); // 0x2984
    *(char *)(v244 % 256 + v4) = 115;
    uint32_t v245 = v244 + (int32_t)(*(char *)(v1 + 0x5ddb) + 116); // 0x29a9
    *(char *)(v245 % 256 + v4) = 116;
    uint32_t v246 = v245 + (int32_t)(*(char *)(v1 + 0x5ddc) + 117); // 0x29ce
    *(char *)(v246 % 256 + v4) = 117;
    uint32_t v247 = v246 + (int32_t)(*(char *)(v1 + 0x5ddd) + 118); // 0x29f3
    *(char *)(v247 % 256 + v4) = 118;
    uint32_t v248 = v247 + (int32_t)(*(char *)(v1 + 0x5dde) + 119); // 0x2a18
    *(char *)(v248 % 256 + v4) = 119;
    uint32_t v249 = v248 + (int32_t)(*(char *)(v1 + 0x5ddf) + 120); // 0x2a3d
    *(char *)(v249 % 256 + v4) = 120;
    uint32_t v250 = v249 + (int32_t)(*(char *)(v1 + 0x5de0) + 121); // 0x2a62
    *(char *)(v250 % 256 + v4) = 121;
    uint32_t v251 = v250 + (int32_t)(*(char *)(v1 + 0x5de1) + 122); // 0x2a87
    *(char *)(v251 % 256 + v4) = 122;
    uint32_t v252 = v251 + (int32_t)(*(char *)(v1 + 0x5de2) + 123); // 0x2aac
    *(char *)(v252 % 256 + v4) = 123;
    uint32_t v253 = v252 + (int32_t)(*(char *)(v1 + 0x5de3) + 124); // 0x2ad1
    *(char *)(v253 % 256 + v4) = 124;
    uint32_t v254 = v253 + (int32_t)(*(char *)(v1 + 0x5de4) + 125); // 0x2af6
    *(char *)(v254 % 256 + v4) = 125;
    uint32_t v255 = v254 + (int32_t)(*(char *)(v1 + 0x5de5) + 126); // 0x2b1b
    *(char *)(v255 % 256 + v4) = 126;
    uint32_t v256 = v255 + (int32_t)(*(char *)(v1 + 0x5de6) + 127); // 0x2b40
    *(char *)(v256 % 256 + v4) = 127;
    uint32_t v257 = v256 + (int32_t)(*(char *)(v1 + 0x5de7) ^ -128); // 0x2b65
    *(char *)(v257 % 256 + v4) = -128;
    uint32_t v258 = v257 + (int32_t)(*(char *)(v1 + 0x5de8) - 127); // 0x2b8a
    *(char *)(v258 % 256 + v4) = -127;
    uint32_t v259 = v258 + (int32_t)(*(char *)(v1 + 0x5de9) - 126); // 0x2baf
    *(char *)(v259 % 256 + v4) = -126;
    uint32_t v260 = v259 + (int32_t)(*(char *)(v1 + 0x5dea) - 125); // 0x2bd4
    *(char *)(v260 % 256 + v4) = -125;
    uint32_t v261 = v260 + (int32_t)(*(char *)(v1 + 0x5deb) - 124); // 0x2bf9
    *(char *)(v261 % 256 + v4) = -124;
    uint32_t v262 = v261 + (int32_t)(*(char *)(v1 + 0x5dec) - 123); // 0x2c1e
    *(char *)(v262 % 256 + v4) = -123;
    uint32_t v263 = v262 + (int32_t)(*(char *)(v1 + 0x5ded) - 122); // 0x2c43
    *(char *)(v263 % 256 + v4) = -122;
    uint32_t v264 = v263 + (int32_t)(*(char *)(v1 + 0x5dee) - 121); // 0x2c68
    *(char *)(v264 % 256 + v4) = -121;
    uint32_t v265 = v264 + (int32_t)(*(char *)(v1 + 0x5def) - 120); // 0x2c8d
    *(char *)(v265 % 256 + v4) = -120;
    uint32_t v266 = v265 + (int32_t)(*(char *)(v1 + 0x5df0) - 119); // 0x2cb2
    *(char *)(v266 % 256 + v4) = -119;
    uint32_t v267 = v266 + (int32_t)(*(char *)(v1 + 0x5df1) - 118); // 0x2cd7
    *(char *)(v267 % 256 + v4) = -118;
    uint32_t v268 = v267 + (int32_t)(*(char *)(v1 + 0x5df2) - 117); // 0x2cfc
    *(char *)(v268 % 256 + v4) = -117;
    uint32_t v269 = v268 + (int32_t)(*(char *)(v1 + 0x5df3) - 116); // 0x2d21
    *(char *)(v269 % 256 + v4) = -116;
    uint32_t v270 = v269 + (int32_t)(*(char *)(v1 + 0x5df4) - 115); // 0x2d46
    *(char *)(v270 % 256 + v4) = -115;
    uint32_t v271 = v270 + (int32_t)(*(char *)(v1 + 0x5df5) - 114); // 0x2d6b
    *(char *)(v271 % 256 + v4) = -114;
    uint32_t v272 = v271 + (int32_t)(*(char *)(v1 + 0x5df6) - 113); // 0x2d90
    *(char *)(v272 % 256 + v4) = -113;
    uint32_t v273 = v272 + (int32_t)(*(char *)(v1 + 0x5df7) - 112); // 0x2db5
    *(char *)(v273 % 256 + v4) = -112;
    uint32_t v274 = v273 + (int32_t)(*(char *)(v1 + 0x5df8) - 111); // 0x2dda
    *(char *)(v274 % 256 + v4) = -111;
    uint32_t v275 = v274 + (int32_t)(*(char *)(v1 + 0x5df9) - 110); // 0x2dff
    *(char *)(v275 % 256 + v4) = -110;
    uint32_t v276 = v275 + (int32_t)(*(char *)(v1 + 0x5dfa) - 109); // 0x2e24
    *(char *)(v276 % 256 + v4) = -109;
    uint32_t v277 = v276 + (int32_t)(*(char *)(v1 + 0x5dfb) - 108); // 0x2e49
    *(char *)(v277 % 256 + v4) = -108;
    uint32_t v278 = v277 + (int32_t)(*(char *)(v1 + 0x5dfc) - 107); // 0x2e6e
    *(char *)(v278 % 256 + v4) = -107;
    uint32_t v279 = v278 + (int32_t)(*(char *)(v1 + 0x5dfd) - 106); // 0x2e93
    *(char *)(v279 % 256 + v4) = -106;
    uint32_t v280 = v279 + (int32_t)(*(char *)(v1 + 0x5dfe) - 105); // 0x2eb8
    *(char *)(v280 % 256 + v4) = -105;
    uint32_t v281 = v280 + (int32_t)(*(char *)(v1 + 0x5dff) - 104); // 0x2edd
    *(char *)(v281 % 256 + v4) = -104;
    uint32_t v282 = v281 + (int32_t)(*(char *)(v1 + 0x5e00) - 103); // 0x2f02
    *(char *)(v282 % 256 + v4) = -103;
    uint32_t v283 = v282 + (int32_t)(*(char *)(v1 + 0x5e01) - 102); // 0x2f27
    *(char *)(v283 % 256 + v4) = -102;
    uint32_t v284 = v283 + (int32_t)(*(char *)(v1 + 0x5e02) - 101); // 0x2f4c
    *(char *)(v284 % 256 + v4) = -101;
    uint32_t v285 = v284 + (int32_t)(*(char *)(v1 + 0x5e03) - 100); // 0x2f71
    *(char *)(v285 % 256 + v4) = -100;
    uint32_t v286 = v285 + (int32_t)(*(char *)(v1 + 0x5e04) - 99); // 0x2f96
    *(char *)(v286 % 256 + v4) = -99;
    uint32_t v287 = v286 + (int32_t)(*(char *)(v1 + 0x5e05) - 98); // 0x2fbb
    *(char *)(v287 % 256 + v4) = -98;
    uint32_t v288 = v287 + (int32_t)(*(char *)(v1 + 0x5e06) - 97); // 0x2fe0
    *(char *)(v288 % 256 + v4) = -97;
    uint32_t v289 = v288 + (int32_t)(*(char *)(v1 + 0x5e07) - 96); // 0x3005
    *(char *)(v289 % 256 + v4) = -96;
    uint32_t v290 = v289 + (int32_t)(*(char *)(v1 + 0x5e08) - 95); // 0x302a
    *(char *)(v290 % 256 + v4) = -95;
    uint32_t v291 = v290 + (int32_t)(*(char *)(v1 + 0x5e09) - 94); // 0x304f
    *(char *)(v291 % 256 + v4) = -94;
    uint32_t v292 = v291 + (int32_t)(*(char *)(v1 + 0x5e0a) - 93); // 0x3074
    *(char *)(v292 % 256 + v4) = -93;
    uint32_t v293 = v292 + (int32_t)(*(char *)(v1 + 0x5e0b) - 92); // 0x3099
    *(char *)(v293 % 256 + v4) = -92;
    uint32_t v294 = v293 + (int32_t)(*(char *)(v1 + 0x5e0c) - 91); // 0x30be
    *(char *)(v294 % 256 + v4) = -91;
    uint32_t v295 = v294 + (int32_t)(*(char *)(v1 + 0x5e0d) - 90); // 0x30e3
    *(char *)(v295 % 256 + v4) = -90;
    uint32_t v296 = v295 + (int32_t)(*(char *)(v1 + 0x5e0e) - 89); // 0x3108
    *(char *)(v296 % 256 + v4) = -89;
    uint32_t v297 = v296 + (int32_t)(*(char *)(v1 + 0x5e0f) - 88); // 0x312d
    *(char *)(v297 % 256 + v4) = -88;
    uint32_t v298 = v297 + (int32_t)(*(char *)(v1 + 0x5e10) - 87); // 0x3152
    *(char *)(v298 % 256 + v4) = -87;
    uint32_t v299 = v298 + (int32_t)(*(char *)(v1 + 0x5e11) - 86); // 0x3177
    *(char *)(v299 % 256 + v4) = -86;
    uint32_t v300 = v299 + (int32_t)(*(char *)(v1 + 0x5e12) - 85); // 0x319c
    *(char *)(v300 % 256 + v4) = -85;
    uint32_t v301 = v300 + (int32_t)(*(char *)(v1 + 0x5e13) - 84); // 0x31c1
    *(char *)(v301 % 256 + v4) = -84;
    uint32_t v302 = v301 + (int32_t)(*(char *)(v1 + 0x5e14) - 83); // 0x31e6
    *(char *)(v302 % 256 + v4) = -83;
    uint32_t v303 = v302 + (int32_t)(*(char *)(v1 + 0x5e15) - 82); // 0x320b
    *(char *)(v303 % 256 + v4) = -82;
    uint32_t v304 = v303 + (int32_t)(*(char *)(v1 + 0x5e16) - 81); // 0x3230
    *(char *)(v304 % 256 + v4) = -81;
    uint32_t v305 = v304 + (int32_t)(*(char *)(v1 + 0x5e17) - 80); // 0x3255
    *(char *)(v305 % 256 + v4) = -80;
    uint32_t v306 = v305 + (int32_t)(*(char *)(v1 + 0x5e18) - 79); // 0x327a
    *(char *)(v306 % 256 + v4) = -79;
    uint32_t v307 = v306 + (int32_t)(*(char *)(v1 + 0x5e19) - 78); // 0x329f
    *(char *)(v307 % 256 + v4) = -78;
    uint32_t v308 = v307 + (int32_t)(*(char *)(v1 + 0x5e1a) - 77); // 0x32c4
    *(char *)(v308 % 256 + v4) = -77;
    uint32_t v309 = v308 + (int32_t)(*(char *)(v1 + 0x5e1b) - 76); // 0x32e9
    *(char *)(v309 % 256 + v4) = -76;
    uint32_t v310 = v309 + (int32_t)(*(char *)(v1 + 0x5e1c) - 75); // 0x330e
    *(char *)(v310 % 256 + v4) = -75;
    uint32_t v311 = v310 + (int32_t)(*(char *)(v1 + 0x5e1d) - 74); // 0x3333
    *(char *)(v311 % 256 + v4) = -74;
    uint32_t v312 = v311 + (int32_t)(*(char *)(v1 + 0x5e1e) - 73); // 0x3358
    *(char *)(v312 % 256 + v4) = -73;
    uint32_t v313 = v312 + (int32_t)(*(char *)(v1 + 0x5e1f) - 72); // 0x337d
    *(char *)(v313 % 256 + v4) = -72;
    uint32_t v314 = v313 + (int32_t)(*(char *)(v1 + 0x5e20) - 71); // 0x33a2
    *(char *)(v314 % 256 + v4) = -71;
    uint32_t v315 = v314 + (int32_t)(*(char *)(v1 + 0x5e21) - 70); // 0x33c7
    *(char *)(v315 % 256 + v4) = -70;
    uint32_t v316 = v315 + (int32_t)(*(char *)(v1 + 0x5e22) - 69); // 0x33ec
    *(char *)(v316 % 256 + v4) = -69;
    uint32_t v317 = v316 + (int32_t)(*(char *)(v1 + 0x5e23) - 68); // 0x3411
    *(char *)(v317 % 256 + v4) = -68;
    uint32_t v318 = v317 + (int32_t)(*(char *)(v1 + 0x5e24) - 67); // 0x3436
    *(char *)(v318 % 256 + v4) = -67;
    uint32_t v319 = v318 + (int32_t)(*(char *)(v1 + 0x5e25) - 66); // 0x345b
    *(char *)(v319 % 256 + v4) = -66;
    uint32_t v320 = v319 + (int32_t)(*(char *)(v1 + 0x5e26) - 65); // 0x3480
    *(char *)(v320 % 256 + v4) = -65;
    uint32_t v321 = v320 + (int32_t)(*(char *)(v1 + 0x5e27) - 64); // 0x34a5
    *(char *)(v321 % 256 + v4) = -64;
    uint32_t v322 = v321 + (int32_t)(*(char *)(v1 + 0x5e28) - 63); // 0x34ca
    *(char *)(v322 % 256 + v4) = -63;
    uint32_t v323 = v322 + (int32_t)(*(char *)(v1 + 0x5e29) - 62); // 0x34ef
    *(char *)(v323 % 256 + v4) = -62;
    uint32_t v324 = v323 + (int32_t)(*(char *)(v1 + 0x5e2a) - 61); // 0x3514
    *(char *)(v324 % 256 + v4) = -61;
    uint32_t v325 = v324 + (int32_t)(*(char *)(v1 + 0x5e2b) - 60); // 0x3539
    *(char *)(v325 % 256 + v4) = -60;
    uint32_t v326 = v325 + (int32_t)(*(char *)(v1 + 0x5e2c) - 59); // 0x355e
    *(char *)(v326 % 256 + v4) = -59;
    uint32_t v327 = v326 + (int32_t)(*(char *)(v1 + 0x5e2d) - 58); // 0x3583
    *(char *)(v327 % 256 + v4) = -58;
    uint32_t v328 = v327 + (int32_t)(*(char *)(v1 + 0x5e2e) - 57); // 0x35a8
    *(char *)(v328 % 256 + v4) = -57;
    uint32_t v329 = v328 + (int32_t)(*(char *)(v1 + 0x5e2f) - 56); // 0x35cd
    *(char *)(v329 % 256 + v4) = -56;
    uint32_t v330 = v329 + (int32_t)(*(char *)(v1 + 0x5e30) - 55); // 0x35f2
    *(char *)(v330 % 256 + v4) = -55;
    uint32_t v331 = v330 + (int32_t)(*(char *)(v1 + 0x5e31) - 54); // 0x3617
    *(char *)(v331 % 256 + v4) = -54;
    uint32_t v332 = v331 + (int32_t)(*(char *)(v1 + 0x5e32) - 53); // 0x363c
    *(char *)(v332 % 256 + v4) = -53;
    uint32_t v333 = v332 + (int32_t)(*(char *)(v1 + 0x5e33) - 52); // 0x3661
    *(char *)(v333 % 256 + v4) = -52;
    uint32_t v334 = v333 + (int32_t)(*(char *)(v1 + 0x5e34) - 51); // 0x3686
    *(char *)(v334 % 256 + v4) = -51;
    uint32_t v335 = v334 + (int32_t)(*(char *)(v1 + 0x5e35) - 50); // 0x36ab
    *(char *)(v335 % 256 + v4) = -50;
    uint32_t v336 = v335 + (int32_t)(*(char *)(v1 + 0x5e36) - 49); // 0x36d0
    *(char *)(v336 % 256 + v4) = -49;
    uint32_t v337 = v336 + (int32_t)(*(char *)(v1 + 0x5e37) - 48); // 0x36f5
    *(char *)(v337 % 256 + v4) = -48;
    uint32_t v338 = v337 + (int32_t)(*(char *)(v1 + 0x5e38) - 47); // 0x371a
    *(char *)(v338 % 256 + v4) = -47;
    uint32_t v339 = v338 + (int32_t)(*(char *)(v1 + 0x5e39) - 46); // 0x373f
    *(char *)(v339 % 256 + v4) = -46;
    uint32_t v340 = v339 + (int32_t)(*(char *)(v1 + 0x5e3a) - 45); // 0x3764
    *(char *)(v340 % 256 + v4) = -45;
    uint32_t v341 = v340 + (int32_t)(*(char *)(v1 + 0x5e3b) - 44); // 0x3789
    *(char *)(v341 % 256 + v4) = -44;
    uint32_t v342 = v341 + (int32_t)(*(char *)(v1 + 0x5e3c) - 43); // 0x37ae
    *(char *)(v342 % 256 + v4) = -43;
    uint32_t v343 = v342 + (int32_t)(*(char *)(v1 + 0x5e3d) - 42); // 0x37d3
    *(char *)(v343 % 256 + v4) = -42;
    uint32_t v344 = v343 + (int32_t)(*(char *)(v1 + 0x5e3e) - 41); // 0x37f8
    *(char *)(v344 % 256 + v4) = -41;
    uint32_t v345 = v344 + (int32_t)(*(char *)(v1 + 0x5e3f) - 40); // 0x381d
    *(char *)(v345 % 256 + v4) = -40;
    uint32_t v346 = v345 + (int32_t)(*(char *)(v1 + 0x5e40) - 39); // 0x3842
    *(char *)(v346 % 256 + v4) = -39;
    uint32_t v347 = v346 + (int32_t)(*(char *)(v1 + 0x5e41) - 38); // 0x3867
    *(char *)(v347 % 256 + v4) = -38;
    uint32_t v348 = v347 + (int32_t)(*(char *)(v1 + 0x5e42) - 37); // 0x388c
    *(char *)(v348 % 256 + v4) = -37;
    uint32_t v349 = v348 + (int32_t)(*(char *)(v1 + 0x5e43) - 36); // 0x38b1
    *(char *)(v349 % 256 + v4) = -36;
    uint32_t v350 = v349 + (int32_t)(*(char *)(v1 + 0x5e44) - 35); // 0x38d6
    *(char *)(v350 % 256 + v4) = -35;
    uint32_t v351 = v350 + (int32_t)(*(char *)(v1 + 0x5e45) - 34); // 0x38fb
    *(char *)(v351 % 256 + v4) = -34;
    uint32_t v352 = v351 + (int32_t)(*(char *)(v1 + 0x5e46) - 33); // 0x3920
    *(char *)(v352 % 256 + v4) = -33;
    uint32_t v353 = v352 + (int32_t)(*(char *)(v1 + 0x5e47) - 32); // 0x3945
    *(char *)(v353 % 256 + v4) = -32;
    uint32_t v354 = v353 + (int32_t)(*(char *)(v1 + 0x5e48) - 31); // 0x396a
    *(char *)(v354 % 256 + v4) = -31;
    uint32_t v355 = v354 + (int32_t)(*(char *)(v1 + 0x5e49) - 30); // 0x398f
    *(char *)(v355 % 256 + v4) = -30;
    uint32_t v356 = v355 + (int32_t)(*(char *)(v1 + 0x5e4a) - 29); // 0x39b4
    *(char *)(v356 % 256 + v4) = -29;
    uint32_t v357 = v356 + (int32_t)(*(char *)(v1 + 0x5e4b) - 28); // 0x39d9
    *(char *)(v357 % 256 + v4) = -28;
    uint32_t v358 = v357 + (int32_t)(*(char *)(v1 + 0x5e4c) - 27); // 0x39fe
    *(char *)(v358 % 256 + v4) = -27;
    uint32_t v359 = v358 + (int32_t)(*(char *)(v1 + 0x5e4d) - 26); // 0x3a23
    *(char *)(v359 % 256 + v4) = -26;
    uint32_t v360 = v359 + (int32_t)(*(char *)(v1 + 0x5e4e) - 25); // 0x3a48
    *(char *)(v360 % 256 + v4) = -25;
    uint32_t v361 = v360 + (int32_t)(*(char *)(v1 + 0x5e4f) - 24); // 0x3a6d
    *(char *)(v361 % 256 + v4) = -24;
    uint32_t v362 = v361 + (int32_t)(*(char *)(v1 + 0x5e50) - 23); // 0x3a92
    *(char *)(v362 % 256 + v4) = -23;
    uint32_t v363 = v362 + (int32_t)(*(char *)(v1 + 0x5e51) - 22); // 0x3ab7
    *(char *)(v363 % 256 + v4) = -22;
    uint32_t v364 = v363 + (int32_t)(*(char *)(v1 + 0x5e52) - 21); // 0x3adc
    *(char *)(v364 % 256 + v4) = -21;
    uint32_t v365 = v364 + (int32_t)(*(char *)(v1 + 0x5e53) - 20); // 0x3b01
    *(char *)(v365 % 256 + v4) = -20;
    uint32_t v366 = v365 + (int32_t)(*(char *)(v1 + 0x5e54) - 19); // 0x3b26
    *(char *)(v366 % 256 + v4) = -19;
    uint32_t v367 = v366 + (int32_t)(*(char *)(v1 + 0x5e55) - 18); // 0x3b4b
    *(char *)(v367 % 256 + v4) = -18;
    uint32_t v368 = v367 + (int32_t)(*(char *)(v1 + 0x5e56) - 17); // 0x3b70
    *(char *)(v368 % 256 + v4) = -17;
    uint32_t v369 = v368 + (int32_t)(*(char *)(v1 + 0x5e57) - 16); // 0x3b95
    *(char *)(v369 % 256 + v4) = -16;
    uint32_t v370 = v369 + (int32_t)(*(char *)(v1 + 0x5e58) - 15); // 0x3bba
    *(char *)(v370 % 256 + v4) = -15;
    uint32_t v371 = v370 + (int32_t)(*(char *)(v1 + 0x5e59) - 14); // 0x3bdf
    *(char *)(v371 % 256 + v4) = -14;
    uint32_t v372 = v371 + (int32_t)(*(char *)(v1 + 0x5e5a) - 13); // 0x3c04
    *(char *)(v372 % 256 + v4) = -13;
    uint32_t v373 = v372 + (int32_t)(*(char *)(v1 + 0x5e5b) - 12); // 0x3c29
    *(char *)(v373 % 256 + v4) = -12;
    uint32_t v374 = v373 + (int32_t)(*(char *)(v1 + 0x5e5c) - 11); // 0x3c4e
    *(char *)(v374 % 256 + v4) = -11;
    uint32_t v375 = v374 + (int32_t)(*(char *)(v1 + 0x5e5d) - 10); // 0x3c73
    *(char *)(v375 % 256 + v4) = -10;
    uint32_t v376 = v375 + (int32_t)(*(char *)(v1 + 0x5e5e) - 9); // 0x3c98
    *(char *)(v376 % 256 + v4) = -9;
    uint32_t v377 = v376 + (int32_t)(*(char *)(v1 + 0x5e5f) - 8); // 0x3cbd
    *(char *)(v377 % 256 + v4) = -8;
    uint32_t v378 = v377 + (int32_t)(*(char *)(v1 + 0x5e60) - 7); // 0x3ce2
    *(char *)(v378 % 256 + v4) = -7;
    uint32_t v379 = v378 + (int32_t)(*(char *)(v1 + 0x5e61) - 6); // 0x3d07
    *(char *)(v379 % 256 + v4) = -6;
    uint32_t v380 = v379 + (int32_t)(*(char *)(v1 + 0x5e62) - 5); // 0x3d2c
    *(char *)(v380 % 256 + v4) = -5;
    uint32_t v381 = v380 + (int32_t)(*(char *)(v1 + 0x5e63) - 4); // 0x3d51
    *(char *)(v381 % 256 + v4) = -4;
    uint32_t v382 = v381 + (int32_t)(*(char *)(v1 + 0x5e64) - 3); // 0x3d76
    *(char *)(v382 % 256 + v4) = -3;
    uint32_t v383 = v382 + (int32_t)(*(char *)(v1 + 0x5e65) - 2); // 0x3d9b
    *(char *)(v383 % 256 + v4) = -2;
    char v384 = *(char *)(v1 + 0x5e66); // 0x3dba
    *(char *)((v383 + (int32_t)(v384 - 1)) % 256 + v4) = -1;
    *(char *)(v4 + v8) = v7;
    uint32_t v385 = (int32_t)v11 + v8; // 0x3e05
    *(char *)(v385 % 256 + v4) = v11;
    uint32_t v386 = v385 + (int32_t)v14; // 0x3e32
    *(char *)(v386 % 256 + v4) = v14;
    uint32_t v387 = v386 + (int32_t)v17; // 0x3e5f
    *(char *)(v387 % 256 + v4) = v17;
    uint32_t v388 = v387 + (int32_t)v20; // 0x3e8c
    *(char *)(v388 % 256 + v4) = v20;
    uint32_t v389 = v388 + (int32_t)v23; // 0x3eb9
    *(char *)(v389 % 256 + v4) = v23;
    uint32_t v390 = v389 + (int32_t)v26; // 0x3ee6
    *(char *)(v390 % 256 + v4) = v26;
    uint32_t v391 = v390 + (int32_t)v29; // 0x3f13
    *(char *)(v391 % 256 + v4) = v29;
    uint32_t v392 = v391 + (int32_t)v32; // 0x3f40
    *(char *)(v392 % 256 + v4) = v32;
    uint32_t v393 = v392 + (int32_t)v35; // 0x3f6d
    *(char *)(v393 % 256 + v4) = v35;
    uint32_t v394 = v393 + (int32_t)v38; // 0x3f9a
    *(char *)(v394 % 256 + v4) = v38;
    uint32_t v395 = v394 + (int32_t)v41; // 0x3fc7
    *(char *)(v395 % 256 + v4) = v41;
    uint32_t v396 = v395 + (int32_t)v44; // 0x3ff4
    *(char *)(v396 % 256 + v4) = v44;
    uint32_t v397 = v396 + (int32_t)v47; // 0x4021
    *(char *)(v397 % 256 + v4) = v47;
    uint32_t v398 = v397 + (int32_t)v50; // 0x404e
    *(char *)(v398 % 256 + v4) = v50;
    uint32_t v399 = v398 + (int32_t)v53; // 0x407b
    *(char *)(v399 % 256 + v4) = v53;
    uint32_t v400 = v399 + (int32_t)v56; // 0x40a8
    *(char *)(v400 % 256 + v4) = v56;
    uint32_t v401 = v400 + (int32_t)v59; // 0x40d5
    *(char *)(v401 % 256 + v4) = v59;
    uint32_t v402 = v401 + (int32_t)v62; // 0x4102
    *(char *)(v402 % 256 + v4) = v62;
    uint32_t v403 = v402 + (int32_t)v65; // 0x412f
    *(char *)(v403 % 256 + v4) = v65;
    uint32_t v404 = v403 + (int32_t)v68; // 0x415c
    *(char *)(v404 % 256 + v4) = v68;
    uint32_t v405 = v404 + (int32_t)v71; // 0x4189
    *(char *)(v405 % 256 + v4) = v71;
    uint32_t v406 = v405 + (int32_t)v74; // 0x41b6
    *(char *)(v406 % 256 + v4) = v74;
    uint32_t v407 = v406 + (int32_t)v77; // 0x41e3
    *(char *)(v407 % 256 + v4) = v77;
    uint32_t v408 = v407 + (int32_t)v80; // 0x4210
    *(char *)(v408 % 256 + v4) = v80;
    uint32_t v409 = v408 + (int32_t)v83; // 0x423d
    *(char *)(v409 % 256 + v4) = v83;
    uint32_t v410 = v409 + (int32_t)v86; // 0x426a
    *(char *)(v410 % 256 + v4) = v86;
    uint32_t v411 = v410 + (int32_t)v89; // 0x4297
    *(char *)(v411 % 256 + v4) = v89;
    uint32_t v412 = v411 + (int32_t)v92; // 0x42c4
    *(char *)(v412 % 256 + v4) = v92;
    uint32_t v413 = v412 + (int32_t)v95; // 0x42f1
    *(char *)(v413 % 256 + v4) = v95;
    uint32_t v414 = v413 + (int32_t)v98; // 0x431e
    *(char *)(v414 % 256 + v4) = v98;
    uint32_t v415 = v414 + (int32_t)v101; // 0x434b
    *(char *)(v415 % 256 + v4) = v101;
    uint32_t v416 = v415 + (int32_t)v104; // 0x4378
    *(char *)(v416 % 256 + v4) = v104;
    uint32_t v417 = v416 + (int32_t)v107; // 0x43a5
    *(char *)(v417 % 256 + v4) = v107;
    uint32_t v418 = v417 + (int32_t)v110; // 0x43d2
    *(char *)(v418 % 256 + v4) = v110;
    uint32_t v419 = v418 + (int32_t)v113; // 0x43ff
    *(char *)(v419 % 256 + v4) = v113;
    uint32_t v420 = v419 + (int32_t)v116; // 0x442c
    *(char *)(v420 % 256 + v4) = v116;
    uint32_t v421 = v420 + (int32_t)v119; // 0x4459
    *(char *)(v421 % 256 + v4) = v119;
    uint32_t v422 = v421 + (int32_t)v122; // 0x4486
    *(char *)(v422 % 256 + v4) = v122;
    uint32_t v423 = v422 + (int32_t)v125; // 0x44b3
    *(char *)(v423 % 256 + v4) = v125;
    uint32_t v424 = v423 + (int32_t)v128; // 0x44e0
    *(char *)(v424 % 256 + v4) = v128;
    uint32_t v425 = v424 + (int32_t)v131; // 0x450d
    *(char *)(v425 % 256 + v4) = v131;
    uint32_t v426 = v425 + (int32_t)v134; // 0x453a
    *(char *)(v426 % 256 + v4) = v134;
    uint32_t v427 = v426 + (int32_t)v137; // 0x4567
    *(char *)(v427 % 256 + v4) = v137;
    uint32_t v428 = v427 + (int32_t)v140; // 0x4594
    *(char *)(v428 % 256 + v4) = v140;
    uint32_t v429 = v428 + (int32_t)v143; // 0x45c1
    *(char *)(v429 % 256 + v4) = v143;
    uint32_t v430 = v429 + (int32_t)v146; // 0x45ee
    *(char *)(v430 % 256 + v4) = v146;
    uint32_t v431 = v430 + (int32_t)v149; // 0x461b
    *(char *)(v431 % 256 + v4) = v149;
    uint32_t v432 = v431 + (int32_t)v152; // 0x4648
    *(char *)(v432 % 256 + v4) = v152;
    uint32_t v433 = v432 + (int32_t)v155; // 0x4675
    *(char *)(v433 % 256 + v4) = v155;
    uint32_t v434 = v433 + (int32_t)v158; // 0x46a2
    *(char *)(v434 % 256 + v4) = v158;
    uint32_t v435 = v434 + (int32_t)v161; // 0x46cf
    *(char *)(v435 % 256 + v4) = v161;
    uint32_t v436 = v435 + (int32_t)v164; // 0x46fc
    *(char *)(v436 % 256 + v4) = v164;
    uint32_t v437 = v436 + (int32_t)v167; // 0x4729
    *(char *)(v437 % 256 + v4) = v167;
    uint32_t v438 = v437 + (int32_t)v170; // 0x4756
    *(char *)(v438 % 256 + v4) = v170;
    uint32_t v439 = v438 + (int32_t)v173; // 0x4783
    *(char *)(v439 % 256 + v4) = v173;
    uint32_t v440 = v439 + (int32_t)v176; // 0x47b0
    *(char *)(v440 % 256 + v4) = v176;
    uint32_t v441 = v440 + (int32_t)v179; // 0x47dd
    *(char *)(v441 % 256 + v4) = v179;
    uint32_t v442 = v441 + (int32_t)v182; // 0x480a
    *(char *)(v442 % 256 + v4) = v182;
    uint32_t v443 = v442 + (int32_t)v185; // 0x4837
    *(char *)(v443 % 256 + v4) = v185;
    uint32_t v444 = v443 + (int32_t)v188; // 0x4864
    *(char *)(v444 % 256 + v4) = v188;
    *(char *)((v444 + (int32_t)v191) % 256 + v4) = v191;
    v3 = 32;
    return printf((char *)(v1 + 0x3d01));
}

// Address range: 0x48de - 0x490b
int main(int argc, char ** argv) {
    // 0x48de
    multiplication_table(17);
    decrypt_message();
    return 0;
}

// Address range: 0x490c - 0x4920
int32_t _fini(void) {
    // 0x490c
    int32_t v1; // 0x490c
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (12.2.0)
// Detected functions: 16

