// tmp_smq5ozl_TEXT_text_startup.c
// Generated by decompiling tmp_smq5ozl
// using Reko decompiler version 0.11.6.0.

#include "tmp_smq5ozl.h"

// 0000000100000E92: void main()
void main()
{
	it_crowd();
	printf("Some calculation returned %d.\n");
}

// tmp_smq5ozl_TEXT_text.c
// Generated by decompiling tmp_smq5ozl
// using Reko decompiler version 0.11.6.0.

#include "tmp_smq5ozl.h"

// 0000000100000D4D: void it_crowd()
// Called from:
//      main
void it_crowd()
{
	puts("Are you feeling stressed, Jen?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Are you sure?\n");
	puts("Well, I guess you're not.\n");
	puts("Well done, Jen.\n");
}

// 0000000100000E53: void some_calculation()
void some_calculation()
{
}

// tmp_smq5ozl_TEXT_stubs.c
// Generated by decompiling tmp_smq5ozl
// using Reko decompiler version 0.11.6.0.

#include "tmp_smq5ozl.h"

// 0000000100000EC0: void printf(Register (ptr64 char) rdi)
// Called from:
//      main
void printf(char * rdi)
{
	printf(rdi, 0x00);
}

// 0000000100000EC6: void puts(Register (ptr64 char) rdi)
// Called from:
//      it_crowd
void puts(char * rdi)
{
	puts(rdi);
}

// tmp_smq5ozl.globals.c
// Generated by decompiling tmp_smq5ozl
// using Reko decompiler version 0.11.6.0.

#include "tmp_smq5ozl.h"

<anonymous> * __imp__dyld_stub_binder; // 0000000000001000
<anonymous> * __imp__printf; // 0000000000002000
<anonymous> * __imp__puts; // 0000000000002008
