// Generated by Rec Studio 4 - build Sep 23 2015

some_calculation()
{// addr = 0x0001057C
    asm("ANDLS	r2, r0, r0, ROR #5");
    asm("ANDEQS	r8, r0, r0, ROR #5");
    asm("Undefined instruction");
    asm("BICEQ	r8, r0, r0, ROR #7");
    asm("Undefined instruction");
    asm("Undefined instruction");
    asm("Undefined instruction");
    asm("BICEQ	r8, r0, r0, ROR #7");
    asm("Undefined instruction");
    asm("Undefined instruction");
    asm("Undefined instruction");
    asm("BICEQ	r8, r0, r0, ROR #7");
    asm("STCLS	p0, c2, [ip], #-&380");
    asm("STCEQ	p0, c8, [r0], #-&380");
    asm("CDPNE	p15, 15, c2, c15, c1, 7");
}

main()
{// addr = 0x000105B8
    asm("SUBNE	r2, r0, r9, ROR #27");
}

main()
{// addr = 0x000105B8
    asm("SUBNE	r2, r0, r9, ROR #27");
}

// Statistics:
//       0 Register nodes
//       0 Temporaries nodes
//       0 Casts
//      16 Statements
//       0 Labels
//       0 Gotos
//       2 Blocks
//      16 Nodes
//      16 Assembly nodes
//       0 Unknown Types


Total time: 0 seconds.
