// Generated by Rec Studio 4 - build Sep 23 2015

_it_crowd()
{// addr = 0x0000000100000D40
    L0000000100000EBC();
    __rbx = "Are you sure?\n";
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    L0000000100000EBC();
    _pop(__rbx);
    goto L0000000100000EBC;
}

_main(
    _unknown_ __rax,                       // r53
    _unknown_ __rsi                        // r58
)
{// addr = 0x0000000100000E90
    __rax = __rax;
    _it_crowd();
    L0000000100000EB6();
}

L0000000100000EB6()
{
    goto ( *4294975488);
}

L0000000100000EBC()
{
    goto ( *4294975496);
}

L0000000100000EBC()
{
    goto ( *4294975496);
}

// Statistics:
//       4 Register nodes
//       0 Temporaries nodes
//       0 Casts
//      37 Statements
//       0 Labels
//       0 Gotos
//       4 Blocks
//      80 Nodes
//       0 Assembly nodes
//       2 Unknown Types


Total time: 0 seconds.
