// tmps1cfeudc_text.c
// Generated by decompiling tmps1cfeudc
// using Reko decompiler version 0.11.6.0.

#include "tmps1cfeudc.h"

// 0001038C: void _start(Stack int32 dwArg00, Stack (ptr32 char) ptrArg04, Stack (ptr32 Eq_9) ptrArg08, Stack (ptr32 Eq_10) ptrArg0C, Stack (ptr32 void) ptrArg10)
void _start(int32 dwArg00, char * ptrArg04, void (* ptrArg08)(), void (* ptrArg0C)(), void * ptrArg10)
{
	__libc_start_main(g_ptr103B8, dwArg00, &ptrArg04, null, ptrArg08, ptrArg0C, ptrArg10);
	abort();
}

int32 (* g_ptr103B8)(int32 r0, char ** r1, char ** r2) = main; // 000103B8
// 000103BC: void call_weak_fn()
// Called from:
//      _init
void call_weak_fn()
{
	if (((char *) &g_t103CC + g_dw103D8)[g_dw103DC] == 0x00)
		return;
	fn00010374();
}

<unknown> g_t103CC = // 000103CC;
int32 g_dw103D8 = 68660; // 000103D8
int32 g_dw103DC = 32; // 000103DC
// 000103E0: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
	if (g_dw10404 == g_dw10400)
		return;
	<anonymous> * r3_10 = g_ptr10408;
	if (r3_10 == null)
		return;
	r3_10();
}

word32 g_dw10400 = 135212; // 00010400
word32 g_dw10404 = 135212; // 00010404
<anonymous> * g_ptr10408 = null; // 00010408
// 0001040C: void register_tm_clones()
// Called from:
//      frame_dummy
void register_tm_clones()
{
	Eq_56 r3_8 = g_dw1043C - g_dw10438;
	if ((r3_8 >> 31) + (r3_8 >> 2) >> 1 == 0x00)
		return;
	<anonymous> * r3_14 = g_ptr10440;
	if (r3_14 == null)
		return;
	r3_14();
}

word32 g_dw10438 = 135212; // 00010438
word32 g_dw1043C = 135212; // 0001043C
<anonymous> * g_ptr10440 = null; // 00010440
// 00010444: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	byte * r4_9 = g_ptr10468;
	if ((word32) *r4_9 != 0x00)
		return;
	deregister_tm_clones();
	*r4_9 = 0x01;
}

byte * g_ptr10468 = &g_b2102C; // 00010468
// 0001046C: void frame_dummy()
void frame_dummy()
{
	register_tm_clones();
}

// 00010470: void count_sheep()
// Called from:
//      main
void count_sheep()
{
	printf("%d ", 0x00);
	printf("%d ", 0x01);
	printf("%d ", 0x02);
	printf("%d ", 0x03);
	printf("%d ", 0x04);
	printf("%d ", 0x05);
	printf("%d ", 0x06);
	printf("%d ", 0x07);
	printf("%d ", 0x08);
	printf("%d ", 0x09);
	printf("%d ", 0x0A);
	printf("%d ", 11);
	printf("%d ", 0x0C);
	printf("%d ", 0x0D);
	printf("%d ", 0x0E);
	printf("%d ", 0x0F);
	printf("%d ", 0x10);
	printf("%d ", 0x11);
	printf("%d ", 0x12);
	printf("%d ", 0x13);
	printf("%d ", 0x14);
	printf("%d ", 0x15);
	printf("%d ", 22);
	printf("%d ", 0x17);
	printf("%d ", 0x18);
	printf("%d ", 0x19);
	printf("%d ", 0x1A);
	printf("%d ", 0x1B);
	printf("%d ", 0x1C);
	printf("%d ", 0x1D);
	printf("%d ", 0x1E);
	printf("%d ", 0x1F);
	printf("%d ", 0x20);
	printf("%d ", 33);
	printf("%d ", 0x22);
	printf("%d ", 0x23);
	printf("%d ", 0x24);
	printf("%d ", 0x25);
	printf("%d ", 0x26);
	printf("%d ", 0x27);
	printf("%d ", 0x28);
	printf("%d ", 0x29);
	printf("%d ", 0x2A);
	printf("%d ", 0x2B);
	printf("%d ", 44);
	printf("%d ", 0x2D);
	printf("%d ", 0x2E);
	printf("%d ", 0x2F);
	printf("%d ", 0x30);
	printf("%d ", 0x31);
	printf("%d ", 0x32);
	printf("%d ", 0x33);
	printf("%d ", 0x34);
	printf("%d ", 0x35);
	printf("%d ", 0x36);
	printf("%d ", 55);
	printf("%d ", 0x38);
	printf("%d ", 0x39);
	printf("%d ", 0x3A);
	printf("%d ", 0x3B);
	printf("%d ", 0x3C);
	printf("%d ", 0x3D);
	printf("%d ", 0x3E);
	printf("%d ", 0x3F);
	printf("%d ", 0x40);
	printf("%d ", 0x41);
	printf("%d ", 66);
	printf("%d ", 0x43);
	printf("%d ", 0x44);
	printf("%d ", 0x45);
	printf("(nice) ");
	printf("%d ", 0x46);
	printf("%d ", 0x47);
	printf("%d ", 0x48);
	printf("%d ", 0x49);
	printf("%d ", 0x4A);
	printf("%d ", 0x4B);
	printf("%d ", 0x4C);
	printf("%d ", 77);
	printf("%d ", 0x4E);
	printf("%d ", 0x4F);
	printf("%d ", 0x50);
	printf("%d ", 0x51);
	printf("%d ", 0x52);
	printf("%d ", 0x53);
	printf("%d ", 0x54);
	printf("%d ", 0x55);
	printf("%d ", 0x56);
	printf("%d ", 0x57);
	printf("%d ", 88);
	printf("%d ", 0x59);
	printf("%d ", 0x5A);
	printf("%d ", 0x5B);
	printf("%d ", 0x5C);
	printf("%d ", 0x5D);
	printf("%d ", 0x5E);
	printf("%d ", 0x5F);
	printf("%d ", 0x60);
	printf("%d ", 0x61);
	printf("%d ", 0x62);
	printf("%d ", 99);
	puts("ZzZzZz...");
}

// 00010948: void short_multiplication_table(Register int32 r0)
// Called from:
//      main
void short_multiplication_table(int32 r0)
{
	printf("%2d \xC3\x97 %3d = %4d\t", 0x00, r0, 0x00);
	printf("%2d \xC3\x97 %3d = %4d\t", 0x01, r0, r0);
	printf("%2d \xC3\x97 %3d = %4d\t", 0x02, r0, r0 << 1);
	printf("%2d \xC3\x97 %3d = %4d\n", 0x03, r0, r0 * 0x03);
	printf("%2d \xC3\x97 %3d = %4d\t", 0x04, r0, r0 << 2);
	printf("%2d \xC3\x97 %3d = %4d\t", 0x05, r0, r0 * 0x05);
	printf("%2d \xC3\x97 %3d = %4d\t", 0x06, r0, r0 * 0x06);
	printf("%2d \xC3\x97 %3d = %4d\n", 0x07, r0, r0 * 0x07);
	printf("%2d \xC3\x97 %3d = %4d\t", 0x08, r0, r0 << 3);
	printf("%2d \xC3\x97 %3d = %4d\t", 0x09, r0, r0 * 0x09);
	printf("%2d \xC3\x97 %3d = %4d\t", 0x0A, r0, r0 * 0x0A);
	printf("%2d \xC3\x97 %3d = %4d\n", 11, r0, r0 * 11);
	printf("%2d \xC3\x97 %3d = %4d\t", 0x0C, r0, r0 * 0x0C);
	printf("%2d \xC3\x97 %3d = %4d\t", 0x0D, r0, r0 * 0x0D);
	printf("%2d \xC3\x97 %3d = %4d\t", 0x0E, r0, r0 * 0x0E);
	printf("%2d \xC3\x97 %3d = %4d\n", 0x0F, r0, r0 * 0x0F);
	printf("%2d \xC3\x97 %3d = %4d\t", 0x10, r0, r0 << 4);
	printf("%2d \xC3\x97 %3d = %4d\t", 0x11, r0, r0 * 0x11);
	printf("%2d \xC3\x97 %3d = %4d\t", 0x12, r0, r0 * 0x12);
	printf("%2d \xC3\x97 %3d = %4d\n", 0x13, r0, r0 * 0x13);
}

// 00010AF4: void main()
void main()
{
	short_multiplication_table(0x13);
	count_sheep();
}

// tmps1cfeudc_fini.c
// Generated by decompiling tmps1cfeudc
// using Reko decompiler version 0.11.6.0.

#include "tmps1cfeudc.h"

// 00010B0C: void _fini()
void _fini()
{
}

// tmps1cfeudc_rodata.c
// Generated by decompiling tmps1cfeudc
// using Reko decompiler version 0.11.6.0.

#include "tmps1cfeudc.h"

word32 _IO_stdin_used = 0x00020001; // 00010B14
char g_str10BB4[] = "ZzZzZz..."; // 00010BB4
// tmps1cfeudc_init.c
// Generated by decompiling tmps1cfeudc
// using Reko decompiler version 0.11.6.0.

#include "tmps1cfeudc.h"

// 00010330: void _init()
void _init()
{
	call_weak_fn();
}

// tmps1cfeudc_plt.c
// Generated by decompiling tmps1cfeudc
// using Reko decompiler version 0.11.6.0.

#include "tmps1cfeudc.h"

// 00010374: void fn00010374()
// Called from:
//      call_weak_fn
void fn00010374()
{
	g_ptr21018();
}

// tmps1cfeudc_got.c
// Generated by decompiling tmps1cfeudc
// using Reko decompiler version 0.11.6.0.

#include "tmps1cfeudc.h"

<anonymous> * __libc_start_main_GOT = null; // 0002100C
<anonymous> * printf_GOT = null; // 00021010
<anonymous> * puts_GOT = null; // 00021014
<anonymous> * g_ptr21018 = null; // 00021018
<anonymous> * abort_GOT = null; // 0002101C
// tmps1cfeudc_bss.c
// Generated by decompiling tmps1cfeudc
// using Reko decompiler version 0.11.6.0.

#include "tmps1cfeudc.h"

byte g_b2102C = 0x00; // 0002102C
