// tmp5u6j2cts_TEXT_text_startup.c
// Generated by decompiling tmp5u6j2cts
// using Reko decompiler version 0.11.6.0.

#include "tmp5u6j2cts.h"

// 0000000100003E10: void main()
void main()
{
	all_badges();
	polynome_table();
	red_herring();
}

// tmp5u6j2cts_TEXT_text.c
// Generated by decompiling tmp5u6j2cts
// using Reko decompiler version 0.11.6.0.

#include "tmp5u6j2cts.h"

// 0000000100003BD8: void all_badges()
// Called from:
//      main
void all_badges()
{
	printf();
}

// 0000000100003C64: void polynome_table()
// Called from:
//      main
void polynome_table()
{
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
	printf();
}

// 0000000100003D8C: void red_herring()
// Called from:
//      main
void red_herring()
{
	puts();
	printf();
	printf();
	printf();
	printf();
	printf();
}

// tmp5u6j2cts_TEXT_stubs.c
// Generated by decompiling tmp5u6j2cts
// using Reko decompiler version 0.11.6.0.

#include "tmp5u6j2cts.h"

// 0000000100003E30: void printf()
// Called from:
//      all_badges
//      polynome_table
//      red_herring
void printf()
{
	__imp__printf();
}

// 0000000100003E3C: void puts()
// Called from:
//      red_herring
void puts()
{
	__imp__puts();
}

// tmp5u6j2cts.globals.c
// Generated by decompiling tmp5u6j2cts
// using Reko decompiler version 0.11.6.0.

#include "tmp5u6j2cts.h"

<anonymous> * __imp__dyld_stub_binder; // 0000000000004000
<anonymous> * __imp__printf; // 0000000000008000
<anonymous> * __imp__puts; // 0000000000008008
