// tmpwr3xt_8q_TEXT_text_startup.c
// Generated by decompiling tmpwr3xt_8q
// using Reko decompiler version 0.11.6.0.

#include "tmpwr3xt_8q.h"

// 0000000100000E80: void main()
void main()
{
	short_multiplication_table();
	count_sheep();
}

// tmpwr3xt_8q_TEXT_text.c
// Generated by decompiling tmpwr3xt_8q
// using Reko decompiler version 0.11.6.0.

#include "tmpwr3xt_8q.h"

// 0000000100000690: void count_sheep()
// Called from:
//      main
void count_sheep()
{
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("(nice) ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	printf("%d ");
	puts("ZzZzZz...");
}

// 0000000100000C90: void short_multiplication_table()
// Called from:
//      main
void short_multiplication_table()
{
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\n");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\n");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\n");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\n");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\t");
	printf("%2d \xC3\x97 %3d = %4d\n");
}

// tmpwr3xt_8q.globals.c
// Generated by decompiling tmpwr3xt_8q
// using Reko decompiler version 0.11.6.0.

#include "tmpwr3xt_8q.h"

<anonymous> * __imp__dyld_stub_binder; // 0000000000001000
<anonymous> * __imp__printf; // 0000000000002000
<anonymous> * __imp__puts; // 0000000000002008
// tmpwr3xt_8q_TEXT_stubs.c
// Generated by decompiling tmpwr3xt_8q
// using Reko decompiler version 0.11.6.0.

#include "tmpwr3xt_8q.h"

// 0000000100000E9C: Register int32 printf(Register (ptr64 char) rdi)
// Called from:
//      count_sheep
//      short_multiplication_table
int32 printf(char * rdi)
{
	return printf(rdi, 0x00);
}

// 0000000100000EA2: Register int32 puts(Register (ptr64 char) rdi)
// Called from:
//      count_sheep
int32 puts(char * rdi)
{
	return puts(rdi);
}

