// Generated by Rec Studio 4 - build Sep 23 2015

_init()
{// addr = 0x00001000
    __rax = __imp____gmon_start__;
    if(__rax != 0) {
         *__rax();
        return;
    }
}

puts()
{// addr = 0x00001030
    goto __imp__puts;
}

printf()
{// addr = 0x00001040
    goto __imp__printf;
}

__cxa_finalize()
{// addr = 0x00001050
    goto __imp____cxa_finalize;
}

main(
    _unknown_ __rax                        // r53
)
{// addr = 0x00001060
    __rax = __rax;
    all_badges();
    polynome_table();
    red_herring();
}

_start(
    _unknown_ __rax,                       // r53
    _unknown_ __rcx,                       // r55
    _unknown_ __rdx                        // r56
)
{// addr = 0x00001080
    _pop(__rsi);
    __r9 = __r9 & -16;
    _push(__rax);
    _push(__r9);
    __imp____libc_start_main();
    asm("hlt");
    asm("o16 nop [cs:rax+rax]");
    if(16592 != 16592 && __imp___ITM_deregisterTMCloneTable != 0) {
        goto __rax;
    }
}

deregister_tm_clones()
{// addr = 0x000010B0
    if(16592 == 16592 || __imp___ITM_deregisterTMCloneTable == 0) {
        return;
    } else {
        goto __rax;
    }
}

register_tm_clones()
{// addr = 0x000010E0
    if(16592 == 0 || __imp___ITM_registerTMCloneTable == 0) {
        return;
    } else {
        goto __rax;
    }
}

__do_global_dtors_aux(
    _unknown_ __rax                        // r53
)
{// addr = 0x00001120
    _unknown_ _t3;                         // _t3

    __rax = __rax;
    asm("invalid");
    if(completed.0 != 0) {
        return;
    } else {
        _push(_t3);
        if(__imp____cxa_finalize != 0) {
            __cxa_finalize();
        }
        deregister_tm_clones();
        completed.0 = 1;
        _pop(__r8);
        return;
    }
}

frame_dummy()
{// addr = 0x00001160
    asm("invalid");
    if(16592 != 0 && __imp___ITM_registerTMCloneTable != 0) {
        goto __rax;
    }
}

all_badges()
{// addr = 0x00001170
    goto __imp__printf;
}

polynome_table()
{// addr = 0x000011F0
    __rbx = "P(%d) = %d\n";
    L1();
    L1();
    L1();
    L1();
    L1();
    L1();
    L1();
    L1();
    L1();
    L1();
    _pop(__rbx);
    goto __imp__printf;
}

red_herring()
{// addr = 0x000012E0
    __rbx = " *  %d\n";
    puts();
    L1();
    L1();
    L1();
    L1();
    _pop(__rbx);
    goto __imp__printf;
}

_fini(
    _unknown_ __rax                        // r53
)
{// addr = 0x00001340
    __rax = __rax;
}

_fini(
    _unknown_ __rax                        // r53
)
{// addr = 0x00001340
    __rax = __rax;
}

// Statistics:
//      23 Register nodes
//       1 Temporaries nodes
//       0 Casts
//      47 Statements
//       0 Labels
//       0 Gotos
//      14 Blocks
//     158 Nodes
//       4 Assembly nodes
//       7 Unknown Types


Total time: 0 seconds.
