#!/usr/bin/python
import os, sys
import multiprocessing
import random
import subprocess
import time

import requests
try:
    import tqdm
except ImportError:
    sys.stderr.write(f"TQDM not found. Try: 'sudo apt-get install python3-tqdm' or 'pip install tqdm'")
    sys.exit(1)

def download_as(project_dir, filename, url):
    file_stat = None
    dir_stat = None
    try:
        file_stat = os.stat(filename)
    except FileNotFoundError:
        print(f"Downloading '{url}'... ", end="", flush=True)
        r = requests.get(url)
        r.raise_for_status()
        with open(filename, "wb+") as f:
            f.write(r.content)
        file_stat = os.stat(filename)
        print("done.");

    try:
        dir_stat = os.stat(project_dir)
        if dir_stat.st_mtime < file_stat.st_mtime:
            subprocess.call(["rm", "-rf", project_dir])
            dir_stat = None
    except FileNotFoundError: pass
    if dir_stat is None:
        os.makedirs(project_dir)
        subprocess.call(["tar", "-C", project_dir, "-xf", filename])

os.chdir(".cache")

download_as("coreutils", "coreutils-9.7.tar.gz", "https://ftp.gnu.org/gnu/coreutils/coreutils-9.7.tar.gz")
download_as("godot", "godot-4.4.1-stable.tar.gz", "https://github.com/godotengine/godot/archive/refs/tags/4.4.1-stable.tar.gz")
download_as("openssl", "openssl-3.5.0.tar.gz", "https://github.com/openssl/openssl/releases/download/openssl-3.5.0/openssl-3.5.0.tar.gz")

os.chdir("openssl/openssl-3.5.0")
if not os.path.exists("Makefile.in"):
    subprocess.call(["./Configure"])
subprocess.call(["make", "-j", "4"])
os.chdir("../..")

os.chdir("coreutils/coreutils-9.7")
if not os.path.exists("Makefile"):
    subprocess.call(["./configure"])
subprocess.call(["make", "-j", "4"])
os.chdir("../..")

os.chdir("godot/godot-4.4.1-stable")
subprocess.call(["scons"])
os.chdir("../..")

os.chdir("..")
workload = []
for project in ("openssl","coreutils","godot"):
    findcmd = ["find", f".cache/{project}", "-type", "f", "-name", "*.o"]
    objfiles = subprocess.run(findcmd, capture_output=True, encoding="utf-8").stdout.strip().split("\n")

    for objfile in objfiles:
        outfile = f"decompilations/{project}/" + " ".join(objfile.split("/")[3:])[:-2] + ".c"
        workload.append((objfile, outfile))

random.shuffle(workload)


def decompile(wu):
    objfile, outfile = wu
    if os.path.exists(outfile):
        return
    try:
        subprocess.call(["python", "./decomp-headless", objfile, "-o", outfile], timeout=60)
    except subprocess.TimeoutExpired:
        time.sleep(5)
        with open(outfile, "a+") as f:
            f.write("// This is taking way too long.")

t = tqdm.tqdm(total=len(workload))

with multiprocessing.Pool() as p:
    for _ in p.imap_unordered(decompile, workload):
        t.update(1)

t.close()
